### ISSUE TITLE
[BUG]feeds update stopped

### ISSUE THREAD

**Issue by shawn8888** [HenryQW/Awesome-TTRSS#100]
HenryQW 大神：我用的是您的docker image 在群晖上部署TTRSS: wangqiru/ttrss 昨天莫名停止更新了，20个小时之后才发现。家里的网络一切正常，不知道是什么原因引起的。我把container restart了一下，现在似乎恢复正常。请教：
1.	Docker下的TTRSS是如何 Refresh feeds的？我看了一下官方的文档：
https://git.tt-rss.org/fox/tt-rss/wiki/UpdatingFeeds
但是好象没有关于docker的解释
2.	为了防止以后再次发生这样问题，如何查看update error log，或者更好一点，有没有可能更新出错就发通知(email之类)？

**Comment by HenryQW** [comment]
s6 supervise 以下目录：https://github.com/HenryQW/Awesome-TTRSS/blob/master/src/s6/update-daemon/run

log 可以通过 
```
docker logs ttrss -f —tail 50
```
进行查看

**Comment by shawn8888** [comment]
今天发现又有feed没有更新，但不是全部。非常伤脑筋...
看了一下log，似乎有memory的问题？但是docker的memory好象无法指定大小。而且群晖的内存也足够，很多free。请帮忙看一下。
[error.txt](https://github.com/HenryQW/Awesome-TTRSS/files/3935127/error.txt)

**Comment by shawn8888** [comment]
docker里ttrss的memory limit本来是auto，把它设成2GB，重启。还是在log里看到这个fatal error:

```
[14:26:34/58]  => 1970-01-01 00:00:00, 98 2
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 46243083 bytes) in /var/www/classes/rssutils.php on line 1551
[14:26:37/57] removing lockfile (57)...
[14:26:37/21] [reap_children] child 57 reaped.
```

但是，停止更新的feed并不是这个engadget-cn，我也没有在log里看到停更feed的错误。

**Comment by HenryQW** [comment]
没有相关方法可以查询，ttrss 没有提供该功能。
