### ISSUE TITLE
[BUG]favicon 间歇性消失，重现，无法指定feed-icons directory

### ISSUE THREAD

**Issue by shawn8888** [HenryQW/Awesome-TTRSS#111]
**Bug 描述**
简洁明了地描述这个 bug。
favicon 间歇性消失，隔天重现。强制force refetch也能重现

**你谷歌/百度了吗？**
请善用搜索引擎。
YES

**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]
latest watchtower自动更新

**部署环境**
 - 操作系统: [如 Ubuntu 18.04]
 - 浏览器: [如 chrome, safari]
群晖 docker

**复现步骤**
复现该 bug 的详细步骤

favicon 间歇性消失

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。
favicon 长期保存

**截屏**
![T3](https://user-images.githubusercontent.com/8271101/71317491-e585f800-244f-11ea-8b0d-0250b98bab8f.png)

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

在TTRSS论坛上提问，作者fox提示是docker的 feed-icons directory设置问题：
`favicons are stored on the filesystem. if they don’t persist, this means whatever docker container you’re using is not storing feed-icons directory properly.`

https://community.tt-rss.org/t/add-autoload-favicon-from-the-site-url-option-in-edit-feed-window/3051/9

**Comment by HenryQW** [comment]
源列表的favicon一直有这个bug，文章列表里的favicon一直是有的。
docker只是一种部署方式，对于源代码不做任何更改。任何上游repo的bug我无力修复。

**Comment by shawn8888** [comment]
请问， feed-icons 目录有没有可能映射到docker container外部存储呢？
我怀疑更新TTRSS时会导致这个目录被重写
如果真是bug的话，能不能去跟fox提一下？

**Comment by HenryQW** [comment]
根本就不知道这个目录存储在哪里，你可以自行映射。

每一次更新docker镜像就意味着你重装了一次系统，除非目录映射不然所有数据都会丢失。

图标本就该存储在数据库里，不知道这个设计的动机是什么。

**Comment by HenryQW** [comment]
说实话这不影响使用，而且TTRSS的网页版体验实在糟糕，为何不用更现代的阅读器呢？

**Comment by shawn8888** [comment]
我感觉相反，我也用ipad 上的Reeder 3，远不及PC浏览器+大屏幕+键盘体验好。
您熟悉docker部署，能不能帮忙查一下这个feed-icons目录在哪里？
非常希望能映射出来。实在不希望每次更新都丢失所有的favicon。作者的动机是什么不清楚，但他最初肯定不是为了docker设计的TTRSS

**Comment by shawn8888** [comment]
又更新docker了，icon又消失...
真的很希望知道怎样映射这个feed-icons目录...
谢谢！

**Comment by shawn8888** [comment]
自己研究了半天，终于找到。贴在这里算是给自己一个交待。
这两个是官方推荐需要映射到docker外部的目录。否则，favicon会在更新后丢失，自己装的plugin需要在更新后重装。
/var/www/feed-icons
/var/www/plugins.local
群晖设置的截图：
![T7](https://user-images.githubusercontent.com/8271101/71426338-fc0d9880-2675-11ea-9b7f-d770e95211b9.png)

两个目录都要给写权限。为了省事， 我直接
`chmod -R 777`
