### ISSUE TITLE
求问迁移服务器为什么还是提示SELF_URL_PATH

### ISSUE THREAD

**Issue by stilleshan** [HenryQW/Awesome-TTRSS#113]
原服务器的 docker-compose.yml 和postgres 拷贝到新服务器  
两台服务器的配置几乎一模一样.  
域名的nginx conf也拷贝过来,域名也解析过来.  
直接docker-compose up -d  启动报以下错误  
删除postgres启新容器缺没问题..  

我是菜鸟,不知道迁移过来的启动命令是否有其他的? 求教

Startup failed
Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:

Please set SELF_URL_PATH to the correct value detected for your server: https://rss.xxx.com/
You might want to check tt-rss wiki or the forums for more information. Please search the forums before creating new topic for your question.

Exception while creating PDO object:SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Network unreachable
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

**Comment by HenryQW** [comment]
数据库连接有误。

**Comment by stilleshan** [comment]
新启一个到没问题,那请指点,能否新启一个,然后拷贝以前的数据过来来迁移呢?
以前的数据和配置是哪些文件呢?

**Comment by HenryQW** [comment]
可以尝试 https://ttrss.henry.wang/zh/#postgres-%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB

**Comment by stilleshan** [comment]
不过我原服务器也是用的最近的这个部署的,并不是老数据库呢

**Comment by HenryQW** [comment]
我多年前用同版本数据库迁移过一次 VPS，没有遇到过该问题。这个迁移步骤同样适用于同版本数据库之间的迁移。尝试之前做好备份。

**Comment by stilleshan** [comment]
非常感谢,已按照教程成功迁移.数据配置都在.
