### ISSUE TITLE
部署后显示ttrss operation time out

### ISSUE THREAD

**Issue by Boycottangent** [HenryQW/Awesome-TTRSS#114]
**Bug 描述**
docker-compose 部署，修改配置后 `docker-compose up -d` ，访问 `ip:port` 显示无法打开。yml 中改动了 database password 和 `SELF_URL_PATH` (ip:port，端口默认 181 )

**你谷歌/百度了吗？**
未找到可用解决方法

**部署方法**
 - docker-compose
 - latest

**部署环境**
 - CentOS 8

**截屏**

<img width="854" alt="image" src="https://user-images.githubusercontent.com/23280916/71766692-8e971d00-2f3d-11ea-9de1-cea2a96c3f87.png">

**错误日志**
```
# docker logs ttrss --tail 100
Operation timed out
```
同 #55 但这个issue没有提供解决方案

**Comment by HenryQW** [comment]
贴配置上来。

**Comment by Boycottangent** [comment]
后来排查应该是 CentOS firewalld 相关的问题，和 ttrss 无关

**Comment by realJackWang** [comment]
> 后来排查应该是 CentOS firewalld 相关的问题，和 ttrss 无关

我也是同样的问题，想问一下你的防火墙是怎么修改的呢？

**Comment by Boycottangent** [comment]
> > 后来排查应该是 CentOS firewalld 相关的问题，和 ttrss 无关
> 
> 我也是同样的问题，想问一下你的防火墙是怎么修改的呢？

确保你使用的端口已经开放了
```
firewall-cmd --zone=public --add-port=xxxx/tcp --permanent
firewall-cmd --reload
```
注意这是CentOS 7的解决方案，不适用8，二者的防火墙策略不同，如果可以的话在CentOS 7环境下部署

**Comment by realJackWang** [comment]
> > > 后来排查应该是 CentOS firewalld 相关的问题，和 ttrss 无关
> > 
> > 
> > 我也是同样的问题，想问一下你的防火墙是怎么修改的呢？
> 
> 确保你使用的端口已经开放了
> 
> ```
> firewall-cmd --zone=public --add-port=xxxx/tcp --permanent
> firewall-cmd --reload
> ```
> 
> 注意这是CentOS 7的解决方案，不适用8，二者的防火墙策略不同，如果可以的话在CentOS 7环境下部署

谢谢，我是centOS 8，我刚刚重启了一下firewall的服务就好了，之前添加了端口没有重启。

**Comment by AlvinCR** [comment]
经测试debian禁用防火墙重新开启也不行，重启docker和防火墙后，从awesome_ttrss容器内部ping不通postgres。干脆直接让postgres加入public_access，舍弃安全性，已成功访问
