### ISSUE TITLE
Add Duplicate Posts Patch

### ISSUE THREAD

**Issue by strobemarch** [HenryQW/Awesome-TTRSS#115]
**Is your feature request related to a problem? Please describe.**
I have a bunch of feeds (8000+) that all use the same id when adding new articles. TTRSS by default automatically removes every feed after the original because they use the same ID, even though they are new articles. I want these new articles to show up in TTRSS, even if it thinks they are duplicates.

**Describe the solution you'd like**
There's a plugin that adds a "allow duplicate posts" option back into TTRSS. I would like it to be added in order to remedy this issue across my a-TTRSS installs.

**Additional context**
https://github.com/DigitalDJ/tinytinyrss-allow-duplicate-posts

**Comment by HenryQW** [comment]
You can always install plugins locally by mounting the plugin into directory. Modify your compose file, under ttrss container:
```yml
volumes:
    - /plugins-folder-on-your-host:/var/www/plugins.local
```
