### ISSUE TITLE
[BUG]Use of undefined constant GLOB_BRACE

### ISSUE THREAD

**Issue by jostyee** [HenryQW/Awesome-TTRSS#118]
**Bug 描述**
ttrss的event log里面出现很多：
```
1. plugins/cache_starred_images/init.php(77): glob(cache/starred-images/*.{png,mp4,status}, GLOB_BRACE)
2. classes/pluginhost.php(129): hook_house_keeping()
3. classes/rssutils.php(1513): run_hooks(24, hook_house_keeping, )
4. update.php(253): housekeeping_common(1) | 
```

**你谷歌/百度了吗？**
按照官方论坛 https://community.tt-rss.org/t/php-7-3-use-of-undefined-constant-glob-brace/2230/3 的讨论，应该是项目Docker base image选用了alpine不带glibc导致

**部署方法**
 -  docker-compose
 - latest

**部署环境**
 - Ubuntu 18.04
 - safari

**复现步骤**
复现该 bug 的详细步骤
1. 打开 Preferences
2. 点击 'System'
3. 查看Event log

**其他**
可以考虑把base image换到 https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc 添加glibc集成。

**Comment by HenryQW** [comment]
这个 base image 集成 glibc 的做法可能会导致 arm 架构无法正常 build，有空我要试一下。

**Comment by HenryQW** [comment]
最近生活琐事缠身实在没空，欢迎大家 PR。

**Comment by HenryQW** [comment]
@jostyee 请测试 wangqiru/ttrss:dev

**Comment by jostyee** [comment]
@HenryQW 我没有ARM架构（RPi等）设备测试，只能在x86上检查。。

**Comment by jostyee** [comment]
ttrss:dev on Ubuntu 18.04

![image](https://user-images.githubusercontent.com/88564/76135521-738e7980-6062-11ea-97ed-c36aac719123.png)

**Comment by jostyee** [comment]
现在还多了个 `Legacy connect requested to pgsql` ，切到主线版本也有，貌似pgo没用上？

**Comment by HenryQW** [comment]
那就是上游的问题啦

**Comment by HenryQW** [comment]
> 现在还多了个 `Legacy connect requested to pgsql` ，切到主线版本也有，貌似pgo没用上？

上游貌似解决了这个问题，麻烦测试一下最新版 dev

**Comment by jostyee** [comment]
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/88564/76919093-d43f7100-6902-11ea-846e-e8b27d7de832.png">

还是一样

**Comment by HenryQW** [comment]
hmmm...为什么我这里什么警告日志都没有？

**Comment by jostyee** [comment]
因为我加了个官方插件？

`- ENABLE_PLUGINS=auth_internal,cache_starred_images,fever`

**Comment by xcffl** [comment]
`cache_starred_images` 確實有這個問題

**Comment by xcffl** [comment]
破案了，是因爲 alpine 的 musl 不支援 `glob()`：https://community.tt-rss.org/t/php-7-3-use-of-undefined-constant-glob-brace/2230/3

**Comment by xcffl** [comment]
> 貌似pgo没用上

似乎需要在 php.ini 裏加上
````
extension=pdo.so
````
https://www.php.net/manual/en/pdo.installation.php

**Comment by dimon222** [comment]
This is not resolved, its still being thrown on current `latest` docker tag.

**Comment by HenryQW** [comment]
@dimon222 I do not see relevant logs from my TTRSS instance, on the latest tag. Can you post your env and plugins enabled so we can find out what happened?

**Comment by dimon222** [comment]
Configuration - running from `docker-compose.yml` that in root of this repository.

I guess its always this culprit?
![image](https://user-images.githubusercontent.com/2671025/107419924-57068700-6ae6-11eb-8bbe-69ddd9e79d53.png)

New 3 log stacktraces appear every time update-daemon.php runs any feed fetching.
Error screenshot:
![image](https://user-images.githubusercontent.com/2671025/107419721-1a3a9000-6ae6-11eb-9310-3f46e36a65b4.png)
