### ISSUE TITLE
Mercury Parser API 的配置咨询

### ISSUE THREAD

**Issue by stilleshan** [HenryQW/Awesome-TTRSS#119]
查看了文档,关于Mercury Parser API 地址,是必须使用 https://rss域名:3000 吗?还是可以内网IP之类?
那么docker-compose.yml内还得需要在mercury内配置port 3000到宿主机吧?

**Comment by stilleshan** [comment]
另外此API交互是服务器容器之间,还是用户外网访问?
也就是说如果映射3000端口到宿主机,能否使用 http://127.0.0.1:3000 来连接?

**Comment by stilleshan** [comment]
尝试编辑docker-compose.yml映射了端口后
使用 http://域名:3000/ 可以显示
`{"message":"Welcome to 🚀mercury-parser-api API! Endpoint: /parser"}`
配置到Mercury Parser API 地址,设置几个订阅使用Mercury插件,都无法显示全文..
不知道错在哪...甚至 API 地址尝试 mercury:3000 也不行...

**Comment by HenryQW** [comment]
文档中的样例可以直接使用，docker 自带 service discovery，无需自行配置端口。

**Comment by stilleshan** [comment]
感谢大佬这么晚还在线回复,但是我尝试按照样例输入了`https://mercury:3000`或者http协议,都无法显示全文..不知道还有哪里有可能会影响此功能呢?至少设置过4个源都没成功

**Comment by stilleshan** [comment]
> 文档中的样例可以直接使用，docker 自带 service discovery，无需自行配置端口。

感谢大佬这么晚还在线回复,但是我尝试按照样例输入了https://mercury:3000或者http协议,都无法显示全文..不知道还有哪里有可能会影响此功能呢?至少设置过4个源都没成功

**Comment by stilleshan** [comment]
@HenryQW 
mercury:3000
service.mercury:3000
http://mercury:3000
https://mercury:3000
都尝试过无法获取全文，实在是找不出其他问题了，Google上搜索也没看到有相关同类问题！

**Comment by HenryQW** [comment]
不知道你的compose配置，按照样例
https://github.com/HenryQW/Awesome-TTRSS/blob/a670d7c055f83b0256a4f5dab555bba88b0faa86/docker-compose.yml#L30
应该为
![image](https://user-images.githubusercontent.com/5896343/73384978-36e19c80-42c4-11ea-96c6-4cada8f162c1.png)

检查一下你的防火墙吧。

**Comment by HenryQW** [comment]
还有就是，已有文章不会抓取全文，只针对新文章。

**Comment by stilleshan** [comment]
> 还有就是，已有文章不会抓取全文，只针对新文章。
> 你也可以通过 `docker logs mercury --tail 10 -f`来检查是否有请求。

@HenryQW 
非常感谢
