### ISSUE TITLE
tinytinyrss-fever-plugin v2.3 - 2020/01/27

### ISSUE THREAD

**Issue by levinneed** [HenryQW/Awesome-TTRSS#121]
v2.3 - 2020/01/27

Fix error thrown when str_repeat() is passed negative length
Removes references to CCache class which has been scrapped and replaced

[v2.3 - 2020/01/27 changelog](https://github.com/DigitalDJ/tinytinyrss-fever-plugin#changelog)

**Comment by HenryQW** [comment]
Should be fixed by https://github.com/HenryQW/tinytinyrss-fever-plugin/commit/a3d99ed1384ec710c7546a8f454bc19c5e229f23 and the CI will automatically rebuild this repo.

Credit @eric-pierce
