### ISSUE TITLE
[技术咨询]关于 volumes: -v - ~/postgres/data/

### ISSUE THREAD

**Issue by stilleshan** [HenryQW/Awesome-TTRSS#122]
先感谢大佬之前对我的issue提供帮助...作为docker新手,想咨询个技术问题.

关于 -v 挂载我大致也知道了点原理..根据这个docker-compose.yml描述,挂载本地~/postgres/data/到容器内,宿主机本身是没有~/postgres/data/这个目录的,我猜测应该是整个compose容器启动时rss容器里的command命令创建了数据库,所以才会自动创建这个目录,并写入了数据库文件. 可以这么理解么?

然后当容器一直运行,此目录的数据一天天增加,如果后期docker-compose down后在up启动时(或者是迁移),按理说会根据yml里rss的command命令又创建一次数据库....那么此时由于本地已经存在这个~/postgres/data/目录,所以容器就直接挂载使用现有的数据..并不会重新创建覆盖..这么理解对么?

期待大佬的提点...

**Comment by HenryQW** [comment]
没错

**Comment by stilleshan** [comment]
@HenryQW 感谢.
