### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ZhuningS** [HenryQW/Awesome-TTRSS#124]
**Bug 描述**
简洁明了地描述这个 bug。
按照文档执行Postgres 数据库迁移 cat export.sql | docker exec -i postgres psql -U postgres 后，命令行报错
ERROR:  database "myttrss" does not exist
ERROR:  current user cannot be dropped
ERROR:  role "postgres" already exists

打开阅读器 报错：Exception while creating PDO object:SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres"
**你谷歌/百度了吗？**
请善用搜索引擎。
已百度
**部署方法**
 docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]
latest
**部署环境**
 - 操作系统: 群晖6.2.1
 - 浏览器:  chrome,
**复现步骤**
复现该 bug 的详细步骤
按照官方文档，执行Postgres 数据库迁移操作 cat export.sql | docker exec -i postgres psql -U postgres 后，命令行报错
ERROR:  database "myttrss" does not exist
ERROR:  current user cannot be dropped
ERROR:  role "postgres" already exists

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。
正常打开阅读器
**截屏**
如果可以提供截屏将有助于 bug 修复。
![image](https://user-images.githubusercontent.com/38108376/75087091-1df0a200-5577-11ea-841c-69307ae80b19.png)

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
`-U postgres` 为你数据库的用户名。

新数据必须初始化，且 `DB_NAME` 必须与旧数据相同。
