### ISSUE TITLE
[Feature Request] 希望能添加wallabag插件

### ISSUE THREAD

**Issue by fasheng** [HenryQW/Awesome-TTRSS#126]
该插件可以将加星标的文章全文缓存到wallabag，还是很有用的。

https://community.tt-rss.org/t/save-to-wallabag-plugin/2128
https://github.com/joshp23/ttrss-to-wallabag-v2

**Comment by HenryQW** [comment]
最近没空哦，可以自行下载插件，map 至 /var/www/plugins/。

**Comment by HenryQW** [comment]
@fasheng 已经添加了 wallabag 插件哦，但是我没找到如何自动将星标文章添加到 wallabag？

**Comment by fasheng** [comment]
抱歉没办法测试了，已经转用miniflux，内置wallabag插件。
