### ISSUE TITLE
[BUG]已解决！Fever Emulation无法保存密码

### ISSUE THREAD

**Issue by jinyebai** [HenryQW/Awesome-TTRSS#130]
**Bug 描述**
已解决！开启Fever Emulation后设置密码无法保存
**你谷歌/百度了吗？**
搜索了
**部署方法**
docker-compose
latest
**部署环境**
centos7.7x64
**复现步骤**
复现该 bug 的详细步骤
1.访问域名：181端口
2.打开偏好设置
3.Fever Emulation插件，设置密码，无法保存
**预期结果**
应正常设置fever的密码
**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by jinyebai** [comment]
有人说把postgres的volumes改成自己本地的一个目录就行了，但试了后依然不行

**Comment by xcffl** [comment]
点击保存如果通过开发者工具查看请求，应该会发现是200的。但不会有界面提示。
