### ISSUE TITLE
[BUG]使用Fever插件无法初始化密码

### ISSUE THREAD

**Issue by ianchang0822** [HenryQW/Awesome-TTRSS#134]
**Bug 描述**
按照指引安装了Fever插件，在初始化密码的时候点击按钮无反应，并没有出现密码保存成功。
在Reeder上可以正常访问，但是显示错误，无法进入。
有报错日志

**你谷歌/百度了吗？**
google上的错误是没有打开API，但是我已经打开了

**部署方法**
docker-compose

**部署环境**
 - 操作系统: CentOS
 - 浏览器: chrome

**复现步骤**
复现该 bug 的详细步骤
1. 打开偏好设置
2. 点击 保存密码
4. 发现错误

**预期结果**
可以正常的保存密码

**截屏**
![image](https://user-images.githubusercontent.com/44132083/77822283-48142180-712c-11ea-9353-806d03c2cdd6.png)

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
> 在初始化密码的时候点击按钮无反应，并没有出现密码保存成功
这是正常的，由于 ttrss 上游代码改动，fever 插件还没有更新。没有提示，但是点击按钮的时候密码会正常保存。

> 在Reeder上可以正常访问，但是显示错误，无法进入。
这是由于其他原因导致的，请按照文档仔细排查。截图中的只是警告，并不是相关错误的日志。
