### ISSUE TITLE
[Feature] Nginx 通过网站子目录进行反向代理的配置文件应该如何编写？

### ISSUE THREAD

**Issue by madobet** [HenryQW/Awesome-TTRSS#135]
**该功能能够解决的问题**
没有一级域名的用户可以通过子目录的方式在同一个域名下部署多个互不冲突的服务

**形容理想的解决方案**
大概只需要一个合适的 Nginx 配置文件，但是我写不出来，希望的效果是：
```nginx
location /ttrss/ {
    proxy_pass http://[::1]:{{ docker_ttrss_port }};

	# 其他配置...
}
```
然后访问 `https://foo.example.com/ttrss` 访问 TTRSS

**其他**
任何有助于解决方案开发的信息，如：某插件已实现相关功能。

**Comment by HenryQW** [comment]
建议尝试文档重的配置，
https://ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https

更改为 `location /ttrss/`

**Comment by madobet** [comment]
> 建议尝试文档重的配置，
> [ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https](https://ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https)
> 
> 更改为 `location /ttrss/`.
> 
> 可以参考 #133.

单纯更改 location 不行，在 `location /ttrss/` 的基础上加了两条 rewrite 规则进去可以，但是每次在 `example.com/ttrss` 下登录，就会被错误的重定向到 `example.com`，必须手动输入 `example.com/ttrss`。猜测是 TTRSS 登录后返回给浏览器的 URL 的问题，可能需要对 TTRSS 本身做些配置

**Comment by madobet** [comment]
测试出了一种可行的配置，以文档中的配置为基础，保持 `SELF_URL_PATH` 不变，分别对 Nginx 配置作以下修改：
- `location /` 改为 `localtion /ttrss/`
- 开启 `proxy_redirect https://$http_host https://$http_host/ttrss`
- `rewrite /ttrss/(.*) $1 break`
如果我想对这个项目的文档提一个 PR 添加这种配置方式，请问应该修改哪个文件？

**Comment by madobet** [comment]
> 建议尝试文档重的配置，
> [ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https](https://ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https)
> 
> 更改为 `location /ttrss/`.
> 
> 可以参考 #133.

测试出了一种可行的配置，以文档中的配置为基础，保持 `SELF_URL_PATH` 不变，分别对 Nginx 配置作以下修改：
- `location /` 改为 `localtion /ttrss/`
- 开启 `proxy_redirect https://$http_host https://$http_host/ttrss`
- `rewrite /ttrss/(.*) $1 break`
如果我想对这个项目的文档提一个 PR 添加这种配置方式，请问应该修改哪个文件？

**Comment by HenryQW** [comment]
repo 没有包含反代的 nginx 配置文件，PR 可以在文档中添加相关部分哦

**Comment by jhongyu** [comment]
> > 建议尝试文档重的配置，
> > [ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https](https://ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https)
> > 更改为 `location /ttrss/`.
> > 可以参考 #133.
> 
> 测试出了一种可行的配置，以文档中的配置为基础，保持 `SELF_URL_PATH` 不变，分别对 Nginx 配置作以下修改：
> 
> * `location /` 改为 `localtion /ttrss/`
> * 开启 `proxy_redirect https://$http_host https://$http_host/ttrss`
> * `rewrite /ttrss/(.*) $1 break`
> 
> 如果我想对这个项目的文档提一个 PR 添加这种配置方式，请问应该修改哪个文件？

我照这种方式修改之后访问页面返回 500 Internal Server Error ，大佬知道该怎么操作吗

**Comment by TangMisaka23001** [comment]
> 
> 
> > > 建议尝试文档重的配置，
> > > [ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https](https://ttrss.henry.wang/zh/#%E9%85%8D%E7%BD%AE-https)
> > > 更改为 `location /ttrss/`.
> > > 可以参考 #133.
> > 
> > 
> > 测试出了一种可行的配置，以文档中的配置为基础，保持 `SELF_URL_PATH` 不变，分别对 Nginx 配置作以下修改：
> > 
> > * `location /` 改为 `localtion /ttrss/`
> > * 开启 `proxy_redirect https://$http_host https://$http_host/ttrss`
> > * `rewrite /ttrss/(.*) $1 break`
> > 
> > 如果我想对这个项目的文档提一个 PR 添加这种配置方式，请问应该修改哪个文件？
> 
> 我照这种方式修改之后访问页面返回 500 Internal Server Error ，大佬知道该怎么操作吗

```
rewrite /ttrss/(.*) /$1 break;
proxy_redirect https://$http_host https://$http_host/ttrss;
```
我配置成这样现在可以正常访问

**Comment by gop167** [comment]
你好
<img width="1386" alt="image" src="https://github.com/HenryQW/Awesome-TTRSS/assets/39524129/dbe7db85-38b5-4921-a889-549e4f8ea915">我把 location 加了/ttrss/就会变成访问站点跳转不到ttrss 
<img width="507" alt="image" src="https://github.com/HenryQW/Awesome-TTRSS/assets/39524129/f1e7e4b1-68d4-4370-9ce7-72d5c2408dd7">

不加就会提示我这个
<img width="1234" alt="image" src="https://github.com/HenryQW/Awesome-TTRSS/assets/39524129/ecba69eb-63f2-4577-9066-7855465aafee">
我好烦啊，大神求教
