### ISSUE TITLE
[BUG]关于undefined -1 如何解决?

### ISSUE THREAD

**Issue by stilleshan** [HenryQW/Awesome-TTRSS#137]
**Bug 描述**
一直有undefine -1这个显示,清理的很多rss,现有的源都能正常订阅,还是如此

**部署方法**
 - docker-compose
 - 使用watchtower保持更新

**部署环境**
 - 操作系统: Centos7
 - 浏览器: Chrome

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
由于有其他人用,docker logs也是其他人的一些订阅信息.

![8cf5745915fbb12061db4bff227f91ce.jpg](https://pic.ioiox.com/images/2020/04/04/8cf5745915fbb12061db4bff227f91ce.jpg)

**Comment by HenryQW** [comment]
#129 建议前往 https://github.com/DIYgod/ttrss-theme-rsshub 提 issue。@DIYgod
