### ISSUE TITLE
忘记登陆密码

### ISSUE THREAD

**Issue by jinyebai** [HenryQW/Awesome-TTRSS#143]
**Bug 描述**
忘记了TinyTinyRSS的登录密码，请问该怎么办，由于没有设置邮箱点击下方的找回也无法重置，可以通过配置文件来修改吗？

**你谷歌/百度了吗？**
未找到解决办法

**部署方法**
docker-compose
latest

**部署环境**
centos7

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
请善用搜索引擎。

通过数据库直接重置为初始密码。
https://community.tt-rss.org/t/how-to-change-my-password/963

**Comment by jinyebai** [comment]
谢谢解决了
