### ISSUE TITLE
[BUG]是否不兼容reeder的主题?

### ISSUE THREAD

**Issue by stilleshan** [HenryQW/Awesome-TTRSS#144]
**Bug 描述**
使用 https://github.com/tschinz/tt-rss_reeder_theme 这个主题,无论挂载还是docker cp进去,切换主题都如下图..是否是不兼容?

**部署方法**
 - docker-compose
 - latest

**部署环境**
 - 操作系统: CentOS7
 - 浏览器:  chrome和safari

**截屏**
[![e73c780b50dfcad4a41105b2e1180d76.jpg](https://pic.ioiox.com/images/2020/04/17/e73c780b50dfcad4a41105b2e1180d76.jpg)](https://pic.ioiox.com/image/dq68)
[![42c164f281c19547b4d12ccff12d18f3.jpg](https://pic.ioiox.com/images/2020/04/17/42c164f281c19547b4d12ccff12d18f3.jpg)](https://pic.ioiox.com/image/dWI3)

**Comment by HenryQW** [comment]
Reeder 主题已经很久没维护了，ttrss 界面已经经历了很多改动。

相关 issue 请查看 https://github.com/tschinz/tt-rss_reeder_theme/issues
