### ISSUE TITLE
[BUG]Exception while creating PDO object:could not find driver</pre>[02:28:18/216] Spawn interval: 120 sec

### ISSUE THREAD

**Issue by xukecheng** [HenryQW/Awesome-TTRSS#145]
**Bug 描述**
TTRSS 容器 log 提示 <pre>Exception while creating PDO object:could not find driver</pre>[02:28:18/216] Spawn interval: 120 sec

**你谷歌/百度了吗？**
用了，似乎和 PHP 相关

**部署方法**
 - Docker
 - latest

**部署环境**
 - Ubuntu 18.04
 - chrome

**复现步骤**
安装该版本
![image](https://user-images.githubusercontent.com/29099863/79708419-efcadc80-82f1-11ea-8bdf-a6d20fcdd580.png)

**预期结果**
正常运行

**截屏**
如果可以提供截屏将有助于 bug 修复。
![image](https://user-images.githubusercontent.com/29099863/79708439-f9ecdb00-82f1-11ea-8c1f-3c0b8b0dd3c9.png)

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。
![image](https://user-images.githubusercontent.com/29099863/79708455-02451600-82f2-11ea-9c32-c7764ac5c873.png)

**其他**

**Comment by hackenfu** [comment]
Exception while creating PDO object:could not find driver
更新后出现此情况，似乎跟楼主一样

**Comment by HenryQW** [comment]
上游不知道更新了什么导致该问题，暂时请用 wangqiru/ttrss:master。

**Comment by HenryQW** [comment]
已修复。

**Comment by xukecheng** [comment]
可以了
