### ISSUE TITLE
请问怎么打开docker自动更新！

### ISSUE THREAD

**Issue by snakwu** [HenryQW/Awesome-TTRSS#154]
自动更新
[样例 docker-compose](#通过-docker-compose-部署） 中包含了 Watchtower，它会自动拉取并更新您所有的服务容器 （包括当前系统上运行的非 Awesome TTRSS 服务的容器）。该服务默认关闭，启用前请确认它将不会影响您其他的服务容器。

说明上是默认关闭的，请问怎么打开，谢谢！

**Comment by HenryQW** [comment]
见[样例 docker-compose]。
