### ISSUE TITLE
Awesone TTRSS 关于nginx反代的文档似乎并不正确

### ISSUE THREAD

**Issue by jase11** [HenryQW/Awesome-TTRSS#159]
在设置子目录哪一块，文档为：
```
location /ttrss/ {
rewrite /ttrss/(.*) $1 break;
proxy_redirect https://$http_host https://$http_host/ttrss;
...
}
```
此时访问 ```https://mydomain.com/ttrss``` 会得到 ```500 Internal server error``` 。原因在于 **rewrite 指令部分有误**，nginx 日志里显示 ```the rewritten URI has a zero length``` 。这跟 ```SELF_URL_PATH``` 是否正确无关，因为此时 nginx 并没有成功反代。

我认为正确的反代配置应为：
```
location /ttrss/ {
rewrite /ttrss(.*) $1 break;
proxy_redirect https://$http_host https://$http_host/ttrss;
...
}
```
这样不用修改 ```SELF_URL_PATH``` ，即仍为 ```https://mydomain.com``` 。访问链接则还是 ```https://mydomain.com/ttrss``` 。

**Comment by jase11** [comment]
奇怪，这个配置会导致媒体缓存失败，因为缓存的图片的链接为 ```https://mydomain.com/public.php?...``` ，不包含 path ```ttrss```。

**Comment by fcs203** [comment]
请问你解决了吗

**Comment by fcs203** [comment]
> 
> 
> 额，这个配置会导致媒体缓存失败，因为缓存的图片的链接为 `https://mydomain.com/public.php?...` ，不包含 path `ttrss`。这应该是 `SELF_URL_PATH` 的问题，可是如果加上 path `ttrss` 的话 `SELF_URL_PATH` 反而会报错。这个该怎么解决？

请问这个解决了吗
