### ISSUE TITLE
拉取 feed 超时，28 Operation timed out after 15000 milliseconds with 6693742 out of 9734186 bytes received

### ISSUE THREAD

**Issue by stormbuf** [HenryQW/Awesome-TTRSS#162]
**Bug 描述**
 - 使用 TTRSS 拉取酷壳 && 阮一峰/科技爱好者周刊 feed 超时，当使用 inoreader 拉取时，则能正常拉取
 - feed 文件能正常 CRUL

**你谷歌/百度了吗？**
目的：想通过配置修改超时时间看看是否能改善情况
结果：无法查到该配置参数

**部署方法**
 - docker-compose
 - 使用的镜像版本 latest
 - postgres 镜像版本为 alpine

**部署环境**
 - 操作系统: centos 7
 
**截屏**
错误情况截图：
![image](https://user-images.githubusercontent.com/37621593/88009827-0299bb00-cb46-11ea-949d-f6d3e14d274b.png)
配置文件截图：
![image](https://user-images.githubusercontent.com/37621593/88010052-910e3c80-cb46-11ea-9edd-207561cb095a.png)

**其他**
阮一峰/科技爱好者周刊使用了自建的 RSSHub 源。

酷壳使用了网站提供的 RSS : https://coolshell.cn/feed

**Comment by HenryQW** [comment]
右键 debug feed，没有发现 issue，建议排查服务器的问题。

![image](https://user-images.githubusercontent.com/5896343/88111028-16283e80-cba5-11ea-88f9-842774d6d510.png)
