### ISSUE TITLE
[BUG] ERROR: In file './docker-compose.yml', the service name True must be a quoted string, i.e. 'True'.

### ISSUE THREAD

**Issue by kid1412621** [HenryQW/Awesome-TTRSS#164]
**Bug 描述**
根据 `docker-compose.yml` 构建报错
`ERROR: In file './docker-compose.yml', the service name True must be a quoted string, i.e. 'True'.`

**你谷歌/百度了吗？**
of course 

**部署方法**
 - Docker 或 docker-compose

docker-compose
 - 使用的镜像版本

19.03.11

**部署环境**
 - 操作系统: 

 Ubuntu 20.04.1 LTS

 - 浏览器: [如 chrome, safari]

safari

**解决步骤**

把第一行 `on: "3"` 改为 `version: "3"`

**Comment by kid1412621** [comment]
说时候，我翻遍了官方文档没找到 `on` 这个指令

**Comment by HenryQW** [comment]
我没看懂，什么意思？

**Comment by kid1412621** [comment]
> 我没看懂，什么意思？

就是构建 docker-compose.yml 里面的一行，我看 legecy 里面是 `version: "3"` 改成了现在的 `on: "3"` ，构建会报错，改回去就好了

**Comment by HenryQW** [comment]
哪一个？你复制错了吧。。

https://github.com/HenryQW/Awesome-TTRSS/blob/master/docker-compose.legacy.yml

https://github.com/HenryQW/Awesome-TTRSS/blob/master/docker-compose.yml

**Comment by kid1412621** [comment]
啊，怎么回事……可能我搞错了

**Comment by Friday21** [comment]
> 啊，怎么回事……可能我搞错了

vim里复制的时候把version 复制成了on (ctrl p 会吃掉前几个字母， 遇到好几次了)
