### ISSUE TITLE
[Feature] 可以配置 FEED_FETCH_TIMEOUT

### ISSUE THREAD

**Issue by gd4Ark** [HenryQW/Awesome-TTRSS#170]
**该功能能够解决的问题**
部分 rss 订阅源可以会比较慢，看了一下 ttrss 本身是可以支持配置 FEED_FETCH_TIMEOUT 的，但是在本项目文档没有看到支持这个配置

**形容理想的解决方案**
希望可以支持配置 FEED_FETCH_TIMEOUT

**Comment by HenryQW** [comment]
相关配置项有两个，`FEED_FETCH_TIMEOUT `, `FILE_FETCH_TIMEOUT `，官方并没有提供相关文档说明，修改后不知道会造成什么负面影响，为了稳定性暂时不提供变量支持。可以自行照葫芦画瓢fork添加。
