### ISSUE TITLE
[BUG]无法从指定的网址下载:; 60 SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by November-raining** [HenryQW/Awesome-TTRSS#173]
**Describe the bug**
https://www.mckinsey.com.cn/feed/  浏览器正常打开，尝试订阅这个源提示
无法从指定的网址下载:; 60 SSL certificate problem: unable to get local issuer certificate

**Have you googled?**
报错error 60: SSL certificate problem: unable to get local issuer certificate

https://curl.haxx.se/ca/cacert.pem
并去拷贝了下cacert.pem到本地-v映射到容器目录

修改了下php.ini文件curl.cainfo = "***********\cacert.pem"   \\映射到容器中的路径
并且-v映射到容器/etc/php7/php.ini
包括后来docker cp手动拷贝重启容器后

尝试类似替换后进入容器curl依然显示报错，亦无法订阅

**Comment by HenryQW** [comment]
这网站的证书配置有误，很大可能性是chain配置错误了。ttrss对证书检查很严格，导致无法订阅

https://www.ssllabs.com/ssltest/analyze.html?d=www.mckinsey.com.cn&latest

**Comment by zuosc** [comment]
@November-raining   使用 fullchain.cer

ssl_certificate     /etc/nginx/cer/fullchain.cer;

**Comment by JoJoJoinme** [comment]
> @November-raining 使用 fullchain.cer
> 
> `ssl_certificate /etc/nginx/cer/fullchain.cer;`

刚开始遇到问题时，思路不对，检索词弄错了。花了两小时排坑，问题解决了，调整检索词，发现这里有正确答案。sad day
