### ISSUE TITLE
[BUG] options_per_feed proxy issue

### ISSUE THREAD

**Issue by LOTehan** [HenryQW/Awesome-TTRSS#174]
**Bug 描述**
Options per feed启用后无法通过http代理访问，具体表现为不使用Options per feed时可以访问的rss在开启相关配置后也无法访问。

**你谷歌/百度了吗？**
谷歌相关信息较少，目前确认信息如下：
1.节点采用docker v2ray 的socks5链接，开启socks5监听点为127.0.0.1:10809。经过curl socks 验证可以连通
此时设置[docker environment](https://blog.vinkdong.com/docker%E4%BD%BF%E7%94%A8socks-proxydocker%E4%BD%BF%E7%94%A8shadowsocks%E4%BB%A3%E7%90%86/)后，境内RSS可访问，墙外不可访问。

2.采用provixy将将socks5的127.0.0.1:10809关联到http的127.0.0.1:1088。经过curl -x 验证可以经http监听端口访问到外网
开启Options per feed设置为127.0.0.1和1088端口，仍然呈现强内外无法订阅

**部署方法**
docker-compose
latest

**部署环境**
 - centos7-x86_64
 - chrome

请问是我哪里理解错了吗？谢谢。

--增--
https://kebingzao.com/2019/02/22/docker-container-proxy/
是否是docker容器环境还需要单独配置一次，标记一下。之后尝试，谢谢。

**Comment by LOTehan** [comment]
> 容器与容器间的通信无法通过127.0.0.1，参见docker network。

谢谢提示；127.0.0.1还是容器内部的地址，这个错误我已更正。我今天尝试了些修正，如下：

Docker_ttrss链接的网络是root_default，在该网络下ip地址为172.19.0.5

新建v2ray容器，设置http监听端口为0.0.0.0:10809；并与root_default关联，PORTS设置了http0.0.0.0:1088->10809/tcp
此时主机可分别通过curl -x 172.19.0.1:1088 http://feeds.feedburner.com/blogto/

新建ubuntu容器，apt-get安装curl。可以通过

**Comment by LOTehan** [comment]
> 容器与容器间的通信无法通过127.0.0.1，参见docker network。

TTRSS插件界面有置顶提示：
以下插件使用按Feed内容挂钩。这可能会导致过多的数据使用和原始服务器负载，从而导致您的实例被禁：Options_Per_Feed (更多信息...https://tt-rss.org/wiki/FeedHandlerPlugins)

**Comment by HenryQW** [comment]
容器IP并不是固定的，建议参考使用[docker-compose直接组建网络](https://github.com/HenryQW/Awesome-TTRSS/blob/master/docker-compose.yml)，这样容器之间通信可以使用service name，从ttrss访问mercury：http://service.mercury:3000

**Comment by HenryQW** [comment]
账号密码明文发送太危险了。。。快改了吧

**Comment by LOTehan** [comment]
> 账号密码明文发送太危险了。。。快改了吧

嘿嘿~密码已擦
IP不固定这点我留意到了，每次重启是会改变。但是172.19.0.1的头地址ip应该不会变吧~
我在容器里能curl通，但不知道为什么Options_peer_feed的启用的订阅还是timeout。我curl的就是订阅地址。

**Comment by LOTehan** [comment]
> 容器IP并不是固定的，建议参考使用[docker-compose直接组建网络](https://github.com/HenryQW/Awesome-TTRSS/blob/master/docker-compose.yml)，这样容器之间通信可以使用service name，从ttrss访问mercury：http://service.mercury:3000

这个建议很棒，我也确实付诸了实践，具体如下
我在docker_v2ray的配置文件中设置了socks5监听端口0.0.0.0:10808；http监听端口为0.0.0.0:10809。将配置文件与docker-compose.yml放在了同一目录下`
并在docker-compose.yml中增加了service.v2ray，代码如下
`  service.v2ray: 
    image: v2ray/official:latest
    container_name: v2ray
    volumes:
      - $PWD:/etc/v2ray
    expose:
      - 10809
      - 10808
    restart: always`

运行docker-compose up -d显示启动成功后，查看运行情况如下
`# docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                 NAMES
46a296247dea        v2ray/official:latest                "v2ray -config=/et..."   27 minutes ago      Up 27 minutes       10808-10809/tcp       v2ray
fa6ab64137f6        ubuntu                               "/bin/bash"              14 hours ago        Up 11 hours                               relaxed_kilby
c81c520bf785        wangqiru/opencc-api-server:latest    "docker-entrypoint..."   47 hours ago        Up 11 hours         3000/tcp              opencc
fdbf4e7f3b3a        wangqiru/mercury-parser-api:latest   "dumb-init -- npm ..."   47 hours ago        Up 11 hours         3000/tcp              mercury
5b5832473237        postgres:alpine                      "docker-entrypoint..."   47 hours ago        Up 11 hours         5432/tcp              postgres
f33aad30163f        wangqiru/ttrss:latest                "sh -c 'sh /wait-f..."   47 hours ago        Up 11 hours         0.0.0.0:666->80/tcp   ttrss`

进入ttrss
`docker exec -it ttrss sh`
分别测试socks和http代理对外网RSS订阅源(blogTO)的连通性
`curl -x service.v2ray:10809 http://feeds.feedburner.com/blogto/
curl --socks5 service.v2ray:10808 http://feeds.feedburner.com/blogto/`
都正常返回了RSS订阅源信息

进入TinyTinyRSS网页端，启动 _偏好设置-插件-options_per_feed_ 并在对应的 _编辑信息源-插件_ 中进行了如下设置
[https://i.loli.net/2020/08/25/4JcfgrWK2SZwaMh.png](url)

但更新后仍然无法获取订阅，报错信息为
blogTO: ; 28 Connection timed out after 15001 milliseconds

请问，是否还有什么其他方面可以尝试的呢，非常感谢。

--------------------------------
因为需要订阅后才能在 _编辑信息源-插件_ 界面设置配置host:port；我是在一个订阅成功的国内信息源的基础上，编辑信息源修改了URL和网址，并配置了插件host:port。是否会与这个操作有关呢？

**Comment by HenryQW** [comment]
Q1: 保存设置之后可以尝试一下右键 debug feed，看看能不能提供更多的日志
![image](https://user-images.githubusercontent.com/5896343/91086431-d989b000-e646-11ea-9a97-f377af0238e0.png)

Q2: 应该没有关系，保存之后下一次请求就会用新的目标地址

Q3: 直接用express暴露的3000端口，然后docker映射，没有什么特殊的写法，见[repo](https://github.com/HenryQW/mercury-parser-api)

**Comment by HenryQW** [comment]
根据目前的信息来看，可能是这个插件出了问题。

可以设置ttrss环境变量 `_HTTP_PROXY` 为 service.v2ray:10809，看看是否所有feed都无法正常更新。

**Comment by LOTehan** [comment]
感谢提示

Debug feed的反馈如下
`[01:19:44/25] start`
`[01:19:44/25] running HOOK_FETCH_FEED handlers...`
`[01:19:44/25] ... Options_Per_Feed`
`[01:19:44/25] === 0.0010 (sec)`
`[01:19:44/25] feed data has not been modified by a plugin.`
`[01:19:44/25] local cache will not be used for this feed`
`[01:19:44/25] last unconditional update request: `
`[01:19:44/25] maximum allowed interval for conditional requests exceeded, forcing refetch`
`[01:19:44/25] fetching [http://feeds.feedburner.com/blogto/] (force_refetch: 1)...`
`[01:19:59/25] fetch done.`
`[01:19:59/25] source last modified: `
`[01:19:59/25] unable to fetch: ; 28 Connection timed out after 15001 milliseconds [0]`

service.ttrss新增环境变量
`      - HTTP_PROXY=service.v2ray:10809`
重启后可以订阅，包括外网RSS。

接下去我会尝试在docker外搭建ttrss然后按插件的说明再手动加载一次看看，有结果再联系

**Comment by LOTehan** [comment]
> 根据目前的信息来看，可能是这个插件出了问题。
> 
> 可以设置ttrss环境变量 `HTTP_PROXY` 为 service.v2ray:10809，看看是否所有feed都无法正常更新。

测试结果是插件是可以用的；应该是我们的环境没有配置完全；我先阐述一下我的尝试过程如下:

我在宿主机上按照[TTRSS Centos7安装教程](https://www.vultr.com/docs/how-to-install-tiny-tiny-rss-on-centos-7)一步步操作配置；其中有几点变更：

1.Step 3: Centos7.6的yum库默认的php5.4低于ttrss所需的5.6，对于php安装部分调整如下：
`rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm`
`sudo yum install php70w php70w-common php70w-gd php70w-mbstring php70w-process php70w-pgsql php70w-xml php70w-cli php70w-intl -y`
`sudo systemctl restart httpd.service`

2.Step 5: 原文`Host name: locahost`拼写错误，修正`Host name: localhost`

### [**options_per_feed部分**](https://github.com/sergey-dryabzhinsky/options_per_feed)
1.git clone源镜像并移动到ttrss插件目录下
2.安装php-curl环境
`yum install curl`
`yum install php-curl`
3.重启apache/php-fpm

使用情况
进入TTRSS网页进行偏好设置打开插件
  直接订阅外网RSS，超时。
  订阅国内RSS并编辑修改为外网RSS，订阅源插件开启填写172.19.0.6:10809(docker网桥在host访问的地址)。可以正常订阅。

**Comment by HenryQW** [comment]
> 应该是docker image的环境没有配置完全
挺奇怪的，`HTTP_PROXY`是ttrss支持的环境变量之一，而 options_per_feed 的目的则是不同feed不同代理配置。

不过鉴于首次订阅的麻烦程度来看，还不如直接设置全局代理了

**Comment by LOTehan** [comment]
> 不过鉴于首次订阅的麻烦程度来看，还不如直接设置全局代理了

我的外网订阅源不是特别多，国内和期刊会多一些；如果能用options_per_feed为个别的订阅源设置代理会更合理一些。

暂时我先用了全局代理。谢谢~
