### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by bladrome** [HenryQW/Awesome-TTRSS#178]
- ## _What_ is the issue?

When I login or even refresh, exception occurred.
`TypeError: iterator is not a function
Stack trace:
each@http://IP:181/lib/prototype.js?1598298494:861:12
unhook@moz-extension://ba788c5f-580c-405b-9849-b3b8a8d14b5f/userscripts/%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4(%E6%94%B9).user.js?id=3313d6df-236f-4324-93ab-7feb824d36b7:664:20
unhook_f@moz-extension://ba788c5f-580c-405b-9849-b3b8a8d14b5f/userscripts/%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4(%E6%94%B9).user.js?id=3313d6df-236f-4324-93ab-7feb824d36b7:659:16

`

- ## _What_ is your OS and its version?
Ubuntu 18.04.5 LTS

- ## _What_ is your installation method?

docker-compose

- ## _Are_ there any error logs?

- ## _How_ can the issue be replicated?

- ## Other Comments

**Comment by HenryQW** [comment]
To me the logs looks like your installed some weird Firefox extensions. Try disabling all extensions and see if it still occurs.

**Comment by bladrome** [comment]
IT WORKS, THANK YOU VERY MUCH. (It's a NOT related issue. VERY KIND OF YOU)
