### ISSUE TITLE
Please add support for SESSION_SKIP_UA_CHECKS option

### ISSUE THREAD

**Issue by ceasley** [HenryQW/Awesome-TTRSS#182]
- ## _What_ is the issue?

I log into TinyTinyRSS on many devices, and several times a day I'm forced to re-login due to "UA Change detected".

- ## _What_ is your OS and its version?

All OS's

- ## _What_ is your installation method?

Docker

- ### Docker

  - Did you build your own dockerfile (paste it here if possible)?
Nope

- ## _Are_ there any error logs?
No

- ## _How_ can the issue be replicated?

Log into the web interface on several devices via different browsers (Chrome and Edge, in my case).  You will occasionally be forced to re-login after a while due to a user agent change.  This was corrected using the official TinyTinyRSS install by adding the following to the config.php:

define(SESSION_SKIP_UA_CHECKS,1)

- ## Other Comments

**Comment by HenryQW** [comment]
What's the source?
