### ISSUE TITLE
postgres 12至13大版本更新数据迁移

### ISSUE THREAD

**Issue by hackenfu** [HenryQW/Awesome-TTRSS#186]
watchover自动更新后始终在重启postgres
虽然跟作者无关，但想确定下是什么问题

**Comment by Derekmini** [comment]
关注一下该issue，我也遇到了同样问题。谢谢解答！

**Comment by HenryQW** [comment]
有日志吗

**Comment by HenryQW** [comment]
pg 大版本更新了。。。好坑

短期解决方案：pg镜像换为`image: postgres:12-alpine`。
长期解决方案：用12导出数据，然后升级为13导入数据。见[文档](https://ttrss.henry.wang/zh/#postgres-%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB)

**Comment by Derekmini** [comment]
> pg 大版本更新了。。。好坑
> 
> 短期解决方案：pg镜像换为`image: postgres:12-alpine`。
> 长期解决方案：用12导出数据，然后升级为13导入数据。见[文档](https://ttrss.henry.wang/zh/#postgres-%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB)，[pg文档](https://www.postgresql.org/docs/12/pgupgrade.html)

已经按照“长期解决方案”恢复了ttrss，非常感谢！！！现在遇到一个**注销问题**：

### 问题描述
ttrss上有两个账号，当我注销时，会跳转到网址：``域名/public.php``，网页页面提示``{"error":{"code":13,"message":null}}``。

尝试访问原网址(不加public.php)，发现仍未注销。

### 尝试方法
尝试删除``~/postgres/data``文件夹，并重新导入``export.sql``，仍出现上述描述内容，无法注销。

请问，这是个别问题还是其他人也遇到了同样问题？需要提供什么内容来判断问题呢？

**Comment by hackenfu** [comment]
> > pg 大版本更新了。。。好坑
> > 短期解决方案：pg镜像换为`image: postgres:12-alpine`。
> > 长期解决方案：用12导出数据，然后升级为13导入数据。见[文档](https://ttrss.henry.wang/zh/#postgres-%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB)，[pg文档](https://www.postgresql.org/docs/12/pgupgrade.html)
> 
> 已经按照“长期解决方案”恢复了ttrss，非常感谢！！！现在遇到一个**注销问题**：
> 
> ### 问题描述
> ttrss上有两个账号，当我注销时，会跳转到网址：`域名/public.php`，网页页面提示`{"error":{"code":13,"message":null}}`。
> 
> 尝试访问原网址(不加public.php)，发现仍未注销。
> 
> ### 尝试方法
> 尝试删除`~/postgres/data`文件夹，并重新导入`export.sql`，仍出现上述描述内容，无法注销。
> 
> 请问，这是个别问题还是其他人也遇到了同样问题？需要提供什么内容来判断问题呢？

请问你新版postgres无限期自动重启，是怎么导入的呢？
似乎作者的办法没有解决这个重启的问题啊

**Comment by Derekmini** [comment]
先按照作者短期解决方案正常启动，即可导出数据，再按照长期解决方案导入数据即可。

**Comment by hackenfu** [comment]
走了点弯路，解决了。我还是写一下具体步骤吧（环境：群晖docker）
1、把image: postgres:alpine改成image: postgres:12-alpine后先确保启动成功
2、停止所有服务的容器
3、备份数据卷，就是你设置:/var/lib/postgresql/data前面的那个路径的文件夹
4、启动所有服务的容器，然后docker exec postgres pg_dumpall -c -U 数据库用户名 > export.sql等到结束为止，会发现第三步的那个文件夹的上一级文件夹出现了一个export.sql文件，说明导出成功
5、这里切记要将:/var/lib/postgresql/data前面的那个路径的文件夹里内容清空，但空文件夹要保存
6、再将image: postgres:12-alpine改回image: postgres:alpine，docker-compose up -d，这时候加载新的版本postgres了
7、cat export.sql | docker exec -i postgres psql -U 数据库用户名等到结束，会发现第五步的空文件夹里多了很多文件，说明导入成功了
8、如果正常工作，可以删除第二步的备份，和第四步的export.sql文件

**Comment by HenryQW** [comment]
> > pg 大版本更新了。。。好坑
> > 短期解决方案：pg镜像换为`image: postgres:12-alpine`。
> > 长期解决方案：用12导出数据，然后升级为13导入数据。见[文档](https://ttrss.henry.wang/zh/#postgres-%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB)，[pg文档](https://www.postgresql.org/docs/12/pgupgrade.html)
> 
> 已经按照“长期解决方案”恢复了ttrss，非常感谢！！！现在遇到一个**注销问题**：
> 
> ### 问题描述
> ttrss上有两个账号，当我注销时，会跳转到网址：`域名/public.php`，网页页面提示`{"error":{"code":13,"message":null}}`。
> 
> 尝试访问原网址(不加public.php)，发现仍未注销。
> 
> ### 尝试方法
> 尝试删除`~/postgres/data`文件夹，并重新导入`export.sql`，仍出现上述描述内容，无法注销。
> 
> 请问，这是个别问题还是其他人也遇到了同样问题？需要提供什么内容来判断问题呢？

我也是用的pg13，注销后会直接跳转到 index.php，没有报错

**Comment by madordie** [comment]
> > > pg 大版本更新了。。。好坑
> > > 短期解决方案：pg镜像换为`image: postgres:12-alpine`。
> > > 长期解决方案：用12导出数据，然后升级为13导入数据。见[文档](https://ttrss.henry.wang/zh/#postgres-%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB)，[pg文档](https://www.postgresql.org/docs/12/pgupgrade.html)
> > 
> > 
> > 已经按照“长期解决方案”恢复了ttrss，非常感谢！！！现在遇到一个**注销问题**：
> > ### 问题描述
> > ttrss上有两个账号，当我注销时，会跳转到网址：`域名/public.php`，网页页面提示`{"error":{"code":13,"message":null}}`。
> > 尝试访问原网址(不加public.php)，发现仍未注销。
> > ### 尝试方法
> > 尝试删除`~/postgres/data`文件夹，并重新导入`export.sql`，仍出现上述描述内容，无法注销。
> > 请问，这是个别问题还是其他人也遇到了同样问题？需要提供什么内容来判断问题呢？
> 
> 我也是用的pg13，注销后会直接跳转到 index.php，没有报错

终于弄好了 先感谢各位提前踩坑.

说一下注销的问题我试了一下 升级到pg13之后 注销依旧失效, 所以我新开了个[issues](190)
