### ISSUE TITLE
[BUG]一进入TT-RSS 就自动爆错TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by ZhuningS** [HenryQW/Awesome-TTRSS#191]
**Bug 描述**
简洁明了地描述这个 bug。
一进入TT-RSS 就自动爆错
**你谷歌/百度了吗？**
已经百度

**部署方法**
docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]
latest,
**部署环境**
 - 操作系统: [如 Ubuntu 18.04]
 - 浏览器: [如 chrome, safari]
群晖nas 6.20

**复现步骤**
复现该 bug 的详细步骤
1. 打开 http://192.168.1.103:1281/
2. 输入登录密码
3. 进入界面
4. 自动出现报错（即使刚刚部署完）：
TypeError: Cannot read property 'forEach' of undefined
    at Object.obj.matchApp (<anonymous>:1959:24)
    at Object.obj.runAppList (<anonymous>:1946:33)
    at HTMLDocument.<anonymous> (<anonymous>:1936:25)
    at l (<anonymous>:1064:29375)
    at c (<anonymous>:1064:29677)

**预期结果**
正常运行不报错

**截屏**
![image](https://user-images.githubusercontent.com/38108376/94364804-8e0f6980-00fe-11eb-82d6-200ea21ba5a5.png)

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。
PDOException: SQLSTATE[08006] [7] FATAL:  database "ttrss" does not exist in /co                                                                                                                                                             nfigure-db.php:127
Stack trace:
#0 /configure-db.php(127): PDO->__construct('pgsql:host=data...', 'postgres', 't                                                                                                                                                             trss')
#1 /configure-db.php(135): dbexist(Array)
#2 /configure-db.php(34): dbcheckdb(Array)
#3 {main}Database not found, creating.
Database table not found, applying schema...
[25-Sep-2020 15:03:58] NOTICE: fpm is running, pid 47
[25-Sep-2020 15:03:58] NOTICE: ready to handle connections

**其他**
在多处都出现这个错误，不管腾讯云还是群晖。每次一进入自动报错（即使刚刚部署完）。

**Comment by HenryQW** [comment]
```
PDOException: SQLSTATE[08006] [7] FATAL: database "ttrss" does not exist in
```
这日志还不明显吗，数据库不存在。
可能相关#186
