### ISSUE TITLE
[BUG] Schema version is wrong, please upgrade the database.

### ISSUE THREAD

**Issue by wellsgz** [HenryQW/Awesome-TTRSS#192]
**Describe the bug**
ttrss docker report error "Schema version is wrong, please upgrade the database."

**Have you googled?**
According to the search result, it seems to be version mismatch, guess the ttrss code need to by synced

**Deployment method**
 - Docker or docker-compose
 - Version of the image used: latest

**Deployment environment**
 - OS: Fedora
 - Browser: [e.g. chrome, safari]

**To Reproduce**
docker-compose pull
docker-compose up

**Expected behavior**
Start normally 

**Screenshots**
[n/a]

**Error logs**
ttrss                | Schema version is wrong, please upgrade the database.

**Additional context**

**Comment by HenryQW** [comment]
Maybe you should visit your homepage and login, where you will see the instructions for upgrading your schema version.
