### ISSUE TITLE
Where is the ttrss folder?

### ISSUE THREAD

**Issue by balajeek** [HenryQW/Awesome-TTRSS#193]
I just used the docker-compose install method and got the ttrss working.  now I want to download a theme and noticed under my docker root folder there is no such folder for ttrss, where is it installed?

**Comment by balajeek** [comment]
anyone ?

**Comment by HenryQW** [comment]
It's a self-contained docker container, so if you want to do that, [let me google that for you](https://lmgtfy.app/?q=docker+map+folder+to+container).
