### ISSUE TITLE
FeedMei Theme + Plugins for Tiny Tiny RSS

### ISSUE THREAD

**Issue by balajeek** [HenryQW/Awesome-TTRSS#194]
is it possible to add FeedMei Theme + Plugins for Tiny Tiny RSS with this docker image.

https://tt-rss.org/wiki/Themes

**Comment by HenryQW** [comment]
You can map the theme folder to do so.

**Comment by balajeek** [comment]
Sorry to bother you, I am not sure how to do that I just the beginner on linux and docker terms.  I googled and couldn’t find any to help me.
Would you mind give me the line of code I need to put in my docker-compose as an example so I could give it a try.  Thank you so much for your fast response.
Stay safe.

**Comment by HenryQW** [comment]
In the section for ttrss, add something like:
```
volumes:
	- /path/to/theme:/var/www/themes.local
```

This maps the folder `/path/to/theme` on your host machine into ttrss container, where ttrss reads the list of themes `/var/www/themes.local`

**Comment by balajeek** [comment]
Thank you so much. it worked.
