### ISSUE TITLE
[BUG]关于自建TTRSS不能订阅自建huginn、rsshub链接的问题

### ISSUE THREAD

**Issue by aoxue651** [HenryQW/Awesome-TTRSS#195]
你好，
    我在阿里云上用docker自建了TTRSS、huginn、RSSHub。新手不会调试，都是按照默认的安装的。
    现在出现个问题，TTRSS不能订阅自建的huginn和RSSHub生成的RSS，或是提示“无法从指定的网址下载:HTTP/1.1 404 Not Found”，又或者提示"无法从指定的网址下载:; 7 Failed to connect to 47.114.154.170 port 80: Connection refused"。
在别人提供的TTRSS网站（"https://rss.ioiox.com/"）上确是能订阅，所以请问下是不是我哪里设置有问题。
    阿里云的安全组端口也打开了。
![image](https://user-images.githubusercontent.com/71183929/95287049-8dfa3100-0897-11eb-8b4c-2f368fc83760.png)
![image](https://user-images.githubusercontent.com/71183929/95287769-63a97300-0899-11eb-977b-2b0159ed7bac.png)
临时服务器

**Comment by HenryQW** [comment]
见#184

**Comment by aoxue651** [comment]
> [[#184](https://github.com/HenryQW/Awesome-TTRSS/issues/184)

能告诉我个解决方法吗？有些专业词看不懂，为了定制筛选rss才接触这个。
我现在在申请个域名（目前在实名审查），再去绑定ssl，再用 Nginx 反向代理，不知道能不能解决问题。

**Comment by HenryQW** [comment]
出于安全考量，ttrss 只支持 80，443 端口的源，其他端口如3000，181都会被拒绝。等你域名下来之后直接用子域名代替IP:端口，就可以解决这个问题。

**Comment by allanpk716** [comment]
> 出于安全考量，ttrss 只支持 80，443 端口的源，其他端口如3000，181都会被拒绝。等你域名下来之后直接用子域名代替IP:端口，就可以解决这个问题。

自己在家建的 rsshub，电信没法给出 80 和 443 端口，这种情况，可以留一个接口给自定义的端口来订阅吗?

**Comment by HenryQW** [comment]
已经增加了绕过 ttrss 上游禁止端口的改动,见 #207

**Comment by CXwudi** [comment]
> 已经增加了绕过 ttrss 上游禁止端口的改动,见 #207

请问这个修复现在还working吗,  
今天我试了一下在本地用docker部署rsshub+awesome ttrss, 但无法连结到非80,433的端口
![bug](https://user-images.githubusercontent.com/17377423/114314103-28893600-9aae-11eb-9d99-dc1f585813b9.png)
rsshub那边没有问题
![浏览器端](https://user-images.githubusercontent.com/17377423/114314163-64bc9680-9aae-11eb-9711-350da6c30ce8.png)
同时我还发现, 即使设置了`ALLOW_PORTS`,docker那边依旧显示只有`80,433`
![ttrss-config](https://user-images.githubusercontent.com/17377423/114314105-2921cc80-9aae-11eb-89ca-06f28eaee1fd.png)
不知道我是否还有别的设置没弄对, 希望大佬能点明一下
