### ISSUE TITLE
[BUG]无法添加本地服务器产生的rss源

### ISSUE THREAD

**Issue by terryxuwen** [HenryQW/Awesome-TTRSS#196]
**Describe the bug**
用docker安装了ttrss，而且使用--e HTTPS_PROXY="http://172.19.0.1:6060" -e no_proxy="127.0.0.1,172.19.0.1,172.19.0.2,172.19.0.3,172.19.0.4,172.19.0.5,192.168.1.130 " 等方式让ttrss运行在代理服务器后面。添加各种源和使用都没问题,都属于使用代理的模式。唯一的问题就是无法添加本地服务器产生的rss源。比如本机ip是 192.168.1.130，本机除了运行ttrss外，还用docker安装了一个huginn，制作了一个rss源，比如 http://192.168.1.130:5002/xxx/xxx.xml,当把这个地址添加到ttrss里面的时候，提示错误 “28 Operation timed out after 45001 milliseconds with 0 bytes received”。我用docker exec进入这个镜像，用curl 链接http://192.168.1.130:5002/xxx/xxx.xml，是能够下载到内容的。不知道是怎么回事。同时，把192.168.1.130换成域名也一样的结果。用inoreader添加这个源也是没问题的（当然地址要换成域名。）

**Have you googled?**
已经google搜索，没找到答案

**Deployment method**
 -docker 安装
 - Version of the image used [e.g. latest, nightly, 19.8]
最新的镜像版本
**Deployment environment**
 - OS: [e.g. Ubuntu 18.04]
CentOS7
 - Browser: [e.g. chrome, safari]
chrome
**To Reproduce**
1.docker安装ttrss，运行在代理服务器下
2. docker安装huginn，与ttrss在同一台机器上
3. 在ttrss里面添加huginn产生的rss源
4. 看到错误
![ttrss问题2](https://user-images.githubusercontent.com/20849822/95658084-a645a680-0b4a-11eb-84b4-a3514ee60b36.png)

**Expected behavior**

**Screenshots**

**Error logs**
When the error occurs, execute `docker logs ttrss --tail 100` to obtain the error logs and paste **the relevant logs** here.

**Additional context**

**Comment by HenryQW** [comment]
见#184

**Comment by terryxuwen** [comment]
谢谢，换了你的dev版本，可以加各种端口的源了。但是，还是不能加局域网的地址，比如 192.168.1.130:5002/xxx  或 172.19.0.1就不行，只有加上域名（路由端口转发到本机）才可以，这是什么原因啊？感觉这ttrss看起来挺好，用起来一大堆问题，玩了几十年的软件，没见过这么啰嗦的软件，连端口都禁，也算奇葩了。

**Comment by HenryQW** [comment]
学习一下docker网络吧，每个容器相当于一个虚拟机，局域网IP是ping不通的
