### ISSUE TITLE
Add Docker Secrets support

### ISSUE THREAD

**Issue by abelfodil** [HenryQW/Awesome-TTRSS#197]
**Is your feature request related to a problem? Please describe.**

Docker Secrets provides secrets to containers through files. TTRSS' Docker Image only reads from environment variables directly, thus lacking Docker Secrets support.

**Describe the solution you'd like**

Take on the documentation's [suggestion](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images) and add support for `DB_USER_FILE` and `DB_PASS_FILE` to env vars and read from them like the Wordpress image [does](https://github.com/docker-library/wordpress/blob/b1127748deb2db34e9b1306489e24eb49720454f/php7.2/apache/docker-entrypoint.sh).

**Comment by HenryQW** [comment]
It's not a critical feature and I'm extremely busy these days. Feel free to PR or I will revisit in probably a few months.
