### ISSUE TITLE
Confine docker containers to internal network

### ISSUE THREAD

**Issue by sphinxc0re** [HenryQW/Awesome-TTRSS#200]
`docker-compose` has a networking feature where you are able to create virtual networks:

```yml
networks:
  external_network:
  internal_network:
    internal: true
```

This would make it possible to confine every sidecar-service (e.g. mercury + other parsing stuff) to exist in an internal network while the actual ttrss instance could exist in both the internal and external network. A great side-effect of this would be that the user wouldn't have to change the postgres password. In fact, I believe this would make editing the `docker-compose.yml` completely obsolete (I could be wrong though 😉).

A great example of this in action would be the `docker-compose.yml` of mastodon:
https://github.com/tootsuite/mastodon/blob/master/docker-compose.yml#L112
The file in general is a really good example of a well-defined `docker-compose.yml`.

**Comment by HenryQW** [comment]
Definitely useful, will you be interested in opening a PR on this? I'm extremely occupied, will have to revisit this in a few months time.

**Comment by sphinxc0re** [comment]
I'll be unable to work on this for a few months as well 😅 but I'm glad you feel the same way.
