### ISSUE TITLE
[BUG]使用compose 安装的 缺少插件

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#208]
使用的compose 安装
但是没有Mercury Fulltext 等插件
![QQ截图20201023093251](https://user-images.githubusercontent.com/4506307/96946408-dca00000-1512-11eb-9903-c982dedc65c7.png)
奇怪的是Fever 却有

**Comment by HenryQW** [comment]
你确定用的是正确的镜像？

**Comment by ptsa** [comment]
![QQ截图20201023223911](https://user-images.githubusercontent.com/4506307/97017511-984b4900-1580-11eb-9c2a-45c89e132f9c.png)
![QQ截图20201023223940](https://user-images.githubusercontent.com/4506307/97017557-a731fb80-1580-11eb-80b7-765f96b0748d.png)
没有错的

**Comment by HenryQW** [comment]
插件都在 `plugins.local`

**Comment by ptsa** [comment]
我挂载了plugins.local，这样以后镜像下载的文件全部清空，只有我放到镜像的文件，能不能你下载的插件全部放plugins文件，这样plugins_local文件夹是空的 可以让我们挂载安装第三方差插件

目前我是这样解决了
    volumes:
       - /home/ttrss_plugins/af_enclosure_fix_type/:/var/www/plugins.local/af_enclosure_fix_type/
       - /home/ttrss_plugins/api_resize_media/:/var/www/plugins.local/api_resize_media/
       - /home/ttrss_plugins/hl_legacy/:/var/www/plugins.local/hl_legacy/

**Comment by HenryQW** [comment]
相关讨论见 https://github.com/HenryQW/Awesome-TTRSS/pull/172#issuecomment-677913322
