### ISSUE TITLE
[BUG]ALLOW_PORTS: 参数问题，重启失效！

### ISSUE THREAD

**Issue by snakwu** [HenryQW/Awesome-TTRSS#209]
**Bug 描述**
ALLOW_PORTS: 当我设置好这个端口参数后，再docker-compose up -d执行，这时可以成功订阅所有非80和443的源，然后重启主机后端口失效，这些源都报http错误，然后再执行docker-compose up -d，还是一样无效，一定要修改一下docker-compose.yml里面修改一下端口，再docker-compose up -d，就又可成功更新非80和443的源，直到下一次重启，又重复出现这个问题！

**你谷歌/百度了吗？**
没有
**部署方法**
 - Docker 或 docker-compose
 - docker-compose

**部署环境**
 - Ubuntu 18.04

**复现步骤**
复现该 bug 的详细步骤
1.修改好docker-compose.yml添加ALLOW_PORTS
2.docker-compose up -d，可成功订阅非80和443的源
3.重启机器，这个ALLOW_PORTS参数失效，不能更新非80和443的源
4.再修改docker-compose.yml，然后docker-compose up -d，又可成功更新非80和443的源
5.到下一次重启，又失效，又要重复上步步骤！

**预期结果**
希望可以修复这个问题！

**Comment by HenryQW** [comment]
https://github.com/HenryQW/Awesome-TTRSS/issues/184#issuecomment-713906485

**Comment by snakwu** [comment]
> [#184 (comment)](https://github.com/HenryQW/Awesome-TTRSS/issues/184#issuecomment-713906485)

compose中的command已经移除，用的是你的最新的docker-compose.yml，已经是去除了！

**Comment by snakwu** [comment]
> [#184 (comment)](https://github.com/HenryQW/Awesome-TTRSS/issues/184#issuecomment-713906485)

version: "3"
services:
  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=******* # please change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    restart: always

  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 1811:80
    environment:
      - SELF_URL_PATH=https://xxxxxxxxxxx/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=******* # please change the password
      - ENABLE_PLUGINS=auth_internal,remove_iframe_sandbox,api_feedreader,api_newsplus # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
      - ALLOW_PORTS=1200
      - FEED_LOG_QUIET=true
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    restart: always

  utility.watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
    restart: always

贴上我的配置！！！！！！

**Comment by HenryQW** [comment]
我研究一下

**Comment by snakwu** [comment]
> 我研究一下

好的，谢谢，现在我只能ubuntu重启过后，就要去修改一下docker-compose.yml文件的ALLOW_PORTS乱改一个，然后docker-compose up -d，再把它改回1200，再docker-compose up -d一下就正常了！

**Comment by HenryQW** [comment]
应该解决了

**Comment by snakwu** [comment]
> 应该解决了

好的，谢谢，我试试，有问题再反馈

**Comment by HenryQW** [comment]
等CI建完新镜像后需要拉取最新镜像，估计还要5分钟

**Comment by snakwu** [comment]
> 等CI建完新镜像后需要拉取最新镜像，估计还要5分钟
> 
> https://github.com/HenryQW/Awesome-TTRSS/actions/runs/327571670

ok！问题已解决，谢谢！

**Comment by EliteOtaku** [comment]
> > [#184 (comment)](https://github.com/HenryQW/Awesome-TTRSS/issues/184#issuecomment-713906485)
> 
> version: "3" services: database.postgres: image: postgres:13-alpine container_name: postgres environment: - POSTGRES_PASSWORD=******* # please change the password volumes: - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host restart: always
> 
> service.rss: image: wangqiru/ttrss:latest container_name: ttrss ports: - 1811:80 environment: - SELF_URL_PATH=https://xxxxxxxxxxx/ # please change to your own domain - DB_HOST=database.postgres - DB_PORT=5432 - DB_NAME=ttrss - DB_USER=postgres - DB_PASS=******* # please change the password - ENABLE_PLUGINS=auth_internal,remove_iframe_sandbox,api_feedreader,api_newsplus # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins - ALLOW_PORTS=1200 - FEED_LOG_QUIET=true stdin_open: true tty: true restart: always
> 
> service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page image: wangqiru/mercury-parser-api:latest container_name: mercury expose: - 3000 restart: always
> 
> service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page image: wangqiru/opencc-api-server:latest container_name: opencc environment: - NODE_ENV=production expose: - 3000 restart: always
> 
> utility.watchtower: container_name: watchtower image: containrrr/watchtower:latest volumes: - /var/run/docker.sock:/var/run/docker.sock environment: - WATCHTOWER_CLEANUP=true - WATCHTOWER_POLL_INTERVAL=86400 restart: always
> 
> 贴上我的配置！！！！！！

你好，可以分享你的yml文件吗？我也遇到这样的问题了，我是在群晖docker下的，这两天部署了ttrss后，发现不能订阅本地rsshub产生的feed。非常感谢。

**Comment by EliteOtaku** [comment]
https://juejin.cn/post/7040788539939749925 目前我也是用这个方法暂时搞定，希望有一劳永逸的解决方案啊

**Comment by EliteOtaku** [comment]
https://www.cnblogs.com/alcc/p/13796031.html  按这个文章搞定了443，但是又出来新问题了
无法从指定的网址下载:Requested URL failed extended validation.

**Comment by HenryQW** [comment]
跟着文档来，rsshub端口是多少，allow_ports就加什么。

**Comment by EliteOtaku** [comment]
> 跟着文档来，rsshub端口是多少，allow_ports就加什么。

嗯，我今天再试一下，因为我不是IT专业范围的，群晖这些图形界面我还会搞一下，但遇到linux命令就抓瞎了，基本只会依葫芦画瓢。

**Comment by EliteOtaku** [comment]
另外，官网的那个yaml文件还没加入allow_ports这个啊，希望能更新一下，免得后来的小白踩坑，多谢啦

**Comment by EliteOtaku** [comment]
目前看官网的文档执行，我只添加了-ALLOW_PORTS=1200,3000，但执行一直出错，因为我不懂unix这些，所以无法理解这个出错是怎么回事
![image](https://user-images.githubusercontent.com/29235152/191646568-bb8fbdc9-8558-418b-8371-6e007943457a.png)

我的环境是在群晖docker下，通过putty ssh登录后弄的，这是我可以理解模仿的。
后来出现443错误后，我在另外一个博客看了，
https://www.cnblogs.com/alcc/p/13796031.html
我昨晚按这个执行后，就一直报超时出错了，怀疑我是不是无意中搞崩了什么东西。能否麻烦您帮忙查看一下是哪里出错了？ @HenryQW 非常感谢您的指导。

**Comment by EliteOtaku** [comment]
呃，去后台登录了下，发现居然已经正常运行了，测试后发现还是不能订阅本地rsshub，比如我想订阅知乎日报，就会出错

比如我自己的https://xxx.dscloud.me:182，后台rsshub访问没问题，但是按rsshub的格式订阅https://xxx.dscloud.me:182/zhihu/daily，就会显示出错。
无法从指定的网址下载:Requested URL failed extended validation.

估计还要继续研究下才知道如何解决。

**Comment by EliteOtaku** [comment]
Requested URL failed extended validation.这个问题我还是无法解决，看了其他有2个issues也有这样的反馈，但我试过好几个源，都搞不定，能否麻烦您帮忙查看一下是怎么回事吗？谢谢了。 @HenryQW
