### ISSUE TITLE
[BUG]使用mysql报错Exception while creating PDO object:could not find driver

### ISSUE THREAD

**Issue by x1a0xv4n** [HenryQW/Awesome-TTRSS#211]
**部署方法**
 - docker-compose
 - 使用的镜像版本 latest

**部署环境**
 - 操作系统: centOS8
 - 浏览器: chrome

**错误日志**

`docker logs ttrss`
返回`Exception while creating PDO object:could not find driver`

查看[wangqiru/ttrss Dockerfile - Docker Hub](https://registry.hub.docker.com/r/wangqiru/ttrss/dockerfile)，猜测是没有安装`php7-pdo_mysql`拓展的问题

![Jietu20201027-145534@2x](https://user-images.githubusercontent.com/8591495/97267330-ef913800-1864-11eb-9a71-92e5f6ca24cf.jpg)

**Comment by CoolkHz** [comment]
我也是这个问题 请问是怎么解决的

**Comment by x1a0xv4n** [comment]
这个repo本身就是不提供mysql这个driver的，可以看一下[Awesome-TTRSS/initialize.php at master · HenryQW/Awesome-TTRSS](https://github.com/HenryQW/Awesome-TTRSS/blob/master/src/initialize.php)这个文件，最后用[dimitri/pgloader: Migrate to PostgreSQL in a single command!](https://github.com/dimitri/pgloader)把之前mysql里的数据转到pgsql了。

如果想用mysql，也可以看一下[toony/docker-ttrss: Tiny Tiny RSS feed reader as a docker image.](https://github.com/toony/docker-ttrss)这个repo，跑了一下没有问题。
