### ISSUE TITLE
TTRSS lost my feeds and theme settings after auto update

### ISSUE THREAD

**Issue by balajeek** [HenryQW/Awesome-TTRSS#214]
I use docker setup with watchtower for auto update images.
This morning I was using the ttrss and all was fine as usual then an hour later i see my ttrss looked like a fresh install with just one feed which is "Tiny Tiny RSS feed", lost my theme settings and all my feeds. whet to settings i see no feeds of mine.  Wanted to logout ttrss and couldn't find an option to logout though.

After digging, found watchtower found new update for ttrss and mercury and updated them 
Here is the watchtower log:

time="2020-11-02T15:29:59Z" level=info msg="Found new wangqiru/ttrss:latest image (sha256:9674358a9aaa19a247c96c56f62ade6fcac956944251c7afab12b97c52fc1e50)"

time="2020-11-02T15:30:17Z" level=info msg="Stopping /ttrss (9ca0f2ff4d85ff9eb7ef41f5432c6471e8d0ae0a17653603bfd879c4b737ffc6) with SIGTERM"

time="2020-11-02T15:30:23Z" level=info msg="Stopping /mercury (9a36c5562a70028f640392ff1d0d8c7d92fb5801fc28605fa480e41c5dd72649) with SIGTERM"

time="2020-11-02T15:30:24Z" level=info msg="Creating /mercury"
time="2020-11-02T15:30:25Z" level=info msg="Creating /ttrss"

time="2020-11-02T15:30:28Z" level=info msg="Removing image sha256:4ca879585e2f999e77294345bde592b2c682372af0f721ed1dda10a89260377b"

time="2020-11-02T16:30:14Z" level=info msg="Waiting for running update to be finished..."

time="2020-11-02T16:31:10Z" level=info msg="Starting Watchtower and scheduling first run: 2020-11-03 16:31:10 +0000 UTC m=+86401.591692151"

Here is the ttrss log:

[02-Nov-2020 16:33:55] NOTICE: fpm is running, pid 25
[02-Nov-2020 16:33:55] NOTICE: ready to handle connections
s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan: fatal: unable to exec .s6-svscan/crash: No such file or directory
[02-Nov-2020 16:36:35] NOTICE: fpm is running, pid 26
[02-Nov-2020 16:36:35] NOTICE: ready to handle connections

What do you think happen?  I tried re-run docker compose, restart my ubuntu but still the same.

**Comment by balajeek** [comment]
Also i logged into the postgres database and I see all the feed entries in the ttrss_feeds table. not sure what went wrong.

**Comment by HenryQW** [comment]
You need to use the issue template and post your compose file here, otherwise I will have to hack into your machine and try to locate an issue that, based on your description, is unlikely caused by this repo.

**Comment by balajeek** [comment]
Sorry, will do that.

**Comment by HenryQW** [comment]
Nevermind, I have hacked into your machine and located the issue.

Just kidding, https://github.com/HenryQW/Awesome-TTRSS/commit/ef8ede78b848f7f280813e35bc7a09bb005b51a2 should fix the problem for you. Just pull the latest image, everything should be fine.

**Comment by balajeek** [comment]
I did set it to latest, but still have same issue though, reverting back to nightly-2020-20-31 which works for me.

**Comment by HenryQW** [comment]
You need to pull the latest, re-up the docker-compose doesn't pull images.
