### ISSUE TITLE
[BUG] Assigning false to SINGLE_USER_MODE has no effect

### ISSUE THREAD

**Issue by v4rakh** [HenryQW/Awesome-TTRSS#215]
**Describe the bug**

Since `latest-2020-11-01` and up until now SINGLE_USER_MODE (false) has no effect. It will always be enabled.

When assigning `SINGLE_USER_MODE` to `false` as env var or manually when host binding the `config.php` with `define(SINGLE_USER_MODE, false)` results in single user mode being enabled and all accounts being exposed in the preferences users tab.

Version `latest-2020-10-31` is the last version which works and which I reverted back to for now.

**Deployment method**
 - docker-compose
 - latest

**Deployment environment**
 - OS: Arch Linux, but that's probably not really relevant here
 - Browser: every browser

**To Reproduce**
1. Set `SINGLE_USER_MODE` to `false`
2. Start docker-compose
3. See single user mode

**Expected behavior**
Single user mode is disabled or can be set properly via env variables or via host bound `config.php` (which worked before).

**Error logs**
No special logs, it's just single user mode.

**Comment by HenryQW** [comment]
Lucky you, I decided to tag images only a few days ago.

I will have to investigate into this issue. I didn't test that env in the last commit, guilty as charged.

**Comment by HenryQW** [comment]
I'm a terrible PHP coder, in fact, I have neither learned it (yeah, never) nor participated in any PHP project.

**Comment by v4rakh** [comment]
Thanks for fixing this so quickly. :+1:
