### ISSUE TITLE
[BUG] 最新镜像 错误

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#216]
**Bug 描述**
Error: The env HTTP_PROXY does not exist

**部署方法**
 - docker-compose
 - latest

**Comment by kkAtGithub** [comment]
同一个环境，同一个问题
我的log是：
Error: The env HTTP_PROXY does not exist
Could not open input file: /configure-db.php

**Comment by ptsa** [comment]
切换 wangqiru/ttrss:nightly-2020-11-03 零时过度，last 不知道什么时候回更新

**Comment by muztag** [comment]
#217

**Comment by marapavelka** [comment]
It works with latest nightly now. But I have two users and I can't figure out how to swich between them. There is no Logout button.

**Comment by November-raining** [comment]
> It works with latest nightly now. But I have two users and I can't figure out how to swich between them. There is no Logout button.

同上  近几版本没有注销按钮  回滚到nightly先

**Comment by HenryQW** [comment]
@marapavelka @November-raining the last commit ef8ede78b848f7f280813e35bc7a09bb005b51a2 should have fixed this issue #215.

@ptsa @kkAtGithub 最新latest镜像应该没有这个问题了

**Comment by ptsa** [comment]
已经可以了
