### ISSUE TITLE
[Feature]提供清理功能？

### ISSUE THREAD

**Issue by kahoch** [HenryQW/Awesome-TTRSS#218]
设置Purge articles older than 2 ，使用一段时间后VPS 15G的空间就爆了，查看发现/var/lib/docker/overlay2/ 占用了绝大多数空间，不知道是不是ttrss的bug，但这个情况对于非专业的coder来说还是非常棘手的，如果能提供简单的清理空间功能那就好了

**Comment by HenryQW** [comment]
ttrss自带清理功能啊，我近200个源跑了几年都没上过G，毕竟是纯文本数据。

**Comment by kahoch** [comment]
就是怀疑ttrss的自动清理有问题，设置purge 日期为2按道理不会有那么多空间占用的

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/98157346-21437800-1ed1-11eb-8581-1afda36529b3.png)

![image](https://user-images.githubusercontent.com/5896343/98157429-41733700-1ed1-11eb-8e5e-8fb4a1f05bc8.png)

![image](https://user-images.githubusercontent.com/5896343/98157657-8e570d80-1ed1-11eb-9470-a0227bddb7cf.png)

/var/lib/docker/overlay2/ 听起来是旧的docker镜像没有删除。

如果 `docker images` 返回很多旧镜像，可以通过 `docker rmi $(docker images -qf dangling=true)` 执行删除

**Comment by kahoch** [comment]
只有ttrss，mercury 和postgres这3个镜像....我再找找问题出在哪吧
