### ISSUE TITLE
mercury插件不能正常运行[BUG]

### ISSUE THREAD

**Issue by isinglever** [HenryQW/Awesome-TTRSS#221]
**Bug 描述**
简洁明了地描述这个 bug。
mrcury 插件不能全文输出，手动点击插件提示“unable to extract fulltext for this article‘   已经按照文档设置插件
**你谷歌/百度了吗？**
请善用搜索引擎。
搜索后之发现有issue讨论mercury 不能使用代理的问题。我使用的是美国的VPS,所以应该不是这个原因
**部署方法**
docker-compose（全部部署，并且全部处于运行状态）
`  STATUS              PORTS                  NAMES
d00ba39fa942        wangqiru/ttrss:latest                "sh /docker-entrypoi…"   13 hours ago        Up 13 hours         0.0.0.0:181->80/tcp    ttrss

4b39c36d542a        wangqiru/opencc-api-server:latest    "docker-entrypoint.s…"   26 hours ago        Up 13 hours                                opencc

5b7be65bb6fe        wangqiru/mercury-parser-api:latest   "dumb-init -- npm ru…"   26 hours ago        Up 13 hours                                mercury

c84233c32a2f        postgres:13-alpine                   "docker-entrypoint.s…"   26 hours ago        Up 13 hours                                postgres`
 - 使用的镜像版本 [如 latest, nightly, 19.8]
latest
**部署环境**
 - 操作系统: ubuntu 20.04.1
 - 浏览器: ? 使用SSH登陆的，网页用的Firefox

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
全文输出

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

`[04:19:03/8053] Lock: update_daemon-8050.lock
[04:19:03/8053] Waiting before update (0)
[04:19:03/8053] Scheduled 0 feeds to update...
[04:19:03/8053] Sending digests, batch of max 15 users, headline limit = 1000
[04:19:03/8053] All done.
[04:19:03/8053] Expired cache/export: removed 0 files.
[04:19:03/8053] Expired cache/feeds: removed 0 files.
[04:19:03/8053] Expired cache/images: removed 0 files.
[04:19:03/8053] Expired cache/upload: removed 0 files.
没有发现错误日志`

**其他**
任何有助于 bug 修复的信息。这个是mercury logs
`root@ising:~# docker logs mercury --tail 10 -f
GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F04%2F02%2Fbusiness-this-week 200 67 - 5015.860 ms

GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F03%2F26%2Fpolitics-this-week 200 67 - 5020.848 ms

GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F03%2F26%2Fbusiness-this-week 200 67 - 5021.280 ms

GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F03%2F26%2Fkals-cartoon 200 67 - 5021.801 ms

GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F03%2F21%2Fpolitics-this-week 200 67 - 5021.568 ms

GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F03%2F21%2Fbusiness-this-week 200 67 - 5013.749 ms

GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F03%2F21%2Fkals-cartoon 200 67 - 5017.229 ms

GET /parser?url=https%3A%2F%2Fwww.economist.com%2Fthe-world-this-week%2F2020%2F03%2F14%2Fpolitics-this-week 200 67 - 5014.586 ms

GET /parser?url=https%3A%2F%2Fwww.theguardian.com%2Faustralia-news%2F2020%2Fnov%2F04%2Faustralia-calls-for-china-to-play-by-the-rules-after-reports-of-multibillion-dollar-trade-bans 200 69 - 5044.085 ms

GET /parser?url=https%3A%2F%2Fwww.theguardian.com%2Fbusiness%2F2020%2Fnov%2F03%2Fnew-lockdown-same-economic-victims-young-low-paid-workers 200 69 - 5027.641 ms
`

**Comment by HenryQW** [comment]
根据日志你的服务器每次获取文章都要50秒，导致超时。

**Comment by kkren** [comment]
这个issue的原因可能是service_only这个network被设置为internal了，设置为internal会导致容器内部无法访问外网。
[reference](https://docs.docker.com/compose/compose-file/compose-file-v2/#internal)

**Comment by isinglever** [comment]
感謝，我試試
