### ISSUE TITLE
Steps: use user-defined dictionary in docker opencc

### ISSUE THREAD

**Issue by linzack** [HenryQW/Awesome-TTRSS#227]
**Is your feature request related to a problem? Please describe.**
I have some modified opencc dictionary like 'STPhrases.txt', and it's interesting to apply it in ttrss, the awesome rss reader XD.

**Describe the solution you'd like**
The goal is to have a folder with dictionary text file outside the docker container, 
and when dictionary text is changed, user can re-generate the dictionary ocd file in opencc docker container,
so the translation later can apply these changes.

**Additional context**
Here are some steps to do this..
1. opencc master branch have issue in ocd2 format, currently choose version 1.0.6 to avoid it.
2. put OpenCC_1.0.6 folder under OpenCC.henry.wang, 
   the dictionary text in OpenCC_1.0.6/data/dictionary will be the first version to be used in ttrss.
   edit `package.json`, tell npm to use local version opencc

```
  "dependencies": {
    "express": "4.17.1",
    "opencc": "file:./OpenCC_1.0.6"
  }
```
3. for some site the content is already translated, if you are not satisfied by the result, you can ask opencc to translate twice.
    for example first call tw2s, then call s2twp. edit `route.js` to reflect this behavior.
```
  try {
    /* original
    const opencc = new OpenCC(`${type}.json`);

    const title = opencc.convertSync(reconvert(req.body.title || ""));
    const content = opencc.convertSync(reconvert(req.body.content || "")); */

    // modified
    // 1. call tw2s
    const opencc_tw2s = new OpenCC(`tw2s.json`);
    const title_tw2s   = opencc_tw2s.convertSync(reconvert(req.body.title || ""));
    const content_tw2s = opencc_tw2s.convertSync(reconvert(req.body.content || ""));

    // 2. call s2twp by ttrss
    const opencc = new OpenCC(`${type}.json`);
    const title   = opencc.convertSync(title_tw2s);
    const content = opencc.convertSync(content_tw2s);
```
4. sometimes the content in feed is too large, opencc container have log like 'PayloadTooLargeError: request entity too large',
    and stop translating the content.. it seems the following trick have this issue solved. edit `app.js`
```
var express = require("express");
var bodyParser = require('body-parser') // add
var router = require("./route");

var app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: false }));

// modified
app.use(bodyParser.json({limit: '30mb', extended: true}))
app.use(bodyParser.urlencoded({limit: '30mb', extended: true}))
```
5. edit `Dockerfile` in OpenCC.henry.wang, tell 'docker build' to move OpenCC_1.0.6 folder under node_modules after compilation in name 'opencc', and don't remove build tools, python is a must need when re-generate ocd file.
```
FROM node:14-alpine

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
COPY ["OpenCC_1.0.6", "./OpenCC_1.0.6"]

RUN  apk update && \
    apk add --no-cache --virtual build-pkg build-base python2 && \
    npm install --production --silent && \
    rm node_modules/opencc && \
    mv OpenCC_1.0.6 node_modules/opencc && \
    mv node_modules ../
COPY . .

EXPOSE 3000

CMD npm start
```
6. docker build script
```
rm package-lock.json && rm -rf node_modules && rm -rf ~/.node-gyp
npm install --unsafe-perm --production
docker-compose build
```
7. edit `docker-compose.yml` in Awesome-TTRSS, bind read-only external opencc dictionary text folder with internal
```
  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
#    image: wangqiru/opencc-api-server:latest
    image: test_opencc
    container_name: opencc
    environment:
      - NODE_ENV=production
    volumes:
      - /path/to/external/dictionary/:/usr/src/node_modules/opencc/data/dictionary/:ro
    networks:
      - public_access # for rebuild download from nodejs.org 
      - service_only
    restart: always
```
8. run `docker-compose up -d`, run `docker ps` to get opencc container_id, enter opencc docker by  `docker exec -it {container_id} /bin/sh`, navigate to opencc folder under node_modules, check ocd file date, should be updated after re-generate
```
/usr/src/app # cd ../node_modules/opencc/
/usr/src/node_modules/opencc # ls -la build/Release/
total 5384
drwxr-xr-x    1 root     root          1020 Nov 23 23:23 .
drwxr-xr-x    1 root     root           180 Nov 23 23:23 ..
-rw-r--r--    1 root     root       4503676 Nov 23 23:23 STPhrases.ocd
```
9. rebuild, again you need python, g++ in the container to do this
```
/usr/src/node_modules/opencc #  npm install --unsafe-perm  --build-from-source
```
10. check the ocd file is re-generated, new dict, yep!
```
/usr/src/node_modules/opencc # ls -la build/Release/
total 5396
drwxr-xr-x    1 root     root          1020 Nov 25 22:52 .
drwxr-xr-x    1 root     root           180 Nov 25 22:51 ..
-rw-r--r--    1 root     root       4508027 Nov 25 22:52 STPhrases.ocd
/usr/src/node_modules/opencc # exit
```
11. check translation is actually working by entering ttrss container, `docker ps`, 
```
docker exec -it {ttrss container_id} curl --request POST \
--url service.opencc:3000/s2twp \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data 'title=唐納德·特朗普 奧巴馬 為什么 \
&content=內存調用'
{"title":"唐納·川普 歐巴馬 為什麼 \\\n","content":"記憶體管理"}
```

Have fun !! 
Thank you all the developers for the wonderful open source software!

**Comment by HenryQW** [comment]
Thanks for the info!
