### ISSUE TITLE
是否可以支持纯ip生成的feed

### ISSUE THREAD

**Issue by yanbodestroyer** [HenryQW/Awesome-TTRSS#228]
**该功能能够解决的问题**
开发者您好。在TTRSS以前的某个版本中，个人自建的纯IP形式的rsshub的feed是可以订阅的。但是更新到最新版本发现不再支持。想问一下啊是否可以支持一下纯ip生成的feed。谢谢
**形容理想的解决方案**
支持一下纯ip生成的feed。例如:http://192.168.0.1:1200/sspai/matrix

**其他**
任何有助于解决方案开发的信息，如：某插件已实现相关功能。

**Comment by HenryQW** [comment]
用docker network service names可以解决该问题。
