### ISSUE TITLE
[BUG] 上游改动导致 ALLOW_PORTS 失效

### ISSUE THREAD

**Issue by HenryQW** [HenryQW/Awesome-TTRSS#232]
**Bug 描述**
https://git.tt-rss.org/fox/tt-rss/commit/95d0cb4953b93ed7b40556ff5c79327b0cde5c32

修复 WIP

**Comment by lechengyu** [comment]
今晚构建的时候。添加了ALLOW_PORTS，会导致订阅不了任何源，提示“无法从指定的网址下载:HTTP/1.1 404 Not Found”或者“无法从指定的网址下载:false”。移除ALLOW_PORTS变量，则恢复正常。不知道新版有没有修复这个BUG
