### ISSUE TITLE
最新镜像错误

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#233]
standard_init_linux.go:219: exec user process caused: exec format error

**Comment by buzhangjiuzhou** [comment]
it seams that  the author forget something in the script, as follows:
https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error

**Comment by buzhangjiuzhou** [comment]
I've encountered the same error!

**Comment by nahornyy** [comment]
i have some issue too

**Comment by yche2990** [comment]
i have the same issue

**Comment by buzhangjiuzhou** [comment]
The same error still exists in today's image.

**Comment by HenryQW** [comment]
It works for me so I don't where to start if you guys just say "it doesn't work".

**Comment by forest0** [comment]
I pulled the latest image and it works fine now.

**Comment by HenryQW** [comment]
> It works for me so I don't know where to start if you guys just say "it doesn't work".
