### ISSUE TITLE
[Feature] 如何配置 SMTP 复制，支持发送邮件

### ISSUE THREAD

**Issue by Samurais** [HenryQW/Awesome-TTRSS#239]
如图：

![image](https://user-images.githubusercontent.com/3538629/104793443-8a9f0b80-57dd-11eb-96bc-00f506112c22.png)

理想情况，系统配置 SMTP 服务，发送邮件，对所有用户都有效的统一的邮箱账号。

**Comment by Samurais** [comment]
fox 提供的插件，https://git.tt-rss.org/fox/ttrss-mailer-smtp

但是这个不是提供在默认插件中，以及可以在界面上配置更合理吗。

**Comment by HenryQW** [comment]
这个还是自行映射（插件，config.php以及ca证书）比较方便。

**Comment by ZacharyRen77** [comment]
您好，请问您解决这个问题了吗？我用git clone了该插件ttrss-mailer-smtp，并且在config.php里配置了smtp，但还是无法使用，显示smtp connect failed()
