### ISSUE TITLE
[BUG]迁移导出数据库报错

### ISSUE THREAD

**Issue by ZhuningS** [HenryQW/Awesome-TTRSS#241]
**Bug 描述**
简洁明了地描述这个 bug。

![捕获](https://user-images.githubusercontent.com/38108376/106387175-7b41d400-6413-11eb-9acb-ef2649364dcb.PNG)

Error response from daemon: Container 808a4a1c8088a962a9237542bf826a00a46043ee9460846b2b78164e3dc4be2f is not running
**你谷歌/百度了吗？**
请善用搜索引擎。
已经百度，没有这个容器，但是报错
**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]
latest
**部署环境**
 - 操作系统: [如 Ubuntu 18.04]
 - 浏览器: [如 chrome, safari]
腾讯云centos7
**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'云服务器
2. 点击 '....'登录
3. 滑动至 '....'按照官网文档https://ttrss.henry.wang/zh/#%E6%95%B0%E6%8D%AE%E5%BA%93%E6%9B%B4%E6%96%B0%E6%88%96%E8%BF%81%E7%A7%BB
运行以下步骤后报错
停止所有服务容器：
docker-compose stop
复制 Postgres 数据卷 ~/postgres/data/（或者你在 docker-compose 中指定的目录）至其他任何地方作为备份，这非常重要！
执行如下命令来导出所有数据：
docker exec postgres pg_dumpall -c -U 数据库用户名 > export.sql
4. 发现错误
Error response from daemon: Container 808a4a1c8088a962a9237542bf826a00a46043ee9460846b2b78164e3dc4be2f is not running
**预期结果**
简洁明了地描述正确的预期结果该是怎样的。
正常导出
**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100

`
[root@VM_0_8_centos ~]# docker logs ttrss --tail 100
PDOException: SQLSTATE[08006] [7] FATAL:  database "ttrss" does not exist in /configure-db.php:127
Stack trace:
#0 /configure-db.php(127): PDO->__construct('pgsql:host=data...', 'postgres', 'ttrss')
#1 /configure-db.php(135): dbexist(Array)
#2 /configure-db.php(34): dbcheckdb(Array)
#3 {main}Database not found, creating.
Database table not found, applying schema... 
[28-Sep-2020 07:35:53] NOTICE: fpm is running, pid 22
[28-Sep-2020 07:35:53] NOTICE: ready to handle connections
s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan: fatal: unable to exec .s6-svscan/crash: No such file or directory
`

` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
`Error response from daemon: Container 808a4a1c8088a962a9237542bf826a00a46043ee9460846b2b78164e3dc4be2f is not running`

容器没在运行

**Comment by ZhuningS** [comment]
截图中已经试过了，docker start后提示这个容器不存在

**Comment by HenryQW** [comment]
你看你自己发的截图，你的pg容器都没在运行，ttrss当然无法连接上数据库
