### ISSUE TITLE
[BUG]mercury_fulltext php8下有错误

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#248]
E_USER_WARNING (512)
--
classes/pluginhost.php:147

Error: Call to undefined method Feeds::getFeedTitle() in /var/www/plugins.local/mercury_fulltext/init.php:130
Stack trace:
#0 /var/www/classes/pluginhost.php(143): mercury_fulltext->hook_prefs_tab('prefFeeds')
#1 /var/www/classes/pref/feeds.php(1403): PluginHost->run_hooks('hook_prefs_tab', 'prefFeeds')
#2 /var/www/backend.php(120): Pref_Feeds->index()
#3 {main}
1. classes/pluginhost.php(147): user_error(Error: Call to undefined method Feeds::getFeedTitle() in /var/www/plugins.local/mercury_fulltext/init.php:130
Stack trace:
#0 /var/www/classes/pluginhost.php(143): mercury_fulltext->hook_prefs_tab('prefFeeds')
#1 /var/www/classes/pref/feeds.php(1403): Plug..., 512)
2. classes/pref/feeds.php(1403): run_hooks(hook_prefs_tab, prefFeeds)
3. backend.php(120): index()

Real IP: xxx
Forwarded For: xxx
Forwarded Protocol: https
Remote IP: 172.18.0.1
Request URI: /backend.php?op=pref-feeds
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

**Comment by ptsa** [comment]
Undefined array key "mercury_fulltext_enabled"
1. plugins.local/mercury_fulltext/init.php(173): ttrss_error_handler(2, Undefined array key "mercury_fulltext_enabled", plugins.local/mercury_fulltext/init.php, 173)
2. classes/pluginhost.php(143): hook_prefs_save_feed(482)
3. classes/pref/feeds.php(1076): run_hooks(hook_prefs_save_feed, 482)
4. classes/pref/feeds.php(993): editsaveops()
5. backend.php(120): editSave()

Real IP: xxx
Forwarded For: xxx
Forwarded Protocol: https
Remote IP: 172.18.0.1
Request URI: /backend.php
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

**Comment by HenryQW** [comment]
php8 is creating way too many problems, I have reverted #246 so `main` branch and the dockerhub image should be usable again.

For anyone who wants to use php8 now, please see `php8` branch,
