### ISSUE TITLE
[BUG]options_per_feed 错误,并且设置无法保存

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#249]
E_WARNING (2) |
 plugins.local/options_per_feed/init.php:200 |
 Undefined array key 1 1. plugins.local/options_per_feed/init.php(200): ttrss_error_handler(2, Undefined array key 1, plugins.local/options_per_feed/init.php, 200) 2. classes/pluginhost.php(196): hook_fetch_feed(, https://imagician.net/feed, 1, 482, 0, , ) 3. classes/rssutils.php(416): chain_hooks_callback(hook_fetch_feed, {Closure}, , https://imagician.net/feed, 1, 482, 0, , ) 4. update.php(240): update_rss_feed(482, 1)

更改设置无法保存

**Comment by ptsa** [comment]
E_USER_WARNING (512) | 
classes/pluginhost.php:147


Error: Call to undefined function db_escape_string() in /var/www/plugins.local/options_per_feed/init.php:323
Stack trace:
#0 /var/www/classes/pluginhost.php(143): Options_Per_Feed->hook_prefs_save_feed(482)
#1 /var/www/classes/pref/feeds.php(1076): PluginHost->run_hooks('hook_prefs_save...', 482)
#2 /var/www/classes/pref/feeds.php(993): Pref_Feeds->editsaveops(false)
#3 /var/www/backend.php(120): Pref_Feeds->editSave()
#4 {main}
1. classes/pluginhost.php(147): user_error(Error: Call to undefined function db_escape_string() in /var/www/plugins.local/options_per_feed/init.php:323
Stack trace:
#0 /var/www/classes/pluginhost.php(143): Options_Per_Feed->hook_prefs_save_feed(482)
#1 /var/www/classes/pref/feeds.php(1076): PluginH..., 512)
2. classes/pref/feeds.php(1076): run_hooks(hook_prefs_save_feed, 482)
3. classes/pref/feeds.php(993): editsaveops()
4. backend.php(120): editSave()

Real IP: xxx
Forwarded For: xxx
Forwarded Protocol: https
Remote IP: 172.18.0.1
Request URI: /backend.php
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

**Comment by HenryQW** [comment]
php8 is creating way too many problems, I have reverted #246 so `main` branch and the dockerhub image should be usable again.

For anyone who wants to use php8 now, please see `php8` branch,

**Comment by HenryQW** [comment]
Actually not, it's due to underlying changes made by the upstream, still identifying which commit causes the problem.

**Comment by HenryQW** [comment]
See #253, I will close this as it's the same underlying issue.
