### ISSUE TITLE
[BUG]E_WARNING (2)	classes/rssutils.php:47	touch(): Utime failed: Permission denied 应该是某个文件夹权限问题

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#250]
[BUG]E_WARNING (2)	
classes/rssutils.php:47	
touch(): Utime failed: Permission denied 
应该是某个文件夹权限问题

**Comment by ptsa** [comment]
应该是改了用户的关系 以前是nobady 现在是www-date
把/feed-icons/ 里的图标删除 让他重建就可以
看看后续会不会再提示

**Comment by HenryQW** [comment]
php8 is creating way too many problems, I have reverted #246 so `main` branch and the dockerhub image should be usable again.

For anyone who wants to use php8 now, please see `php8` branch,
