### ISSUE TITLE
[BUG]After update, error message

### ISSUE THREAD

**Issue by yche2990** [HenryQW/Awesome-TTRSS#251]
**Describe the bug**
I saw the message Could not update headlines (invalid object received - see error console for details)

And the message:

classes/pluginhost.php:147 | Error: Call to undefined method Feeds::getFeedTitle() in /var/www/plugins.local/mercury_fulltext/init.php:130 Stack trace: #0 /var/www/classes/pluginhost.php(143): mercury_fulltext->hook_prefs_tab('prefFeeds') #1 /var/www/classes/pref/feeds.php(1403): PluginHost->run_hooks('hook_prefs_tab', 'prefFeeds') #2 /var/www/backend.php(120): Pref_Feeds->index() #3 {main} 1. classes/pluginhost.php(147): user_error(Error: Call to undefined method Feeds::getFeedTitle() in /var/www/plugins.local/mercury_fulltext/init.php:130 Stack trace: #0 /var/www/classes/pluginhost.php(143): mercury_fulltext->hook_prefs_tab('prefFeeds') #1 /var/www/classes/pref/feeds.php(1403): Plug..., 512) 2. classes/pref/feeds.php(1403): run_hooks(hook_prefs_tab, prefFeeds) 3. backend.php(120): index() Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /backend.php?op=pref-feeds User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
-- | --

**Comment by HenryQW** [comment]
close as duplicates #248
