### ISSUE TITLE
[BUG]自动更新后报错

### ISSUE THREAD

**Issue by hackenfu** [HenryQW/Awesome-TTRSS#252]
Startup failed
Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:

ICONS_DIR defined in config.php is not writable (chmod -R 777 feed-icons).
You might want to check tt-rss wiki or the forums for more information. Please search the forums before creating new topic for your question.

**Comment by HenryQW** [comment]
php8 is creating way too many problems, I have reverted #246 so `main` branch and the dockerhub image should be usable again.

For anyone who wants to use php8 now, please see `php8` branch,
