### ISSUE TITLE
[Urgent] ttrss upstream breaking changes 上游破坏性更新导致latest镜像不稳定

### ISSUE THREAD

**Issue by HenryQW** [HenryQW/Awesome-TTRSS#253]
TTRSS upstream had made a lot of changes recently, and some are breaking changes.

Many plugins stopped working and I'm still trying to fix them, and unfortunately, I'm very busy at the moment. If you are able to help out, these are core plugins that need a fix urgently:

https://github.com/HenryQW/mercury_fulltext
https://github.com/HenryQW/tinytinyrss-fever-plugin

A stable image without these changes is available via the tag `wangqiru/ttrss:latest-2021-02-14`, you can use that until all plugins are made compatible with ttrss.

近期 TTRSS 释出大量破坏性更新（包括更新至php8），底层逻辑改动导致第三方插件全部失效。部分插件修复之后，TTRSS 又释出了更多的破坏性更新。由于 TTRSS 作者 fox 在很久之前就决定停止使用 release 作为版本控制，导致鉴别破坏性更新并提前应对的难度极高，所以`latest`或`nightly`镜像将极为不稳定。为了稳定性考虑，目前请使用稳定镜像`wangqiru/ttrss:latest-2021-02-14`。

**Comment by dimon222** [comment]
Is there list of issues and way to replicate? Or is it plain fails to run?

**Comment by HenryQW** [comment]
@dimon222 

I think the problem starts here

https://git.tt-rss.org/fox/tt-rss/commit/6b5c9c781b082c116538c313038f6d9c3ebdb757

Which causes plugins that reply on `print_hidden("op", "pluginhandler")` to produce the following error:


```
Error: Call to undefined function print_hidden() in /var/www/plugins/fever/init.php:56
Stack trace:
#0 /var/www/classes/pluginhost.php(143): Fever->hook_prefs_tab('prefPrefs')
#1 /var/www/classes/pref/prefs.php(1054): PluginHost->run_hooks('hook_prefs_tab', 'prefPrefs')
#2 /var/www/backend.php(120): Pref_Prefs->index()
#3 {main}
1. classes/pluginhost.php(147): user_error(Error: Call to undefined function print_hidden() in /var/www/plugins/fever/init.php:56
Stack trace:
#0 /var/www/classes/pluginhost.php(143): Fever->hook_prefs_tab('prefPrefs')
#1 /var/www/classes/pref/prefs.php(1054): PluginHost->run_hooks('hook_prefs_tab'..., 512)
2. classes/pref/prefs.php(1054): run_hooks(hook_prefs_tab, prefPrefs)
3. backend.php(120): index()

Remote IP: 172.18.0.1
Request URI: /backend.php?op=pref-prefs
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
```

**Comment by HenryQW** [comment]
Also, https://github.com/HenryQW/tinytinyrss-fever-plugin is a very ancient plugin that lacks serious maintenance, which causes trouble every time there is a major change from ttrss upstream. This time I think it's due to the newly introduced APP Password section.

However, I believe many users' daily readings (including mine) depend on this plugin, especially those using Reeder. 

If someone can upgrade (pretty much rewrite it), please contact me to claim the bounty, which will include whatever amount raised since 1th Jan 2021 until the end of 2021 on [Open Collective](https://opencollective.com/awesome-ttrss) for this repo.

**Comment by dimon222** [comment]
Based on very brief look over two mentioned commits, it seems like the mechanics behind building the outputs is changed from `print` to inline php.

Shouldn't be big deal to rewrite, I'll give it a shot and if get any success, PR will be provided.

More readable diff:
https://git.tt-rss.org/fox/tt-rss/commit/8e75551f95ec2ade517afce2afe76150d5ffda24.diff

I would assume that's major thing that probably broke most of plugins.

**Comment by dimon222** [comment]
I have started getting stuff fixed back right and center for Fever, but apparently solution was contributed to upstream Fever repository, so Fever is probably getting fixed right in this very moment. Safest approach is probably to reuse upstream repository (and patch whatever is needed for Awesome-TTRSS, I assume)
https://github.com/DigitalDJ/tinytinyrss-fever-plugin/commits/master
(more on this - https://community.tt-rss.org/t/syncing-via-fever-api-has-stopped-working/4308/8)

As mercury source code is much simpler, I would assume the only hotfix required for `print_hidden`. I'm checking quickly.

**Comment by HenryQW** [comment]
Great to see if's being maintained (sort of), I will switch to https://github.com/DigitalDJ/tinytinyrss-fever-plugin and ditch my own fork.

**Comment by dimon222** [comment]
Changes keep coming to TTRSS, I wonder if we have to review again for any new errors.

**Comment by HenryQW** [comment]
Yes it went on and on, and it stopped using release for versioning, which makes it really difficult to keep up.

**Comment by HenryQW** [comment]
It seems things are stable now, I'm running the latest image with fever and mercury, no issues.

**Comment by kulongwangzhi85** [comment]
难怪最近怎么老是无法使用

**Comment by hackenfu** [comment]
最近两个版本开始，彻底稳了，感谢大佬

**Comment by ding00** [comment]
最近的latest可以正常运行了，但是一旦我修改了pg数据库的密码（rss配置上也对应修改），就会再次出现数据库连接不上的错误
我的环境macos 11.2.2
采用docker-compose方式
