### ISSUE TITLE
[BUG] Fever plugin error

### ISSUE THREAD

**Issue by alexbogus** [HenryQW/Awesome-TTRSS#259]
- ## _What_ is the issue?

I'm using Reeder 5 with the FEVER prlugin on an iPad, and recently I cannot view categories on the app only the feeds
Looking on the system logs I can see a warning with the fever plugin.

- ## _What_ is your OS and its version?

iOS 14.5 and Reeder 5
Tiny Tiny RSS v21.02-92cb91e

- ## _What_ is your installation method?

Docker, with docker-compose.yml

- ### Others

- ## _Are_ there any error logs?

`Error: Call to undefined function print_hidden() in /var/www/plugins/fever/init.php:47 Stack trace: #0 /var/www/classes/pluginhost.php(144): Fever->hook_prefs_tab('prefPrefs') #1 /var/www/classes/pref/prefs.php(1054): PluginHost->run_hooks('hook_prefs_tab', 'prefPrefs') #2 /var/www/backend.php(120): Pref_Prefs->index() #3 {main} 1. classes/pluginhost.php(148): user_error(Error: Call to undefined function print_hidden() in /var/www/plugins/fever/init.php:47 Stack trace: #0 /var/www/classes/pluginhost.php(144): Fever->hook_prefs_tab('prefPrefs') #1 /var/www/classes/pref/prefs.php(1054): PluginHost->run_hooks('hook_prefs_tab'..., 512) 2. classes/pref/prefs.php(1054): run_hooks(hook_prefs_tab, prefPrefs) 3. backend.php(120): index() Real IP: 10.0.x.x Forwarded For: 10.0.1.21 Forwarded Protocol: https Remote IP: 172.24.0.2 Request URI: /backend.php?op=pref-prefs

- ## _How_ can the issue be replicated?

Every time I use the fever plugin

**Comment by alexbogus** [comment]
I changed to the nightly version and the issue was resolved

**Comment by HenryQW** [comment]
https://github.com/HenryQW/Awesome-TTRSS/issues/253

Too many changes recently from TTRSS, I would recommend against using `latest` or `nightly`. The stable version atm is `latest-2021-02-14`.
