### ISSUE TITLE
How to install new theme on Synology?如何安装下载的主题？

### ISSUE THREAD

**Issue by huazi007cn** [HenryQW/Awesome-TTRSS#260]
According official wiki:
Install by copying theme CSS (and any other content, if needed) into themes.local directory under tt-rss root, then you’ll be able to activate it in preferences.
But I cannot find the themes.local directory with my Synology ssh root account.

TTrss官方说明称在 themes.local 目录中拷贝进去下载的主题就可以在设定中激活新主题选单。但我群晖通过docker-compose安装的ttrss怎么也找不到这个文件夹，我用root权限登陆后用winscp搜索也找不到这个文件夹。

**Comment by HenryQW** [comment]
需要自行创建该文件夹

**Comment by huazi007cn** [comment]
小白一个，请教下应该在什么路径下创建呢？除了我自己按教程建了一个ttrss文件夹（在这个文件夹下创建了themes.local和themes文件夹，都不行），压根都找不到ttrss容器的文件路径？

**Comment by huazi007cn** [comment]
小白一个，请教下应该在什么路径下创建呢？除了我自己按教程建了一个ttrss文件夹（在这个文件夹下创建了themes.local和themes文件夹，都不行），压根都找不到ttrss容器的文件路径？

**Comment by HenryQW** [comment]
需要自行映射 /var/www/themes.local

**Comment by huazi007cn** [comment]
非常感谢！完美解决
