### ISSUE TITLE
Fever Emulation is wrong

### ISSUE THREAD

**Issue by huazi007cn** [HenryQW/Awesome-TTRSS#265]
There is no input place for fever passwords. I have tried with chrome and Edge. API is activated.
Fever插件是默认激活状态，且不能取消。然后到设置插件的地方就发现并没有设置密码的输入栏。API也已经勾选
![下载](https://user-images.githubusercontent.com/79095526/108613004-d0a74a80-73ed-11eb-9278-c36237ef8495.jpeg)

**Comment by HenryQW** [comment]
不按照issue模板，不搜一搜已有issue，所以你看不见那个输入框。
