### ISSUE TITLE
[BUG]昨天自动更新过后，就不能访问了！麻烦大佬看一下！谢谢

### ISSUE THREAD

**Issue by snakwu** [HenryQW/Awesome-TTRSS#270]
Startup failed
Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:

Please set Config::get(Config::SELF_URL_PATH) to the correct value detected for your server: https://rss.xxxxxx.com:4443/ (you're using: )
You might want to check tt-rss wiki or the forums for more information. Please search the forums before creating new topic for your question.

https地址是肯定是正确的，一直在正常使用，昨天自动更新过后，就不能访问了！
我有配置watchtower自动更新

**Comment by dimon222** [comment]
https://github.com/HenryQW/Awesome-TTRSS/issues/267#issuecomment-784246758

**Comment by snakwu** [comment]
> [#267 (comment)](https://github.com/HenryQW/Awesome-TTRSS/issues/267#issuecomment-784246758)

收到，谢谢！一时没看到置顶！
