### ISSUE TITLE
[BUG] postgres无法安装问题

### ISSUE THREAD

**Issue by wklesss** [HenryQW/Awesome-TTRSS#271]
**Bug 描述**
ERROR: for database.postgres  Cannot start service database.postgres: Bind mount failed: '/root/postgres/data' does not exists
ERROR: Encountered errors while bringing up the project.

**你谷歌/百度了吗？**
请善用搜索引擎。

**部署方法**
 -  docker-compose
 - 使用的镜像版本 [lates]

**部署环境**
 - 操作系统: [群辉6.2]
 - 浏览器: [如 chrome, safari]

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by chen23188** [comment]
这个问题我也碰到了，研究了一阵，发现这个是群晖Docker的机制导致的问题，群晖Docker的映射的目录必须要是在File Station中可见的目录，解决方法就是，把compose文件的第46行：~/postgres/data/  改成其他的文件夹，且必须保证该文件夹已经存在
