### ISSUE TITLE
[BUG] DB connect error

### ISSUE THREAD

**Issue by dvoijen** [HenryQW/Awesome-TTRSS#272]
**Describe the bug**
Every image after latest-2021-02-22 has a error connecting to the Postgress database.
The issue it says: tt-rss could not connect to server: No such file or directory 	Is the server running locally and accepting 	connections on Unix domain socket

**Have you googled?**
Yes i did

**Deployment method**
 - Docker
 - Version of the image used latest

**Deployment environment**
 - OS: QNAP
 - Browser: chrome

**To Reproduce**
Update the image to latest

**Error logs**
tt-rss could not connect to server: No such file or directory 	Is the server running locally and accepting 	connections on Unix domain socket

**Comment by kontaktwackler** [comment]
i see similar issue with newest docker image on synology nas. 
after starting the container and trying to connect via webbrowser i get following error message in browser:

Exception while creating PDO object:SQLSTATE[08006] [7] could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Comment by HenryQW** [comment]
See https://github.com/HenryQW/Awesome-TTRSS/issues/267#issuecomment-784246758
