### ISSUE TITLE
[BUG] Material-icons moved to composer, missing on Awesome-TTRSS

### ISSUE THREAD

**Issue by MEGAMENE** [HenryQW/Awesome-TTRSS#273]
**Describe the bug**
https://git.tt-rss.org/fox/tt-rss/commit/a22ddb2fe0d538ef930a47d480dd71ca1ad9f8d4

Apperantly the material-icons were moved to the offical ttrss composer, that means that they are now missing from the 
Awesome-TTRSS, and the Feedly theme can't load them.

**Deployment method**
 - Docker
 - Latest 01/03/2021

**Comment by HenryQW** [comment]
Will look into this

**Comment by HenryQW** [comment]
Should be fixed already.
