### ISSUE TITLE
last版本 s6-envuidgid: fatal: unknown user: nobody.php 错误

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#274]
last版本 s6-envuidgid: fatal: unknown user: nobody.php 错误

**Comment by dimon222** [comment]
I've currently just pulled latest `docker.io/wangqiru/ttrss:latest` and not able to replicate. It works without issues.
Can you confirm that you point to tag `latest` and its not old cached version?

**Comment by ptsa** [comment]
Not the version of the cache used， use docker.io/wangqiru/ttrss:latest ，The problem remains

**Comment by ptsa** [comment]
docker-compose.yml Does it need to be modified？

**Comment by dimon222** [comment]
I believe only `SELF_URL_PATH` is required to be modified, the rest is optional.

Are you running from regular `docker-compose.yml` or are you using any of custom versions (perhaps, postgres12 one or dev one)?
Plus, check in your `docker-compose.yml` if you do mount any volume in-place of entrypoint or in place of update-daemon/run as its obviously not intended by default.

**Comment by ptsa** [comment]
environment: 
     - DISABLE_USER_IN_DAYS=100

**Comment by dimon222** [comment]
Maybe due to this missing colon
https://github.com/HenryQW/Awesome-TTRSS/pull/275/files
