### ISSUE TITLE
options_per_feed log warnings

### ISSUE THREAD

**Issue by hackenfu** [HenryQW/Awesome-TTRSS#278]
![image](https://user-images.githubusercontent.com/51818740/110053919-2805cd00-7d95-11eb-81c1-22e57ecc9ff3.png)
看报的频率，应该是每获取一次feed，就报一次警告，影响使用倒是没有，就是一个三角感叹号有点逼死强迫症

**Comment by dimon222** [comment]
I don't see such warning, so I might assume its something very specific to options_per_feed plugin I assume?
Especially, considering that upstream repository haven't updated for past 2 years.
https://github.com/sergey-dryabzhinsky/options_per_feed

**Comment by hackenfu** [comment]
> I don't see such warning, so I might assume its something very specific to options_per_feed plugin?
> Especially, considering that upstream repository haven't updated for past 2 years, so it should probably be patched to use new Config.
> https://github.com/sergey-dryabzhinsky/options_per_feed

谢谢帮助！确实极有可能是这个插件的问题，因为部分feed必须使用代理proxy翻墙，所以我开启了这个插件。不知道有没有替代方案

**Comment by qingsongya** [comment]
切换主题，界面就不正常了，怎么回事，哪里有问题，楼主你有这个问题吗？
![image](https://user-images.githubusercontent.com/53110520/110097851-78534e00-7dda-11eb-95f4-bbba95a98ad5.png)

**Comment by hackenfu** [comment]
> 切换主题，界面就不正常了，怎么回事，哪里有问题，楼主你有这个问题吗？
> ![image](https://user-images.githubusercontent.com/53110520/110097851-78534e00-7dda-11eb-95f4-bbba95a98ad5.png)

我参照你试了下，确实，应该是feedly.css这个主题的问题，我一直用的是compact.css，毫无问题

**Comment by qingsongya** [comment]
这个时间格式可以不用英文的吗？
![image](https://user-images.githubusercontent.com/53110520/110100545-7d65cc80-7ddd-11eb-8856-064008c2e647.png)

**Comment by hackenfu** [comment]
> 这个时间格式可以不用英文的吗？
> ![image](https://user-images.githubusercontent.com/53110520/110100545-7d65cc80-7ddd-11eb-8856-064008c2e647.png)

我是英文的

**Comment by ptsa** [comment]
这个插件有替代的么  还是挺有用的

**Comment by HenryQW** [comment]
插件本身的问题，作者没有在维护了 https://github.com/sergey-dryabzhinsky/options_per_feed

**Comment by dimon222** [comment]
Contributed fix in here https://github.com/sergey-dryabzhinsky/options_per_feed/pull/3
If you want temporary workaround - you can take init.php from my branch and mount as volume in compose to respective plugin catalog.
```
- ./volumes/options_per_feed/init.php:/var/www/plugins.local/options_per_feed/init.php
```

**Comment by HenryQW** [comment]
TTRSS supports installing plugins from git repos directly now, so should be able to just do that from the UI and pointing to https://github.com/dimon222/options_per_feed/, while waiting for it to be merged.

**Comment by dimon222** [comment]
PS, use the upgrade branch, not the master
https://github.com/dimon222/options_per_feed/tree/feature/upgrade_to_latest
