### ISSUE TITLE
[BUG]mercury full text and opencc issues

### ISSUE THREAD

**Issue by yche2990** [HenryQW/Awesome-TTRSS#281]
I have tested the new version.

The fever plugin works fine.

However, the opencc not working.

The mercury plugin gives the following error:

plugins.local/mercury_fulltext/init.php:218 | Undefined property: stdClass::$content 1. plugins.local/mercury_fulltext/init.php(218): ttrss_error_handler(2, Undefined property: stdClass::$content, plugins.local/mercury_fulltext/init.php, 218) 2. plugins.local/mercury_fulltext/init.php(241): process_article([{"owner_uid":2,"guid":"2,https:\/\/www.chiphell.com\/article-25171-1.html","guid_hashed":"{\"ver\":2,\"uid\":2,\"hash\":\"SHA1:e98a604761e68afdb20e0b249b1933260d5419d3\"}","title":"\u8001\u724c\u5c71\u8fdb\u7684\u9876\u5c16\u529b\u4f5c\uff1a\u5168\u9891\u6...) 3. classes/pluginhost.php(198): hook_article_filter([{"owner_uid":2,"guid":"2,https:\/\/www.chiphell.com\/article-25171-1.html","guid_hashed":"{\"ver\":2,\"uid\":2,\"hash\":\"SHA1:e98a604761e68afdb20e0b249b1933260d5419d3\"}","title":"\u8001\u724c\u5c71\u8fdb\u7684\u9876\u5c16\u529b\u4f5c\uff1a\u5168\u9891\u6...) 4. classes/rssutils.php(801): chain_hooks_callback(hook_article_filter, {Closure}, [{"owner_uid":2,"guid":"2,https:\/\/www.chiphell.com\/article-25171-1.html","guid_hashed":"{\"ver\":2,\"uid\":2,\"hash\":\"SHA1:e98a604761e68afdb20e0b249b1933260d5419d3\"}","title":"\u8001\u724c\u5c71\u8fdb\u7684\u9876\u5c16\u529b\u4f5c\uff1a\u5168\u9891\u6...) 5. update.php(235): update_rss_feed(23, 1)
-- | --

**Comment by HenryQW** [comment]
again? Only fixed it a few days ago... I will look into this when I'm free...

**Comment by HenryQW** [comment]
I looked into this, I couldn't get the same error you are getting, things work perfectly on my side.
