### ISSUE TITLE
[BUG] Improve fever url doc?

### ISSUE THREAD

**Issue by bebound** [HenryQW/Awesome-TTRSS#286]
**Describe the bug**
The latest fever plugin suggest to
> Clone this repository to your plugins.local folder of your Tiny Tiny RSS installation.

And in preferences, the plugin says:
> To login with the Fever API, set your server details in your favourite RSS application to: xxxxxx/plugins.local/fever/

Should we add a notice for this in documentation? 

> In supported RSS readers, use https://[your url]/plugins/fever **(not https://[your url]/plugins.local/fever)** as the target server address, with your account and the password set in Step 2.

**Comment by HenryQW** [comment]
This will break so many people's TTRSS as they all run watchtower to auto update.

It does not affect anything AFAIK, so I do not plan to change it.

**Comment by dimon222** [comment]
Wait this is just documentation, not the actual endpoint to be changed
