### ISSUE TITLE
[BUG] ALLOW_PORTS is not working (Docker shows ALLOW_PORTS is still 80,433 despite custom ports have been set in docker-compose)

### ISSUE THREAD

**Issue by CXwudi** [HenryQW/Awesome-TTRSS#287]
**Describe the bug**
When I am testing out rsshub+awesome ttrss in docker. I can't subscribe to non 80,433 port feeds despite that I have `ALLOW_PORTS` set to others.
Here are screenshots
![bug](https://user-images.githubusercontent.com/17377423/114314103-28893600-9aae-11eb-9d99-dc1f585813b9.png)
I have confirmed that rsshub doesn't have any issue
![浏览器端](https://user-images.githubusercontent.com/17377423/114314163-64bc9680-9aae-11eb-9711-350da6c30ce8.png)
And as you can see, the `ALLOW_PORTS` has been set to `3900,3000`, but Docker side still shows `80,433` only
![ttrss-config](https://user-images.githubusercontent.com/17377423/114314105-2921cc80-9aae-11eb-89ca-06f28eaee1fd.png)
**Have you googled?**
Yes, and I found [this comment](https://github.com/HenryQW/Awesome-TTRSS/issues/195#issuecomment-748212801) promising the issue should be gone but it is not

**Deployment method**
 - docker-compose
 - Version: latest

**Deployment environment**
 - OS: WIndows 10 1909 
 - Browser: chrome

**To Reproduce**
1. download docker-compose file from rsshub
2. modify the docker-compose file to have rsshub connect on port 3900
3. download docker-compose file from awesome-ttress
4. modify the docker-compose file to have `ALLOW_PORTS=3900`
5. run `docker-compose up -d` on both rsshub and awesome-ttrss
6. login to Tiny Tiny RSS and subscribe to a feed through the rsshub on port 3900

**Expected behavior**
I should be able to subscribe non 80,433 port feeds

**Screenshots**
See above

**Error logs**
No meaningful logs found related to this issue

**Additional context**
No

**Comment by dimon222** [comment]
Perhaps what you want to try is to merge both compose files into one, and reference services by service name instead of NAT IP address

**Comment by CXwudi** [comment]
> Perhaps what you want to try is to merge both compose files into one, and reference services by service name instead of NAT IP address
> The error of connecting to not allowed port looks different from what you see. So it's something port mapping or IP resolving related.
Sorry, is my fault that I used a wrong `docker-compose.yml` file to launch the ttrss instances
Closing the issue now.  
But here is my ping and curl result within the ttrss docker container showing nothing wrong with connecting to the host internet
```
--- 192.168.1.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 2.016/2.202/2.389 ms
/var/www #
/var/www #
/var/www #
/var/www # curl 192.168.1.8:3900
<!DOCTYPE html><html><head><title>Welcome to RSSHub!</title>  <meta name="robots" content="noindex">  <style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-size:16px;color:#2c3e50}.content{position:absolute;left:50%;transform:translate(-50%,100px);min-width:400px;text-align:center}a{color:#f5712c}details{text-align:left;max-height:400px;overflow:auto}details::-webkit-scrollbar{width:5px}details::-webkit-scrollbar-thumb{border-radius:3px;background-color:#eee}details::-webkit-scrollbar-thumb:hover{background-color:#ccc}summary{margin-bottom:10px;outline:0;cursor:pointer}.debug-key{width:120px;text-align:right;display:inline-block;margin-right:10px}.debug-item{margin:5px 0;font-size:12px;line-height:24px}.debug-value{display:inline-block;vertical-align:top;white-space:pre}</style></head><body><div class="content"><p><img src="https://i.loli.net/2019/04/23/5cbeb7e41414c.png" alt="RSSHub" width="100"></p><h1>Welcome to <span style="color:#f5712c">RSSHub</span>!</h1><p>If you see this page, the RSSHub is successfully installed and working.</p><p>For online documentation and support please refer to <a href="https://docs.rsshub.app/" target="_blank">docs.rsshub.app</a>.</p><p>-- Made with <i style="color:#d43f57">♥</i> by <a href="https://diygod.me" target="_blank">DIYgod</a></p>  <details><summary>debug</summary>     <div class="debug-item"><span class="debug-key">Git Hash: </span><span class="debug-value">fddf9d7</span></div>    <div class="debug-item"><span class="debug-key">Request Amount: </span><span class="debug-value">1</span></div>    <div class="debug-item"><span class="debug-key">Request Frequency: </span><span class="debug-value">1.296 times/minute</span></div>    <div class="debug-item"><span class="debug-key">Cache Hit Ratio: </span><span class="debug-value">0.000</span></div>      <div class="debug-item"><span class="debug-key">Memory Usage: </span><span class="debug-value">165.474304 MB</span></div>    <div class="debug-item"><span class="debug-key">CPU Usage: </span><span class="debug-value">0%</span></div>    <div class="debug-item"><span class="debug-key">Run Time: </span><span class="debug-value">0.01 hour(s)</span></div>      <div class="debug-item"><span class="debug-key">Hot Paths: </span><span class="debug-value">1  /<br></span></div>       </details>  </div></body></html>/var/www #
/var/www #
```
