### ISSUE TITLE
Suggestion -> DB Permanence

### ISSUE THREAD

**Issue by robotictacos** [HenryQW/Awesome-TTRSS#288]
I recently did a bit of housekeeping and purged all images and did a redownload and a force recreate on my stack (which includes a number of other things besides ttrss).  I found that I had lost all my data in ttrss, my feeds, settings, etc.  Basically started from scratch.  What I found was that using your docker compose for the postgres DB didn't setup a proper volume and permissions within the postgres container.  Using [this](https://github.com/docker-library/postgres/issues/696) as a reference, I have fixed this in my setup, and would suggest modifying your docker compose file as follows:

    postgres: 
    container_name: postgres  
    image: postgres:13-alpine  
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata #postgres needs this set for mapping to work correctly
    volumes:
      - /config/postgres:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro #this allows mapping UID and GID from the host so permissions work correctly
    user: UID:GID #the numerical user and group ids
    networks:
      - t2_proxy
    ports:
      - 5432:5432
    restart: always

**Comment by HenryQW** [comment]
Sorry to hear about your experience, that sucks.

I'm not an expert here, so this alone is not enough?
https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml#L45-L46

I had them recreated multiple times and I did not lose any data.

**Comment by robotictacos** [comment]
Apparently not.  What I saw was that there were no files being created in the mapped volume (not sure where they went?).  I suspect (maybe) in your test case the internal UID/GID inside the postgres container just so happens to have adequate permissions to write to the volume on the host.  In my case anyway, it didn't.  So, I needed to do a couple of things:

1. Make sure the PGDATA variable was set (not sure this was actually needed but it doesn't hurt)
2. Map /etc/passwd as a read only volume so it can "translate" the ID's internally
3. Pass in the UID and GID via the user declaration

**Comment by HenryQW** [comment]
I think it's the UID/GUI that matter, `PGDATA` is not relevant. We can certainly add `user: "${UID}:${GID}"` in the compose file but it will require the user to set these 2 envs before bringing the stack up, and honestly, 99% of the current users have no idea how to do it.

Which distro are you using btw?
