### ISSUE TITLE
请问，要如何自定义文章页面的宽度呢？

### ISSUE THREAD

**Issue by akimolll** [HenryQW/Awesome-TTRSS#290]
因为显示器分辨率比较高的缘故，点开文章内容页面，版式会非常宽，不够美观。

之前在使用另一个镜像的时候，是可以在偏好设置里面自定义css页面宽度的。当我使用这个的镜像的时候，发现对feedly这款主题不起作用了。

div.cdm.expanded {
	width: calc(100% - 72px);
	max-width: 960px;
	margin: 21px auto;
}

.content {
	max-width: 50em;
	margin: 0 auto;
}

想问一下，会有解决方案吗？
我是在群晖Docker部署了它，似乎也没有映射任何修改添加主题的文件夹。
感谢。

**Comment by akimolll** [comment]
又测试了一下，在偏好设置中设置为 “始终展开” 文章，这个CSS就生效了。
取消勾选 “展开文章” ，手动点开标题的时候的状态，这段css就失效了。
至少在feedly主题里看上去是这样。

**Comment by HenryQW** [comment]
这是ttrss上游改动css所致的

**Comment by akimolll** [comment]
> 这是ttrss上游介入css所致的

嗯，除了这个问题，还有这个版本在Safari浏览器的支持上也有问题，登陆提示 window.requestIdleCallback not a function 的错误。

其他看起来一切都好。

**Comment by HenryQW** [comment]
> > 这是ttrss上游介入css所致的
> 
> 嗯，除了这个问题，还有这个版本在Safari浏览器的支持上也有问题，登陆提示 window.requestIdleCallback not a function 的错误。
> 
> 其他看起来一切都好。

https://github.com/HenryQW/Awesome-TTRSS/commit/1b077f26f8c40ce7dd7b2a0cf2263a3537118e07 修复了该问题。
