### ISSUE TITLE
部署完毕，未发送任何数据

### ISSUE THREAD

**Issue by Whisht** [HenryQW/Awesome-TTRSS#291]
**Bug 描述**
docker-compose 部署完毕，通过 ip 访问显示`ip 未发送任何数据`。

`docker logs -f `显示 `Operation timed out`

**部署方法**
 - docker-compose
 - 使用的镜像版本 latest

**部署环境**
 - 操作系统: centos 8
 - 浏览器: chrome

**复现步骤**
复现该 bug 的详细步骤
1. 打开 `http://ip:181/`

**截屏**
![image](https://user-images.githubusercontent.com/16497652/115489498-dce54200-a28e-11eb-8213-043f992f7f2b.png)

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。
```
Operation timed out
Operation timed out
Operation timed out
Operation timed out
```

**Comment by HenryQW** [comment]
我这里无法复现这个问题

**Comment by dimon222** [comment]
Could it be that you're using privileged ports (and knowing history of CentOS, it might not allow to map some without necessary special configurations)?
Try port above 1024
