### ISSUE TITLE
[BUG]能否开放不止一个地址登录？

### ISSUE THREAD

**Issue by hackenfu** [HenryQW/Awesome-TTRSS#292]
我的网络环境：主路由192.168.22.253，旁路由（翻墙）192.168.22.252，ttrss搭建在192.168.22.254的设备（网关192.168.22.253）上，ttrss我一直有翻墙需求，所以之前采用过HTTP_PROXY: ip:port或者Options per Feed的办法让ttrss全部或部分翻墙
因为我内外网都有访问需求，所以通过端口转发，SELF_URL_PATH设为ddns:端口，使用一直很顺利

最近192.168.22.254的设备其他应用也有翻墙需求，所以就把网关改成192.168.22.252，这样导致我内网无法用ddns:端口的方式访问各种应用了。其他应用都没问题，内网用内网ip就行，但是ttrss比较特殊，必须用SELF_URL_PATH，只能牺牲内网或外网之一的访问了，不知道SELF_URL_PATH能否设置为一个内网一个ddns两种地址？多谢！

**Comment by HenryQW** [comment]
据我所知不能

**Comment by ihcbbs** [comment]
实测可用反代修改header中HOST解决
我用的是caddy
