### ISSUE TITLE
刚安装不自动更新了

### ISSUE THREAD

**Issue by daqueque** [HenryQW/Awesome-TTRSS#301]
**Bug 描述**
第1、2天还会自动更新，第三天突然就不更新了。

**部署方法**
 - Docker
 - 
**部署环境**
 - 操作系统: centos 宝塔
 - 浏览器: 谷歌

**Comment by dimon222** [comment]
I guess something to do with Watchtower?

**Comment by HenryQW** [comment]
`latest`镜像没有更新，watchtower自然就不会有更新。

GitHub actions 目前抽风中 https://github.com/HenryQW/Awesome-TTRSS/actions/runs/853959131

**Comment by daqueque** [comment]
> `latest`镜像没有更新，watchtower自然就不会有更新。
> 
> GitHub actions 目前抽风中 https://github.com/HenryQW/Awesome-TTRSS/actions/runs/853959131

是因为GitHub actions抽风 所以不能更新吗？请问有没有解决办法了？
