### ISSUE TITLE
使用fever+reeder无内嵌视频

### ISSUE THREAD

**Issue by LiRJie** [HenryQW/Awesome-TTRSS#302]
**Bug 描述**
已添加iframe至环境变量，fever作为本地插件启用
![image](https://user-images.githubusercontent.com/45494542/118686571-b20eef00-b836-11eb-8c93-f28a6ceec6b1.png)
使用rsshub订阅b站视频，ttrss网页端有内嵌视频，而reeder内无视频

**你谷歌/百度了吗？**
无相关回答

**部署方法**
 docker-compose
 - 使用的镜像版本 latest

**部署环境**
 - 操作系统: 【Ubuntu 20.04]
 - 浏览器: [reeder]

**Comment by HenryQW** [comment]
这个应该反馈到 https://github.com/DIYgod/RSSHub 

**Comment by 1551255004** [comment]
> 

我也遇到了同样的问题。
