### ISSUE TITLE
docker安装时源程序无法从git.tt-rss.org下载

### ISSUE THREAD

**Issue by husx** [HenryQW/Awesome-TTRSS#31]
ttrss的主代码库https://git.tt-rss.org/git/tt-rss/src/master 使用了 Cloudflare，docker安装时无法从git.tt-rss.org下载源程序，安装失败。
建议修改ttrss下载地址为https://gitlab.com/gothfox/tt-rss 或增加设置ttrss下载地址的全局变量

**Comment by HenryQW** [comment]
无法复现。
