### ISSUE TITLE
网页地址和SELF_URL_PATH填写的一样，还是报错

### ISSUE THREAD

**Issue by haiyangzhijia** [HenryQW/Awesome-TTRSS#312]
**Bug 描述**
简洁明了地描述这个 bug。

Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:

Please set SELF_URL_PATH to the correct value detected for your server: http://192.168.50.62:182/ (you're using: %SELF_URL_PATH)
You might want to check tt-rss wiki or the forums for more information. Please search the forums before creating new topic for your question.
**你谷歌/百度了吗？**
请善用搜索引擎。
#

> 

**部署方法**
 - docker-compose
 - wangqiru/ttrss:latest-2021-02-14

**部署环境**
 - 操作系统: Raspberry Pi
 - 浏览器: chrome

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

![image](https://user-images.githubusercontent.com/23657541/125595685-94fe025e-bd67-403b-a77b-58b0f6e4b87e.png)

**Comment by HenryQW** [comment]
Compose配置？

**Comment by haiyangzhijia** [comment]
> 撰写配置？

是的
直接用的:https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml

**Comment by HenryQW** [comment]
正确配置是 SELF_URL_PATH=http://192.168.50.62:182/
如果还有问题就看看#62

**Comment by haiyangzhijia** [comment]
> 正确配置是SELF_URL_PATH= http://192.168.50.62:182/
> 如果还有问题就看看#62

Compose是这样写的SELF_URL_PATH=http://192.168.50.62:182

**Comment by HenryQW** [comment]
#62 里已经有出现该错误的解决方案了，一条条排查吧
