### ISSUE TITLE
[错误]

### ISSUE THREAD

**Issue by GayHub1** [HenryQW/Awesome-TTRSS#313]
**Describe the bug**

**Have you googled?**
Please google it now.

**Deployment method**
docker-compose
 - Version of the image used [e.g. latest, nightly, 19.8]
  20.10.7

**Deployment environment**
 - OS: [CentOS 8.2]

**To Reproduce**
运行后直接访问 IP：端口报错
当前无法使用此页面zhuoke.xyz 未发送任何数据。
ERR_EMPTY_RESPONSE

**Expected behavior**

**Screenshots**

**Error logs**
When the error occurs, execute `docker logs ttrss --tail 100` to obtain the error logs and paste **the relevant logs** here.

都是
Operation timed out

**Comment by HenryQW** [comment]
什么都信息都没有怎么帮你？

**Comment by GayHub1** [comment]
docker-compose 日志
![docker-compose 日志](https://user-images.githubusercontent.com/42793273/126046380-a8f6aee8-689a-4a5a-a63d-a3c6d6ea4986.png)
防火墙已经关闭181端口 
![image](https://user-images.githubusercontent.com/42793273/126046409-9898dd62-b895-4ac7-9356-078f86b65391.png)
docker-compose 仅仅修改了 SELF_URL_PATH 与DB_PASS ， POSTGRES_PASSWORD 
但是直接访问
![image](https://user-images.githubusercontent.com/42793273/126046444-f889228a-be2f-4d84-8449-0c34d400dcc7.png)
