### ISSUE TITLE
docker-compose 日志

### ISSUE THREAD

**Issue by GayHub1** [HenryQW/Awesome-TTRSS#314]
docker-compose 日志
![docker-compose 日志](https://user-images.githubusercontent.com/42793273/126046380-a8f6aee8-689a-4a5a-a63d-a3c6d6ea4986.png)
防火墙已经关闭181端口 
![image](https://user-images.githubusercontent.com/42793273/126046409-9898dd62-b895-4ac7-9356-078f86b65391.png)
docker-compose 仅仅修改了 SELF_URL_PATH 与DB_PASS ， POSTGRES_PASSWORD 
但是直接访问
![image](https://user-images.githubusercontent.com/42793273/126046444-f889228a-be2f-4d84-8449-0c34d400dcc7.png)

_Originally posted by @GayHub1 in https://github.com/HenryQW/Awesome-TTRSS/issues/313#issuecomment-881940214_

**Comment by HenryQW** [comment]
建议查看 pg logs，DB_USER 存在吗？
