### ISSUE TITLE
[Feature]出错的源请增加批量禁用按钮(而不是只有删除)

### ISSUE THREAD

**Issue by qokelate** [HenryQW/Awesome-TTRSS#316]
**该功能能够解决的问题**
在`Feeds with update errors`菜单中可以查看出错的Feeds, 但只能进行批量Unsubscribe,这不是个好主意,因为这些源可能是暂时不可用,我希望继续保留在列表中(设置更新周期为Disabled以减少资源消耗)

**形容理想的解决方案**
增加批量Disable按钮(若能直接批量Edit,则更好)

**其他**
无

**Comment by HenryQW** [comment]
关于 TTRSS 的功能需求请移步 https://community.tt-rss.org/
