### ISSUE TITLE
[BUG] operation time out怎么处理

### ISSUE THREAD

**Issue by feiyihx** [HenryQW/Awesome-TTRSS#317]
**Bug 描述**
运行之后日志显示operation timeout然后自动停止

**你谷歌/百度了吗？**
找不到解决方法

**部署方法**
 - Docker
 - latest

**部署环境**
 - unraid
 - edge, chrome, 搜狗浏览器

**复现步骤**
部署完了直接运行就报错

**Comment by HenryQW** [comment]
看看数据库容器有没有报错

**Comment by feiyihx** [comment]
> 看看数据库容器有没有报错

还真的是呢。mysql报错：mbind: Operation not permitted。

数据库创建的问题吗？新增ttrss账户，创建同名数据库并授予所有权限。还有别的地方需要设置吗？我唯一能想到出问题的就是认证插件了，目前是按照nextcloud和photoprism一样选择的mysql自带的身份验证。还有一个sha256密码验证和caching2 sha2验证。之前装过需要用到mysql的都只能通过mysql自带验证，其他两个都调用不了。

**Comment by feiyihx** [comment]
> 看看数据库容器有没有报错

按照dockerhub的说明给了数据库--security-opt seccomp=unconfined参数绕开安全设置，还是报同样的错。

**Comment by HenryQW** [comment]
> 新增ttrss账户，创建同名数据库并授予所有权限
这样应该就没问题了，我没试过认证插件
