### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by balajeek** [HenryQW/Awesome-TTRSS#318]
**Describe the bug**
Trying to install the plug-in from preference menu -> install plugin option

**Have you googled?**
Yes

**Deployment method**
 - docker-compose
 - Version:latest

**Deployment environment**
 - OS: Ubuntu 21.04]
 - Browser: [chrome based, Brave]

**To Reproduce**
1. Go to Preferences/Settings
2. Click on 'Plugins' panel and click 'Install plugin'
3. Search for 'smtp' and choose ttrss-mailer-smtp
4. Click Install
5. you see message "Installing ttrss-mailer-smtp, please wait..." and its stuck on it for long time.

**Expected behavior**
installs the plug-in so i can configure email alerts

**Screenshots**
![image](https://user-images.githubusercontent.com/19213088/127655147-76bedd37-65f3-474d-b728-6cbdbe852b56.png)

**Error logs**
no messages or errors in the log after install clicked.

**Additional context**
If this will not work, are there any option to install manually, please let me know steps so i can try,

**Comment by HenryQW** [comment]
Duplicate #283 

I think it's a permission issue.
