### ISSUE TITLE
如何规避无法订阅本地feed的问题？

### ISSUE THREAD

**Issue by x1a0xv4n** [HenryQW/Awesome-TTRSS#322]
无法订阅解析为127.0.0.1的feed

![image](https://user-images.githubusercontent.com/8591495/129311219-2a51255b-d31a-4340-88f7-6bedfb0b91f5.png)

查了一下源码，确实目前有此限制，尝试了几种方法都无法解决，也尝试了freshrss和miniflux，也都限制了本地feed

请问ttrss如何规避无法订阅本地feed的问题？

**Comment by wujunchuan** [comment]
rsshub.wrss.top 会被解析到 127.0.0.1 吗？

**Comment by x1a0xv4n** [comment]
> rsshub.wrss.top 会被解析到 127.0.0.1 吗？

是的，部署在本地的

**Comment by wujunchuan** [comment]
> > rsshub.wrss.top 会被解析到 127.0.0.1 吗？
> 
> 是的，部署在本地的

试试解析到内网 IP（改HOST 或者 DNS 都可以），或者搭一层 Nginx 做反向代理

**Comment by x1a0xv4n** [comment]
问题解决了，总结一下

因为本地局域网IP还是会被解析成127.0.0.1，所以只改host或者只加一层反代是不行的，所以如果想部署在本地，有以下两种方法

如果想部署在同一台机器上，需要用DNSmasq之类的服务改DNS
如果不想改DNS，可以把rsshub和ttrss分开部署，这样解析出来的是另一台机器的局域网IP
