### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by neo1104** [HenryQW/Awesome-TTRSS#325]
**Bug 描述**

老问题，在nginx反向代理二级目录xxx.com/ttrss/的时候，点击文章标题显示 xxxx.net/backend.php , 404,not found

**你谷歌/百度了吗？**
已经google了，发现有其它用户反馈了同样的问题，但是没有得到确切的一个解决方案

**部署方法**
 - docker-compose
 - 使用的镜像版本 latest

**部署环境**
 - 操作系统:  raspberrypi. 4b
 - 浏览器: chrome

**预期结果**
预期结果应该是在chrome的新tab上显示文章的原始页面

**其他**
通过观察我发现了以下几个特点：

1.  文章的标题所指向的地址并不是反代nginx的地址
2. 点击了文章标题后，nginx上并没有任何访问日志
3. 所以是否有可能是处理文章标题的点击方法并没有正确处理域名的subdirectory导致，我不懂php，所以这点需要大家的确认和帮助

**Comment by HenryQW** [comment]
这是nginx反代设置的问题，与本repo无关。

**Comment by neo1104** [comment]
如果是nginx的配置问题 我强烈建议作者可以尝试下ngixn的subdirectory，然后指正正确的做法 因为我完全按照文档中的描述一样导致此类问题
