### ISSUE TITLE
[BUG]Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by fucao** [HenryQW/Awesome-TTRSS#326]
**Bug 描述**

安装最新版后，报错。

**你谷歌/百度了吗？**

搜过

**部署方法**
 - docker-compose
 - 使用的镜像版本 [如 今天装的最新版]

**部署环境**
 - 操作系统: [ esxi]
 - 浏览器: [chrome]

**复现步骤**

安装后打开网页就这样

**预期结果**

无弹窗

**截屏**
![image](https://user-images.githubusercontent.com/15061002/130357417-508f3cb4-4cdc-4efb-b2b5-f29cf443afa0.png)

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
换个浏览器试试看
