### ISSUE TITLE
在群晖docker上安装了rsshub，使用的是1200端口，ttrss无法正常订阅[BUG]

### ISSUE THREAD

**Issue by fucao** [HenryQW/Awesome-TTRSS#329]
**Bug 描述**
在群晖docker上安装了rsshub，使用的是1200端口，ttrss无法正常订阅

**你谷歌/百度了吗？**
https://www.h3399.cn/202011/784925.html
搜到了这个，但给出的配置不能正常使用。

**部署方法**
 - docker-compose

**部署环境**
 - 群晖

**截屏**
![image](https://user-images.githubusercontent.com/15061002/131517407-44605d14-3b53-44aa-8df1-b28972ff11b6.png)

**预期结果**
可以搭配rsshub使用

**错误日志**
Requested URL failed extended validation. 

**其他**
任何有助于 bug 修复的信息。

**Comment by mqq982068** [comment]
想问一下怎么解决的
