### ISSUE TITLE
[Feature]为什么不弄到hub.docker上？不是方便得多么

### ISSUE THREAD

**Issue by mapleshadow** [HenryQW/Awesome-TTRSS#331]
RT，为什么能告诉原因吗？

**Comment by HenryQW** [comment]
你说的每个字我都能看懂，连在一起却不知道你在说什么。

**Comment by mapleshadow** [comment]
是否可以考虑在https://hub.docker.com/上进行注册，这样就可以方便的用docker容器通过命令下载安装了，特别对于群晖会很友好。目前在https://hub.docker.com/可以搜索到有人代为发布了，但由于版本较老，貌似已不在更新。

**Comment by HenryQW** [comment]
一直都自动自动发布

https://github.com/HenryQW/Awesome-TTRSS/blob/a1a57a3608665945f7e4dfd12407d778eec799b7/docker-compose.yml#L4
