### ISSUE TITLE
[BUG] nginx反向代理HTTPS，SELF_URL_PATH问题

### ISSUE THREAD

**Issue by zsbai** [HenryQW/Awesome-TTRSS#332]
**Bug 描述**
简洁明了地描述这个 bug。

已经反复检测过配置文件和配置文档...如果还是这方面的问题那就是我眼瞎了

**你谷歌/百度了吗？**
请善用搜索引擎。

**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]

使用docker- compose部署

**部署环境**
 - 操作系统: [如 Ubuntu 18.04]
 - 浏览器: [如 chrome, safari]

Debian10 浏览器Safari

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

看图：
<img width="1297" alt="截屏2021-09-19 下午12 04 54" src="https://user-images.githubusercontent.com/62942942/133915056-4bfc1d9e-052d-47e7-b8b9-d504bf17e8b4.png">
如果我更改配置文件为http,则会出现
<img width="1075" alt="截屏2021-09-19 下午12 06 01" src="https://user-images.githubusercontent.com/62942942/133915075-b341c6af-cdc5-4e17-b03b-76d6ec7cfd44.png">

尝试更换浏览器：更换为Chrome最新版，当我配置文件为http的时候，访问正常,配置改为https一样的提示，最后附上配置文件的截图
<img width="689" alt="截屏2021-09-19 下午12 08 29" src="https://user-images.githubusercontent.com/62942942/133915127-317be0ec-b564-4e5f-b9a6-f1db9002785b.png">

尝试重新安装，重新添加反向代理，清除浏览器缓存，都没啥用啊....

**错误日志**

当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by zsbai** [comment]
。。。。。已查明为nginx反代问题，稍加一行配置，已解决

**Comment by frankwuzp** [comment]
请问是怎么解决的？遇到同样的问题，在宝塔上用的反向代理，不知是要加哪个配置？

**Comment by zsbai** [comment]
> 请问是怎么解决的？遇到同样的问题，在宝塔上用的反向代理，不知是要加哪个配置？

```
#PROXY-START/
location  ~* \.(gif|png|jpg|css|js|woff|woff2)$
{
    proxy_pass http://127.0.0.1:181;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header  X-Frame-Options     SAMEORIGIN;
    proxy_set_header  X-Forwarded-Proto   $scheme;
    expires 12h;
}
location /
{
    proxy_pass http://127.0.0.1:181;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header  X-Frame-Options     SAMEORIGIN;
    proxy_set_header  X-Forwarded-Proto   $scheme;
    
    add_header X-Cache $upstream_cache_status;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
}

#PROXY-END/
```
我就照着别人的，把宝塔少写的都补上去了

**Comment by frankwuzp** [comment]
谢谢帮助，it worked，用上https 了 🤞

**Comment by online-web2025** [comment]
> > > 请问是怎么解决的？遇到同样的问题，在宝塔上用的反向代理，不知是要加哪个配置？
> > 
> > 
> > ```
> > #PROXY-START/
> > location  ~* \.(gif|png|jpg|css|js|woff|woff2)$
> > {
> >     proxy_pass http://127.0.0.1:181;
> >     proxy_set_header Host $host;
> >     proxy_set_header X-Real-IP $remote_addr;
> >     proxy_set_header X-Forwarded-Ssl on;
> >     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     proxy_set_header REMOTE-HOST $remote_addr;
> >     proxy_set_header  X-Frame-Options     SAMEORIGIN;
> >     proxy_set_header  X-Forwarded-Proto   $scheme;
> >     expires 12h;
> > }
> > location /
> > {
> >     proxy_pass http://127.0.0.1:181;
> >     proxy_set_header Host $host;
> >     proxy_set_header X-Real-IP $remote_addr;
> >     proxy_set_header X-Forwarded-Ssl on;
> >     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     proxy_set_header REMOTE-HOST $remote_addr;
> >     proxy_set_header  X-Frame-Options     SAMEORIGIN;
> >     proxy_set_header  X-Forwarded-Proto   $scheme;
> >     
> >     add_header X-Cache $upstream_cache_status;
> >     
> >     #Set Nginx Cache
> >     
> >     	add_header Cache-Control no-cache;
> > }
> > 
> > #PROXY-END/
> > ```
> > 
> > 
> > 我就照着别人的，把宝塔少写的都补上去了
> 
> 这个配置如何加载？在哪加载？是要新建一个文件吗？我到这一步过不去了，小白遇坑多，求教

在宝塔的这个位置开始
![image](https://github.com/HenryQW/Awesome-TTRSS/assets/138352290/030566fb-0687-4d50-a031-b41b5d7d620c)
绑定域名之后，申请完ssl，就开始修改配置文件。
把代码复制上去，修改对应开放的端口。
