### ISSUE TITLE
[BUG] 重置密码后没有保存，重装以后无法使用默认账密登陆

### ISSUE THREAD

**Issue by Guluji** [HenryQW/Awesome-TTRSS#335]
**Bug 描述**
使用了重置密码功能，未保存重置后密码，
之后无法登陆，重装一遍后还无法使用默认的password密码，
之前也未绑定邮箱，不知道合法的用户名和邮箱地址

**你谷歌/百度了吗？**
无结果

**部署方法**
 -  docker-compose
 -  latest

**部署环境**
 - centOS7

**复现步骤**
复现该 bug 的详细步骤
1. 点击重置密码，之后自动返回ttrss登陆界面，无法登录，重装无效

**Comment by HenryQW** [comment]
没设置smtp服务器，是没办法用邮件重置密码的。如果想不起来密码，只能通过连接数据库重置为初始密码，见：[https://git.tt-rss.org/fox/tt-rss/wiki/FAQ](https://git.tt-rss.org/fox/tt-rss/wiki/FAQ)
