### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lylunula** [HenryQW/Awesome-TTRSS#338]
**Bug 描述**
内网客户端无法通过Fever API访问TTRSS：内网在Web端是可以访问TTRSS web页面，使用iOS Reeder连接内网就不可以更新，但是切换5G 或者在公司就可以正常使用。
我的情况是这样：部署在群晖docker里面，另外为了内外网正常访问，群晖起了DNS用于区分内外网使用。但我关闭DNS也不能解决问题，我估计不是TTRSS的问题，但是我实在没想法是什么原因导致的，求助一下

**你谷歌/百度了吗？**
都用了，没有我类似的问题

**部署方法**
 - docker-compose
 - 使用的镜像版本 latest
 - 
**部署环境**
 - 操作系统: 群晖DSM7.0 Docker
 - 浏览器:chrome

**复现步骤**
复现该 bug 的详细步骤
1. 内网
2. 客户端使用fever API访问报错

**预期结果**
内网客户端可以正常访问

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
你要不给我寄个群晖我给你看看🌚
