### ISSUE TITLE
[BUG] Looking for instructions to configure the SMTP plugin.

### ISSUE THREAD

**Issue by es9o** [HenryQW/Awesome-TTRSS#339]
**Describe the bug**
I'm attempting to install the [ttrss SMTP plugin](https://git.tt-rss.org/fox/ttrss-mailer-smtp), but can't figure out how to pass through the additional variables (TTRSS_SMTP_HOST, etc.) to the config.php file.

I've tried passing them through my docker-compose file as environment variables, as well as manually mounting/editing the config.php file myself (which is just overwritten with the variables from my compose file upon restart/update/rebuild).

**Deployment method**
 - docker-compose
 - Latest

**Deployment environment**
 - OS: Ubuntu Server 20.04
 - Edge (Chromium)

**To Reproduce**
1. Install SMTP plugin and enable it
2. Add additional configuration variables to docker-compose and/or config.php file
3. Restart the container
4. Note that the variables did not stick when the application starts

**Expected behavior**
TT-RSS should accept the variables to successfully send mail via SMTP.

**Comment by HenryQW** [comment]
The ends should be passed into the container, if you set `TTRSS_SMTP_HOST =smtp.email.com`, and bash into the container and check what's in env, it should be there.

**Comment by TonyRL** [comment]
Only environment variables explicitly set in `src/initialize.php` are passed onto TTRSS. Same issue as https://github.com/HenryQW/Awesome-TTRSS/issues/330.

Workaround:
Mount `initialize.php` to somewhere and add `$config['SMTP_SERVER'] = env('SMTP_SERVER');` etc in it.

---

> 
> I've tried passing them through my docker-compose file as environment variables, as well as manually mounting/editing the config.php file myself (which is just overwritten with the variables from my compose file upon restart/update/rebuild).

On every restart of the container, `initialize.php` will overwrite the existing `config.php`, pick up those environment variables that are passed into the container **AND** specified in `initialize.php`. 

If you try to install any plugins that requires additional environment variables that does not appears in `initialize.php`, it won't work until you did a workaround or wait until those are added into `initialize.php`.

**Comment by HenryQW** [comment]
Hi if you can submit a PR on this, I'm too busy to work on this.
