### ISSUE TITLE
请教一下crontab的使用方式

### ISSUE THREAD

**Issue by penjune** [HenryQW/Awesome-TTRSS#34]
请问要如何使用crontab加速ttrss的更新?
还请作者指导

另外我想询问ttrss有提供card view 及 magazine view 的排版么(主题也行
以下提供feedly的截图

card view
![image](https://i.imgur.com/116IblQ.png)

magazine view
![image](https://i.imgur.com/iGJQo7f.png)

**Comment by HenryQW** [comment]
https://git.tt-rss.org/fox/tt-rss/wiki/UpdatingFeeds

据我所知没有。

**Comment by penjune** [comment]
找了一下资料
self-hosted的服务主要有ttrss, freshrss, newsblur
目前只有newsblur支持card view 不过也是最厚重的服务
要求性能较好的机器
