### ISSUE TITLE
[BUG]docker for windows部署报错

### ISSUE THREAD

**Issue by goukey** [HenryQW/Awesome-TTRSS#340]
用docker for windows直接用docker-compose部署，结果postgres容器无限重启。
经观察，应该是-v的时候容器内提示用户没有权限，请问如何解决
![微信截图_20211118130845](https://user-images.githubusercontent.com/44106685/142355791-4dd8367b-9c71-4f11-acb2-245dfd70c77f.png)

ps:用Ubuntu可以正常部署，所以应该是windows专属bug

**Comment by HenryQW** [comment]
不是win用户 不清楚 谷歌吧

**Comment by goukey** [comment]
........................
