### ISSUE TITLE
自动更新后fever插件不能工作了

### ISSUE THREAD

**Issue by yche2990** [HenryQW/Awesome-TTRSS#341]
<html>
<body>

E_COMPILE_ERROR (64) | plugins/fever/fever_api.php:113 | Declaration of FeverAPI::before($method) must be compatible with Handler::before(string $method): bool  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /plugins/fever/?api User agent: Reeder/5001.29.01 CFNetwork/1325.0.1 Darwin/21.1.0 |   | 3:48
-- | -- | -- | -- | --
E_COMPILE_ERROR (64) | plugins/fever/fever_api.php:113 | Declaration of FeverAPI::before($method) must be compatible with Handler::before(string $method): bool  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /plugins/fever/?api User agent: Reeder/5001.29.01 CFNetwork/1325.0.1 Darwin/21.1.0 |   | 3:48
E_COMPILE_ERROR (64) | plugins/fever/fever_api.php:113 | Declaration of FeverAPI::before($method) must be compatible with Handler::before(string $method): bool  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /plugins/fever/?api User agent: Reeder/5001.29.01 CFNetwork/1325.0.1 Darwin/21.1.0 |   | 3:46
E_USER_WARNING (512) | classes/pluginhost.php:456 | Plugin feediron has caused a PHP fatal error so it won't be loaded again in this session. 1. classes/pluginhost.php(456): user_error(Plugin feediron has caused a PHP fatal error so it won't be loaded again in this session., 512) 2. classes/pluginhost.php(422): load(af_comics,af_psql_trgm,af_readability,af_redditimgur,af_youtube_embed,af_zz_vidmute,api_feedreader,api_newsplus,auth_internal,auth_remote,auto_assign_labels,bookmarklets,cache_starred_images,feediron,fever,hotkeys_force_top,hotkeys_noscroll,hotkeys_swap_jk..., 1, 2, 1) 3. classes/pref/prefs.php(804): load_all(1, 2, 1) 4. backend.php(136): getPluginsList()  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 | yche2990 | 3:46
E_COMPILE_ERROR (64) | plugins.local/feediron/init.php:54 | Declaration of Feediron::csrf_ignore($method) must be compatible with IHandler::csrf_ignore(string $method): bool  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 | yche2990 | 3:45
E_USER_WARNING (512) | classes/pluginhost.php:456 | Plugin feediron has caused a PHP fatal error so it won't be loaded again in this session. 1. classes/pluginhost.php(456): user_error(Plugin feediron has caused a PHP fatal error so it won't be loaded again in this session., 512) 2. classes/pluginhost.php(422): load(af_comics,af_psql_trgm,af_readability,af_redditimgur,af_youtube_embed,af_zz_vidmute,api_feedreader,api_newsplus,auth_internal,auth_remote,auto_assign_labels,bookmarklets,cache_starred_images,feediron,fever,hotkeys_force_top,hotkeys_noscroll,hotkeys_swap_jk..., 1, 2, 1) 3. classes/pref/prefs.php(804): load_all(1, 2, 1) 4. backend.php(136): getPluginsList()  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 | yche2990 | 3:45
E_COMPILE_ERROR (64) | plugins.local/feediron/init.php:54 | Declaration of Feediron::csrf_ignore($method) must be compatible with IHandler::csrf_ignore(string $method): bool  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 | yche2990 | 3:44
E_COMPILE_ERROR (64) | plugins/fever/fever_api.php:113 | Declaration of FeverAPI::before($method) must be compatible with Handler::before(string $method): bool  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /plugins/fever/?api User agent: Reeder/5001.29.01 CFNetwork/1325.0.1 Darwin/21.1.0 |   | 3:43
E_COMPILE_ERROR (64) | plugins/fever/fever_api.php:113 | Declaration of FeverAPI::before($method) must be compatible with Handler::before(string $method): bool  Real IP: 192.168.1.1 Forwarded For: 192.168.1.1 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /plugins/fever/?api User agent: Reeder/5001.29.01 CFNetwork/1325.0.1 Darwin/21.1.0

</body>
</html>

**Comment by lylunula** [comment]
+1

**Comment by lylunula** [comment]
我是全部插件都不行了，提示Error while loading plugins list: RequestError: Unable to load backend.php status: 500.

**Comment by nathankellenicki** [comment]
+1 here. Image needs to be rebuild. Thanks!

**Comment by HenryQW** [comment]
I've triggered the rebuild. Thanks for the heads up!
