### ISSUE TITLE
[BUG]订阅rsshub豆瓣广播每次更新时会拉取重复文章

### ISSUE THREAD

**Issue by Liu-Guang** [HenryQW/Awesome-TTRSS#343]
**Bug 描述**
订阅rsshub豆瓣个人广播，例如：http://rsshub.app/douban/people/62759792/status
每次更新时会拉取重复的文章，导致现在已有几千条重复文章
仅有豆瓣广播出现此情况

**你谷歌/百度了吗？**
无相关结果

**部署方法**
 - docker-compose
 - 使用的镜像版本：latest

**部署环境**
 - 操作系统: Centos 8.2.2004

**错误日志**
无错误日志

**Comment by HenryQW** [comment]
源相关问题建议去 rsshub 提 issue。
