### ISSUE TITLE
改了admin密码后登录不了，有解决方案吗[BUG]

### ISSUE THREAD

**Issue by zfy68** [HenryQW/Awesome-TTRSS#344]
**Bug 描述**
简洁明了地描述这个 bug。

**你谷歌/百度了吗？**
请善用搜索引擎。

**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]

**部署环境**
 - 操作系统: [如 Ubuntu 18.04]
 - 浏览器: [如 chrome, safari]

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
请善用搜索引擎。

执行sql：
```sql 
UPDATE ttrss_users SET pwd_hash = 'SHA1:5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8' , salt = '' WHERE login = 'admin';
```

https://community.tt-rss.org/t/how-to-change-my-password/963
