### ISSUE TITLE
[BUG]fever无法使用

### ISSUE THREAD

**Issue by wklesss** [HenryQW/Awesome-TTRSS#350]
**Bug 描述**
使用fluent reader中的fever连接ttrss报错，无法连接。
ttrss警告E_USER_WARNING (512)

**你谷歌/百度了吗？**
请善用搜索引擎。

**部署方法**
 docker-compose
 latest

**部署环境**
 群晖

**截屏**

![image](https://user-images.githubusercontent.com/29318238/147252710-1e928eb8-e9bf-4064-b241-d087abdfbfe7.png)

![image](https://user-images.githubusercontent.com/29318238/147252414-36de4226-e1f8-4895-8fb8-f22a02882b58.png)

**Comment by wklesss** [comment]
是否因为域名是通过ipv6解析导致的

**Comment by HenryQW** [comment]
没试过 ipv6，不清楚是否是这个问题

**Comment by wklesss** [comment]
fever 升级后可以正常使用了
