### ISSUE TITLE
libpng warning

### ISSUE THREAD

**Issue by dvoijen** [HenryQW/Awesome-TTRSS#361]
- ## _What_ is the issue?

imagecreatefromstring(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image

- ## _What_ is your OS and its version?

- ## _What_ is your installation method?

- ### Docker

  - Did you build your own dockerfile (paste it here if possible)?

- ### Others

- ## _Are_ there any error logs?

imagecreatefromstring(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image

- ## _How_ can the issue be replicated?

It happens everytime it fetches new feeds

**Comment by dvoijen** [comment]
Full error:
imagecreatefromstring(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image
1. include/colors.php(361): imagecreatefromstring(�PNG

**Comment by HenryQW** [comment]
It looks like a source code issue, which cannot be fixed by this repo. Please report it to the TTRSS forum.

**Comment by dvoijen** [comment]
Henry,

Ok, took it to the tt-rss community.
