### ISSUE TITLE
On power loss,TTRss seems to reset to zero and DB+settings are lost [BUG]

### ISSUE THREAD

**Issue by aelg305** [HenryQW/Awesome-TTRSS#362]
**Describe the bug**
On power loss on the host machine with docker running, the database as well as the settings seems to be deleted and I have to set everything up (change the default password, feeds, etc)

**Have you googled?**
I googled the problem and it seems to be the stack within docker, but unsure what it is
I did turn off the watchtower option to ensure is not an update or upgrade.

**Deployment method**
 - Docker-compose
 - Version of the image used [e.g. latest]

**Deployment environment**
 - OS: Windows 10
 - Browser: chrome
-Im starting the docker engine using the windows "task scheduler" with the setting to run automatically without user interaction

**To Reproduce**
1. Disconnect computer from power
2. Connect power
3. Start computer

**Expected behavior**
A will think the machine would restart and the docker engine restart with all the settings saved

**Screenshots**
NA

**Error logs**
NA

**Additional context**
I have restarted the machine and it seems to maintain the settings. It's only on power loss.

**Comment by HenryQW** [comment]
I'm not sure this is something related to this repo, ttrss settings are saved in your Postgres, which by default should be stored in a volume on your machine somewhere defined by the compose file. If there is a power cut, Postgres has an extremely slim chance to corrupt and lose all your data.

**Comment by aelg305** [comment]
Does the compose file creates the volume as needed? I been reading a d it seems it does, but I'm unable to see it within the volumen option (image attached)
![Screenshot_20220106-151138_Home Assistant](https://user-images.githubusercontent.com/4448006/148445130-06b9389c-ad4a-49af-8eca-edc2cf4eebcf.jpg)

**Comment by aelg305** [comment]
Container details appear to have the volume listed...am I missing something?
![Uploading Screenshot_20220106-151309_Home Assistant.jpg…]()

**Comment by HenryQW** [comment]
Looks right to me, check what's in `/postgres/data` on the host.

**Comment by aelg305** [comment]
I have Docker for windows (running W10), my understanding is that the host file is located under: \\wsl$\

2 folders under that location:
-Docker-desktop & docker-desktop-data
however, no folder shown as /postgress/data..... unless is nested under one of the folders? (photo below showing tree)

![image](https://user-images.githubusercontent.com/4448006/149349222-05a79113-033a-4925-a76c-976566c198c5.png)
![image](https://user-images.githubusercontent.com/4448006/149349279-506f7b61-02c9-4018-b305-ea92b5f58576.png)

**Comment by aelg305** [comment]
Question, should I have a Volume /postgres/data ?? or should it be a folder under \\wsl$\??

**Comment by HenryQW** [comment]
Sorry I'm not a windows user, but what the volume /postgres/data for is to persist your database on your host machine. So it has to be physically stored somewhere on your windows or inside WSL.

**Comment by aelg305** [comment]
I think I fix it - no errors or issues so far.

It has to do with the syntax.
Within the docker compose file, I changed the volume as follow: `./data:/var/lib/postgresql/data\`

FYI:
Im using Win10 + Docker Desktop for Windows + Portainer to control the stacks/compose, etc. 
Code ended looking like tike this:

```
#
  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=mypass1234 # feel free to change the password
    volumes:
      - ./data:/var/lib/postgresql/data\   # To make it work with Win10 + Docker for Win + Portainer
    networks:
      - database_only
    restart: always

```
