### ISSUE TITLE
[BUG]加载缓慢，选择订阅源后一直转圈很长时间才能显示

### ISSUE THREAD

**Issue by JamYiz** [HenryQW/Awesome-TTRSS#369]
**Bug 描述**
加载缓慢，选择订阅源后一直转圈很长时间才能显示

**你谷歌/百度了吗？**
请善用搜索引擎。
是
**部署方法**
 - docker-compose
 - latest [如 latest, nightly, 19.8]

**部署环境**
 - 操作系统: CentOS 8.3.2011 x86_64
 - 浏览器: Firefox|Vivaldi|Edge

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '订阅'
2. 一直转圈，加载缓慢

**预期结果**
较快的显示

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。
E_WARNING (2) | classes/feeds.php:1679 | Trying to access array offset on value of type bool 1. classes/feeds.php(1679): ttrss_error_handler(Trying to access array offset on value of type bool, classes/feeds.php) 2. classes/api.php(678): _get_headlines([{"feed":"105","limit":200,"view_mode":"unread","cat_view":false,"search":"","override_order":"updated","offset":0,"since_id":0,"include_children":false,"check_first_id":0,"skip_first_id_check":true}) 3. classes/api.php(221): _api_get_headlines(105, , unread, updated, ) 4. api/index.php(55): getHeadlines()  Real IP: 116.169.5.224 Forwarded For: 116.169.5.224 Remote IP: 192.168.48.1 Request URI: /api/ User agent: okhttp/3.14.9 | admin | 15:20
-- | -- | -- | -- | --
E_WARNING (2) | classes/feeds.php:1678 | Trying to access array offset on value of type bool 1. classes/feeds.php(1678): ttrss_error_handler(Trying to access array offset on value of type bool, classes/feeds.php) 2. classes/api.php(678): _get_headlines([{"feed":"105","limit":200,"view_mode":"unread","cat_view":false,"search":"","override_order":"updated","offset":0,"since_id":0,"include_children":false,"check_first_id":0,"skip_first_id_check":true}) 3. classes/api.php(221): _api_get_headlines(105, , unread, updated, ) 4. api/index.php(55): getHeadlines()  Real IP: 116.169.5.224 Forwarded For: 116.169.5.224 Remote IP: 192.168.48.1 Request URI: /api/ User agent: okhttp/3.14.9
<html>
<body>

E_USER_WARNING (512) | backend.php:158 | Refusing to invoke method getallcounters of handler rpc with invalid CSRF token. 1. backend.php(158): user_error(Refusing to invoke method getallcounters of handler rpc with invalid CSRF token.)  Real IP: 182.135.46.250 Forwarded For: 182.135.46.250 Remote IP: 192.168.48.1 Request URI: /backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.137 Safari/537.36
-- | -- | --

</body>
</html>
**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
invalid CSRF token? 尝试换个浏览器或者关闭浏览器扩展试试看

**Comment by JamYiz** [comment]
> 试

重建了下有所好转了，请问大佬是不是类别点击都会自动更新，每次都会等很久
