### ISSUE TITLE
Last error: Requested URL failed extended validation. 更新docker后出现错误

### ISSUE THREAD

**Issue by fucao** [HenryQW/Awesome-TTRSS#374]
**Bug 描述**
Last error: Requested URL failed extended validation.

**你谷歌/百度了吗？**
用了

**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本 ：2022年2月9号更新

**部署环境**
 - 操作系统: 群晖
 - 浏览器: chrome

**复现步骤**
复现该 bug 的详细步骤
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 1281:80
    environment:
      - SELF_URL_PATH=https://XXXXXXX:1280/ # please change to your own domain
      - DB_PASS=XXXX # use the same password defined in `database.postgres`
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=XXXXX # feel free to change the password
    volumes:
      - /volume1/docker/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true

**预期结果**

**截屏**
![image](https://user-images.githubusercontent.com/15061002/153107898-42f66277-8861-4be9-8897-47266ba4bc74.png)

**错误日志**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///h:/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///h:/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ttrss |   |  
-- | -- | --
date | stream | content
2022/2/9 2:07 | stdout | [02:07:49/29] Received SIGCHLD,   1 active tasks left.
2022/2/9 2:07 | stdout | [02:07:49/29] Child process with PID 284 reaped.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Purged 0 orphaned posts.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Removing old error log entries...
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Removed 0 old lock files.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Expired cache/upload: removed 0 files.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Expired cache/images: removed 0 files.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Expired cache/feeds: removed 0 files.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Expired cache/export: removed 0 files.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] All done.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Sending digests,   batch of max 15 users, headline limit = 1000
2022/2/9 2:07 | stdout | [02:07:48/285] Running housekeeping tasks for user 1...
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] Processed 16   feeds in 1.3463 (sec), 0.0841 (sec/feed avg)
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0789 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/320] Lock: update_daemon-feed-102.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] => 娓歌祫鐑偣   (ID: 102, U: admin [1]), last updated: 2022-02-09 01:52:33
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E6%B8%B8%E8%B5%84%E7%83%AD%E7%82%B9
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0812 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/318] Lock: update_daemon-feed-74.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] => 娌抽┈鐢靛奖   (ID: 74, U: admin [1]), last updated: 2022-02-09 01:52:33
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr/%E6%B2%B3%E9%A9%AC%E7%94%B5%E5%BD%B1
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0761 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/316] Lock: update_daemon-feed-76.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] => 鐢靛奖閾哄瓙   (ID: 76, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E7%94%B5%E5%BD%B1%E9%93%BA%E5%AD%90
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0805 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/314] Lock: update_daemon-feed-32.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] => 鍖楀ぇ娓呭崕璁插骇   (ID: 32, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E5%8C%97%E5%A4%A7%E6%B8%85%E5%8D%8E%E8%AE%B2%E5%BA%A7
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0779 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/312] Lock: update_daemon-feed-157.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] => 缁忕涔嬪   (ID: 157, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E7%BB%8F%E7%AE%A1%E4%B9%8B%E5%AE%B6
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0782 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/310] Lock: update_daemon-feed-29.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] =>   瀛︿細瀛︽湳浜ゆ祦涓庡鍔?(ID: 29, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E5%AD%A6%E4%BC%9A%E5%AD%A6%E6%9C%AF%E4%BA%A4%E6%B5%81%E4%B8%8E%E5%A5%96%E5%8A%B1
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0784 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/308] Lock: update_daemon-feed-68.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] =>   璁￠箯鏂拌兘婧?(ID: 68, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E8%AE%A1%E9%B9%8F%E6%96%B0%E8%83%BD%E6%BA%90
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0840 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/306] Lock: update_daemon-feed-65.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] => 姣忔棩椋庣數   (ID: 65, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:48/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E6%AF%8F%E6%97%A5%E9%A3%8E%E7%94%B5
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/285] <= 0.0944 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:48/304] Lock: update_daemon-feed-90.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] =>   涓栫晫缁忔祹璁哄潧鎶ュ憡 (ID: 90, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:47/285] Base feed: http://192.168.50.50:1200/weforum/report
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] <= 0.0783 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/302] Lock: update_daemon-feed-63.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] => 鍥藉鑳芥簮灞€   (ID: 63, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:47/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E5%9B%BD%E5%AE%B6%E8%83%BD%E6%BA%90%E5%B1%80
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] <= 0.0806 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/300] Lock: update_daemon-feed-7.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] =>   鏂颁含鎶ヨ瘎璁?(ID: 7, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:47/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E6%96%B0%E4%BA%AC%E6%8A%A5%E8%AF%84%E8%AE%BA
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] <= 0.0849 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/298] Lock: update_daemon-feed-31.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] => 绉戠爺骞茶揣   (ID: 31, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:47/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E7%A7%91%E7%A0%94%E5%B9%B2%E8%B4%A7
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] <= 0.0787 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/296] Lock: update_daemon-feed-126.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] =>   椋庤兘璧勬簮涓撲笟缁?(ID: 126, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:47/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/darhcenssr?filter_author=%E9%A3%8E%E8%83%BD%E8%B5%84%E6%BA%90%E4%B8%93%E4%B8%9A%E7%BB%84
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] <= 0.0787 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/294] Lock: update_daemon-feed-154.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] => 榛戞礊璧勬簮绗旇   (ID: 154, U: admin [1]), last updated: 2022-02-09 01:52:32
2022/2/9 2:07 | stdout | [02:07:47/285] Base feed:   http://192.168.50.50:1200/wechat/tgchannel/tieliu
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] <= 0.0777 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/292] Lock: update_daemon-feed-89.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] =>   涓婃捣璇佸埜浜ゆ槗鎵€ - 涓婂競鍏徃淇℃伅 - 鏈€鏂板叕鍛?(ID: 89, U: admin [1]), last updated:   2022-02-09 01:52:31
2022/2/9 2:07 | stdout | [02:07:47/285] Base feed: http://192.168.50.50:1200/sse/disclosure
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] !! Last error: Requested URL failed extended validation.
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] <= 0.0795 (sec) exit code: 100
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/290] Lock: update_daemon-feed-70.lock
  |   |  
2022/2/9 2:07 | stdout | [02:07:47/285] =>   椋庣數宄拌瀵?(ID: 70, U: admin [1]), last updated: 2022-02-09 01:52:31

</body>

</html>

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
估计是源地址的问题
