### ISSUE TITLE
[BUG] cookie_lifetime 没有正确的设置成 SESSION_COOKIE_LIFETIME

### ISSUE THREAD

**Issue by uJZk** [HenryQW/Awesome-TTRSS#381]
**Bug 描述**
cookie_lifetime 没有正确设置成 SESSION_COOKIE_LIFETIME。

**你谷歌/百度了吗？**
没有相关结果。

**部署方法**
 - docker-compose
 - latest

**部署环境**
 - debian 11
 - chrome

**预期结果**
cookie_lifetime 正确设置成 SESSION_COOKIE_LIFETIME。

**截屏**
![image](https://user-images.githubusercontent.com/34388941/159564621-0993e027-360b-46af-8e38-11ad5927c51f.png)
![image](https://user-images.githubusercontent.com/34388941/159564724-9112cd83-9d3e-483b-96fb-15b6f5023f3d.png)

**Comment by HenryQW** [comment]
https://community.tt-rss.org/t/session-cookie-lifetime-is-always-0/3912
