### ISSUE TITLE
[BUG] /var/www is owned by someone else

### ISSUE THREAD

**Issue by tensor5g** [HenryQW/Awesome-TTRSS#387]
**Describe the bug**
After going from latest latest-2022-04-04 to latest-2022-04-19 I get the below error
```
fatal: unsafe repository ('/var/www' is owned by someone else)

To add an exception for this directory, call:

	git config --global --add safe.directory /var/www
```
The container does not work at all when this error is present. Even creating a container with no volumes generates the same error. Downgrading to latest-2022-04-04 resolves the error. 

**Deployment method**
 - docker and docker-compose tested

**Deployment environment**
 - OS: Ubuntu 20.04 and Windows 10 tested

**To Reproduce**
1. Pull latest-2022-04-19 image and view logs

**Comment by abelfodil** [comment]
same issue

**Comment by ptsa** [comment]
同样错误

**Comment by Roufoye** [comment]
出现了同样错误，目前容器无限重启中

**Comment by ResidualBlood** [comment]
same issue

**Comment by dvoijen** [comment]
same here

**Comment by MackXue** [comment]
刚刚更新，遇到了同样的错误

**Comment by bolitao** [comment]
Same issue after Watchtower's auto-updating.
I changed `wangqiru/ttrss` image tag to `latest-2022-04-04` to avoid this temporarily.

**Comment by LindenXing** [comment]
same issue

**Comment by hyyin** [comment]
any solution on this? seems related to https://github.blog/2022-04-12-git-security-vulnerability-announced/. But don't know how to handle this in container

**Comment by tensor5g** [comment]
@hyyin this problem was resolved for me after the latest update. Try pulling the latest-2022-04-19 image again
