### ISSUE TITLE
[BUG] the proxy_redirect will not work

### ISSUE THREAD

**Issue by lockywolf** [HenryQW/Awesome-TTRSS#389]
**Describe the bug**
The official documentation suggests using the following method:
```
        rewrite /ttrss/(.*) /$1 break;
        proxy_redirect https://$http_host https://$http_host/ttrss;
        proxy_pass http://ttrssdev;
```
This way, TTRSS_SELF_URL_PATH needs to be set to myhost/, because the first nginx will remove the /ttrss/ part, and tt-rss will not start, complaining about URL mismatch.

However, this will make many Javascript requests invalid, such as the feed debugger, because the JS code is not subject to `proxy_redirect`, and will still point to /mydomain/backend.php, whereas the actual url would be /mydomain/ttrss/backend.php

This is because in php code, there is the following line:
```
$self_url_path = $proto . '://' . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
```
This `REQUEST_URI` will be without `/ttrss/` removed by "rewrite", so the two URLs will not match.

So what actually needs to be done - "rewrite" and "proxy_redirect" should _not_ be used. Instead, internal nginx should remove the prefix in order to find the correct file, but set the  fcgi_param REQUEST_URI accordingly, to  the original value.

The prefix may be done via a custom header, I guess.

**Have you googled?**
Yes.

**Deployment method**
 - docker-compose
 - latest

**Deployment environment**
 - OS: Slackware 15
 - Browser: chrome

**Comment by HenryQW** [comment]
I personally don't use subpath, the solution in the doc was proposed by the community. Do you have an alternative for this?

**Comment by lockywolf** [comment]
I don't know. But the method described in the how-to is definitely not correct, so I would suggest removing it, and adding a question to the audience.

I am not an nginx expert, but it should be possible, I guess, to make nginx set some arbitrary header, say, `X-AwesoneTTRSS: prefix`, (tell the user to set this header) and then remove it from the url, with rewriting (inside docker), but keeping the fcgi_param REQUEST_URI as-is.

**Comment by HenryQW** [comment]
Thanks. I have removed the relevant sections in the doc.

I ditched nginx for caddy a long time ago, made my life much easier.
