### ISSUE TITLE
[BUG]部署之后页面打不开，而且端口显示未使用

### ISSUE THREAD

**Issue by SurpriseLon** [HenryQW/Awesome-TTRSS#390]
**Bug 描述**
部署之后页面打不开，而且端口显示未使用

**你谷歌/百度了吗？**
谷当然，只是没找到解决办法

**部署方法**
 - docker-compose
 - 使用的镜像版本:latest

**部署环境**
 - 操作系统: Debian 11
 - 浏览器: chrome

**复现步骤**
docker-compose up -d
Creating network "wwwroot_public_access" with the default driver
Creating network "wwwroot_service_only" with the default driver
Creating network "wwwroot_database_only" with the default driver
Creating mercury  ... done
Creating postgres ... done
Creating opencc   ... done
Creating ttrss    ... done
http://ip:181/
HTTP ERROR 503

**错误日志**
You might want to check tt-rss wiki or the forums for more information.
Please search the forums before creating new topic for your question.
PHP Warning:  Undefined array key 1 in /var/www/classes/config.php on line 358
PHP Warning:  Undefined array key 2 in /var/www/classes/config.php on line 358
PHP Warning:  Unable to determine version: Git error [RC=128]: fatal: unsafe repository ('/var/www' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /var/www in /var/www/classes/config.php on line 317
Please fix errors indicated by the following messages:

 * Image cache is not writable (chmod -R 777 cache/images)
 * Upload cache is not writable (chmod -R 777 cache/upload)
 * Data export cache is not writable (chmod -R 777 cache/export)
 * ICONS_DIR defined in config.php is not writable (chmod -R 777 feed-icons).

 * LOCK_DIRECTORY is not writable (chmod -R 777 lock).

**Comment by HenryQW** [comment]
这玩意十九天就修复了，你确定是最新的镜像吗？

**Comment by SurpriseLon** [comment]
> 这玩意十九天前就修复了[40e9d04](https://github.com/HenryQW/Awesome-TTRSS/commit/40e9d04bb259c265a8c2ef5f97ffbc1317b91ffa) 你确定是最新的镜像吗？

我是按照[docker-compose.yml](https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml) 默认的部署的

**Comment by TT2TER** [comment]
Please fix errors indicated by the following messages:



 * ICONS_DIR defined in config.php is not writable (chmod -R 777 feed-icons).





You might want to check tt-rss wiki or the forums for more information.

Please search the forums before creating new topic for your question.
我也遇到了同样的问题

**Comment by TT2TER** [comment]
解决了，是Linux系统用户组的问题

**Comment by ifeichuan** [comment]
> 解决了，是Linux系统用户组的问题

具体是啥问题啊 大哥你咋解决的

**Comment by TT2TER** [comment]
> > 解决了，是Linux系统用户组的问题
> 
> 具体是啥问题啊 大哥你咋解决的

https://blog.1314171.xyz/post/220809docker-rss博客里描述了我的问题和解决方法，当然最后我卡在了别的地方，放弃了ttrss
