### ISSUE TITLE
[BUG]wallabag插件没办法勾选

### ISSUE THREAD

**Issue by wrhsd1** [HenryQW/Awesome-TTRSS#392]
wallabag插件没办法勾选啊大佬，其他插件都是正常勾选。请问这是什么原因
[![O0FlV0.png](https://s1.ax1x.com/2022/05/12/O0FlV0.png)](https://imgtu.com/i/O0FlV0)

**Comment by HenryQW** [comment]
不清楚，没在用

**Comment by chinyajie** [comment]
我也是这个问题，没办法勾选。可以看到 plugins.local 目录下有 wallabag_v2，但是配置里面选不中

**Comment by HenryQW** [comment]
可能是这个插件自己的问题，没有遵从某个 ttrss 要求的语法，所以没办法勾选

**Comment by huangwb8** [comment]
所以这个问题还是没有解决？
