### ISSUE TITLE
[BUG]（含修复）options_per_feed插件无法使用

### ISSUE THREAD

**Issue by hacklu** [HenryQW/Awesome-TTRSS#394]
**Bug 描述**
options_per_feed插件无效

调试后发现该插件使用了预设常量“SELF_USER_AGENT“，而ttrss在2021年8月的一次[提交](https://git.tt-rss.org/fox/tt-rss.git/commit/?id=2c931df77ccba5e76bc1865584e870219596ff69)中删除了该常量，插件没有及时进行更新。

修复pull request已发插件原作者，等待原作者接受。

着急使用的可以先用[这里](https://github.com/hacklu/options_per_feed/tree/bug_fix)

**Comment by kangsbk** [comment]
现在插件一直没更新,试了可以直接改/var/www/plugins.local/options_per_feed里面的文件,重启就可用了
