### ISSUE TITLE
无法从指定的网址下载:; 60 SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by zhl111** [HenryQW/Awesome-TTRSS#396]
用vercel一键搭建了rsshub，显示成功了。然后我绑定了自己的域名，以为可以工作了，但发现乐观了。说我证书过期了，我该如何修正？作为没有编程能力的选手，没有一点头绪，望大神们赐教

**Comment by HenryQW** [comment]
原来的证书哪里来的，去更新一下。
