### ISSUE TITLE
支持观看防盗链图片/视频

### ISSUE THREAD

**Issue by huangwb8** [HenryQW/Awesome-TTRSS#399]
**该功能能够解决的问题**
支持观看防盗链图片/视频

**形容理想的解决方案**
今天看到RSShub的一个[pull request](https://github.com/DIYgod/RSSHub/pull/9984/commits/69439ed1fac24c6f6c51e1ff17ebd1e2be9787e0)，其中有提到：RSSHub 里的图片 / 视频地址都是源站地址，部分有防盗链，所以 RSSHub 给图片加了 `referrerpolicy="no-referrer"` 属性来防止跨域问题，但部分 RSS 服务会自作主张去掉这个属性，如 Feedly、Inoreader，在它们的网页端图片会触发跨域加载不出来。同时，视频目前没有类似的属性，因此大部分阅读器都无法通过防盗链检查。下面是一些解决方案：
1.  使用不发送 Referer 的阅读器，如 [Inoreader 网页版](https://www.inoreader.com/)配合[禁用 Referer 的 user script](https://greasyfork.org/zh-CN/scripts/376884)、[RSS to Telegram Bot](https://github.com/Rongronggg9/RSS-to-Telegram-Bot) 等。如果你的阅读器能够绕过防盗链成功播放内嵌视频，那么它就是不发送 Referer 的，请考虑添加到文档里帮助更多的人。
2. ...
如果TTRSS可以支持这个功能就好了

**Comment by HenryQW** [comment]
这里只管部署不管功能。
