### ISSUE TITLE
Would you be able to add the env variables for email smtp?

### ISSUE THREAD

**Issue by peppy6582** [HenryQW/Awesome-TTRSS#403]
Would you please add the env variables for email?  I would appreciate it greatly.  Thanks

**Comment by TonyRL** [comment]
I think it's there.
https://github.com/HenryQW/Awesome-TTRSS/blob/abe9d2b57d0c5410681c36f8039da0d33831b253/src/initialize.php#L54-L59

**Comment by HenryQW** [comment]
#339

**Comment by peppy6582** [comment]
You guys are awesome.
