### ISSUE TITLE
[BUG]mailer_smtp插件怎么使用？？？

### ISSUE THREAD

**Issue by unyielding2013** [HenryQW/Awesome-TTRSS#408]
RSS更新后通过发送邮件提醒。

**Comment by YehowahLiu** [comment]
部署完毕此镜像后，安装并开启mailer_smtp插件会提示：`使用全局配置启用系统插件`，但是参照wiki使用`ENABLE_PLUGINS`环境变量并无作用，预计为此容器内未打包插件所致

所以必须在容器构建时打包相应插件（修改`Dockerfile`），然后使用环境变量将其启用？

**Comment by HenryQW** [comment]
> 部署完毕此镜像后，安装并开启mailer_smtp插件会提示：`使用全局配置启用系统插件`，但是参照wiki使用`ENABLE_PLUGINS`环境变量并无作用，预计为此容器内未打包插件所致
> 
> 所以必须在容器构建时打包相应插件（修改`Dockerfile`），然后使用环境变量将其启用？

没错。

**Comment by AngusWG** [comment]
请问一下配置成功了吗？

- 我安装 mailer_smtp 后 
- 环境变量设置 - TTRSS_PLUGINS=mailer_smtp
- 在plugins页面中看
  - 并没有enable mailer_smtp

![image](https://github.com/user-attachments/assets/1ec2db1e-4d6b-4e7c-97d3-fa64201e5ab1)


邮件测试报错：

```
Error sending mail: Unknown error while sending mail. Hooks tried: 0.
1. classes/Mailer.php(59): user_error(Error sending mail: Unknown error while sending mail. Hooks tried: 0.)
2. classes/Mailer.php(51): set_error(Unknown error while sending mail. Hooks tried: 0.)
```
