### ISSUE TITLE
请问在TTRSS里面如何播放视频呢？

### ISSUE THREAD

**Issue by i-iooi-i** [HenryQW/Awesome-TTRSS#409]
![image](https://user-images.githubusercontent.com/1827701/187058807-82d1910c-f9e1-4903-9d18-9450d0a24b8d.png)

使用RSSHUB订阅了一些微博，发现在TTRSS里面是无法播放的，播放进度条 0:00~
起初以为是订阅链接的问题，今天使用FreshRSS测试了一下，在FreshRSS里是可以播放的。

特来求教~😼

**Comment by HenryQW** [comment]
👀那我推荐用FreshRSS，TTRSS破坏性改动实在太多了，工作原因近期都没有精力去适配了。

**Comment by i-iooi-i** [comment]
> 👀那我推荐用FreshRSS，TTRSS破坏性改动实在太多了，工作原因近期都没有精力去适配了。

![image](https://user-images.githubusercontent.com/1827701/187486713-0cede114-218b-4c52-89ff-f8477eb35a6c.png)

感谢大佬回复，问题解决了，在微博订阅源里面添加一个displayVideo判断，然后在TTRSS里面收到的视频就可以播放了。
只是不知道为什么，FreshRSS里面不用添加判断就可以播放。🤣

再次感谢大佬对TTRSS的维护。辛苦啦。💕💕💕
