### ISSUE TITLE
在 Reeder 中添加新订阅源

### ISSUE THREAD

**Issue by essethon** [HenryQW/Awesome-TTRSS#41]
* ## _What_ is the issue?

使用 Reeder 3/4 for iOS/macOS，Fever API 方式连接 ttrss，在 Reeder 中没有添加新订阅源的「➕」按钮。
与之对比，在 Reeder app 中添加 Inoreader 账户，可以在「订阅源列表」的右上角（iOS）或右下角（macOS）看到「➕」号，点击之后可以添加订阅源。

![Snipaste_2019-06-09_09-07-33](https://user-images.githubusercontent.com/8758566/59153826-2f038c80-8a96-11e9-85a3-d0aa05e6b658.png)
![Snipaste_2019-06-09_09-07-54](https://user-images.githubusercontent.com/8758566/59153829-332faa00-8a96-11e9-97c4-306bfc07defd.png)

* ## _What_ is your OS and its version?

Server: Debian 9.7
Client: iOS 12.3.1 and Reeder 3/4、macOS 10.14.5 and Reeder 3

* ## _What_ is your installation method?

* ### Docker

Server: 基于本仓库的 docker-compose, 增加了 jwilder/nginx-proxy 和 jrcs/letsencrypt-nginx-proxy-companion 作为前置代理和自动配置 SSL 证书

  * Did you build your own dockerfile (paste it here if possible)?

* ### Old-fashion way

  * _What_ is your setup? (PHP version, database used, etc.)
    

* ### Others

* ## _Are_ there any error logs?

* ## _How_ can the issue be replicated?

1. 使用本仓库提供的 docker-compose.yml 部署 ttrss 服务
2. 启用 Fever API 并设置 Fever 密码
3. 在 Reeder App 中通过 Fever 登录 ttrss

* ## Other Comments
可能这是 Fever API 本身的限制？
作者自己的帖子 https://tt-rss.org/oldforum/viewtopic.php?t=1981 里似乎也没看到➕按钮（1 楼最后一张图）

**Comment by HenryQW** [comment]
1. Fever 只是模拟插件，不提供全部 Fever 功能。
1. Reeder 本身也不支持通过 Fever 添加新源。

**Comment by SuperNG6** [comment]
原来是这个原因，查了半天
