### ISSUE TITLE
[BUG] 无法订阅 反斗限免RSS

### ISSUE THREAD

**Issue by Beurling** [HenryQW/Awesome-TTRSS#412]
**Bug 描述**
订阅此信息时提示
无法订阅 https://free.apprcn.com/feed/
无法下载订阅源的 URL。
![Snipa_2022-09-26_16-26](https://user-images.githubusercontent.com/48503044/192229726-1254ec5d-73b9-435d-a355-a79beb3f4501.png)

**你谷歌/百度了吗？**
没有找到类似解决方案

**部署方法**
docker-compose
使用的latest的镜像版本

**部署环境**
Docker Desktop Win11

其他RSS软件均能正常订阅，向大神们求助，谢谢！

**Comment by HenryQW** [comment]
该 feed 地址浏览器都打不开

**Comment by Beurling** [comment]
> 打开都是空的，他们应该是关闭了rss输出

![Snipaste_2022-10-07_08-12-13](https://user-images.githubusercontent.com/48503044/194440334-2d5d7309-6ae9-4e4c-9b2e-0cbf066b4c8d.png)

我刚试了一下，是有内容的

**Comment by kangbuu** [comment]
emm... 插个眼，rsshub部署到本地，也遇到了这个问题。

**Comment by HenryQW** [comment]
我打开是空白，也订阅不上
<img width="602" alt="image" src="https://user-images.githubusercontent.com/5896343/205447975-18464e05-8d56-41d7-bcb0-3f4ca133f3e0.png">
