### ISSUE TITLE
[Feature] feed43 ssl挂了，希望插件options_per_feed 能整合到docker-compose.yml

### ISSUE THREAD

**Issue by ugukkylbklaom** [HenryQW/Awesome-TTRSS#416]
**该功能能够解决的问题**

feed43的ssl过期 chrome 反馈

This server could not prove that it is node2.feed43.com; its security certificate expired 38 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. 

[https://v2ex.com/t/884333](https://v2ex.com/t/884333)

网友提到

 我只能说我的解决方案：在自建 freshrss 内，找到该 feed43 订阅的高级设置，验证 ssl 证书安全项选“否”，然后清理缓存重载文章，即可绕过证书验证环节，成功订阅。这个方法同样适合将来的新 feed43 订阅。也就是说现在 feed43 网站仍然可以新建自己的源，只不过打不开订阅网址，只要在 freshrss 内验证 ssl 证书安全项选“否”，即可正常订阅浏览。

又有网友提到一个插件

[https://github.com/sergey-dryabzhinsky/options_per_feed](https://github.com/sergey-dryabzhinsky/options_per_feed)

Tiny-Tiny-RSS plugin to setup feed fetch options:

proxy settings per feed
user-agent per feed
ssl certificate verification
This plugin uses php-curl extension. Install it and restart your apache/php-fpm instance.

To install it - put files into options_per_feed directory inside plugins of TTRSS installation.

**形容理想的解决方案**

希望可以把插件options_per_feed 整合到[https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml](https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml)

**其他**
任何有助于解决方案开发的信息，如：某插件已实现相关功能。

**Comment by HenryQW** [comment]
啥意思，不是一直都在吗http://ttrss.henry.wang/#options-per-feed
