### ISSUE TITLE
fever API无法连接

### ISSUE THREAD

**Issue by YangDipper** [HenryQW/Awesome-TTRSS#417]
请大佬赐教：
外网可以登录TTRSS，已开启“允许外部客户端通过API来访问该账户”，并且开启fever插件，设置了密码。但是在fluent reader上复制fever插件上的地址后添加fever API时提示“连接到服务出错，请检查服务配置或网络连接”。

**Comment by Colin-XKL** [comment]
fever插件页面写的应该有问题，我之前遇到过，页面上写的/plugins.local/fever/，访问不通，改成/plugins/fever/ 后就可以访问了

**Comment by YangDipper** [comment]
> fever插件页面写的应该有问题，我之前遇到过，页面上写的/plugins.local/fever/，访问不通，改成/plugins/fever/ 后就可以访问了

非常感谢，改成/plugins/fever/后可以访问了！

**Comment by alpha9534** [comment]
多谢多谢，查了好久，终于找到了
