### ISSUE TITLE
希望RSS记录的题目可以被copy

### ISSUE THREAD

**Issue by huangwb8** [HenryQW/Awesome-TTRSS#419]
如题，TTRSS无法选中并复制RSS推送的文章的标题：

![image-20221128231507853](https://chevereto.hwb0307.com/images/2022/11/28/image-20221128231507853.png)

这个特征应该很容易改进。或者大佬们有什么建议不（比如安装某个plugin实现）？

**Comment by HenryQW** [comment]
只管部署不管功能。
