### ISSUE TITLE
How to enable HTTPS?

### ISSUE THREAD

**Issue by gianvitom** [HenryQW/Awesome-TTRSS#42]
* ## _What_ is the issue?

I would like to have https for TTRSS

* ## _What_ is your OS and its version?

I have installed it on a QNAP nas

* ## _What_ is your installation method?

Created a new app with your Dockerfile

* ### Docker

It's the one in the project

* ### Old-fashion way

  * _What_ is your setup? (PHP version, database used, etc.)

Default from your project. I also tried to change the SELF_URL_PATH to have also https

* ## Other Comments

**Comment by HenryQW** [comment]
HTTPS should be handled using Nginx reverse proxy, not by container itself.

**Comment by gianvitom** [comment]
Ok but modifying the docker compose all the Nginx settings are lost. Is there a way to enable it even with self signed certificate?

**Comment by gianvitom** [comment]
Can you give me some tips or links where I can see how to enable it using your project?

**Comment by HenryQW** [comment]
What do you mean by “Nginx settings are lost”? Nginx is not included and I’m not intended to include it. 

My Nginx config looks like this:

```
upstream ttrssdev {
    server 127.0.0.1:181;
}

server {
    listen 80;
    server_name  ttrssdev.henry.wang;
    return 301 https://ttrssdev.henry.wang$request_uri;
}

server {
    listen 443 ssl;
    gzip on;
    server_name  ttrssdev.henry.wang;

    ssl_certificate /etc/letsencrypt/live/ttrssdev.henry.wang/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ttrssdev.henry.wang/privkey.pem;

    access_log /var/log/nginx/ttrssdev_access.log combined;
    error_log  /var/log/nginx/ttrssdev_error.log;

    location / {
        proxy_redirect off;
        proxy_pass http://ttrssdev;

        proxy_set_header  Host                $http_host;
        proxy_set_header  X-Real-IP           $remote_addr;
        proxy_set_header  X-Forwarded-Ssl     on;
        proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto   $scheme;
        proxy_set_header  X-Frame-Options     SAMEORIGIN;

        client_max_body_size        100m;
        client_body_buffer_size     128k;

        proxy_buffer_size           4k;
        proxy_buffers               4 32k;
        proxy_busy_buffers_size     64k;
        proxy_temp_file_write_size  64k;
    }
}
```

**Comment by gianvitom** [comment]
I mean using the Container station in QNAP when I change a Docker file he will try to restart them and the content in /etc/nginx/nginx.conf is replaced with the default one with only the 80 port.

Ok I will try to add something similar to you, thank you!
