### ISSUE TITLE
[BUG]新手，存档的功能找不着，是版本不对么？求助

### ISSUE THREAD

**Issue by kangbuu** [HenryQW/Awesome-TTRSS#421]
![image](https://user-images.githubusercontent.com/35142285/204702212-88d523c9-a93b-4a66-b211-80a67ef36326.png)

[Tiny Tiny RSS](https://tt-rss.org/) v22.08-ed2cbef (Unsupported) © 2005-2022 [Andrew Dolgov](https://fakecake.org/)

**Comment by HenryQW** [comment]
不知道它的存档是指什么，archive吗？

**Comment by kangbuu** [comment]
![image](https://user-images.githubusercontent.com/35142285/205450864-bcbe498e-3ba7-425c-8672-af9b527b1f76.png)


抱歉，没有描述清楚。

我的诉求就是把喜欢的文章保存了，看到了左侧菜单中的【存档的文章】，但是没有看到存档的功能。

我搜索了很久，在一个人的博客截图里看到存档的功能，位置就在上面提问的那张图那里，是应该有一个【存档文章】的选项的。

哪个博客的图片我找不到了，所以只能用语言描述了~

**Comment by TonyRL** [comment]
https://community.tt-rss.org/t/what-is-the-archive-special-feed-and-how-to-use-it/3243

**Comment by HenryQW** [comment]
加星之后取消订阅的文章会出现在这里，应该没有其他入口。
