### ISSUE TITLE
[BUG]无法创建新的过滤器

### ISSUE THREAD

**Issue by FantasyFish** [HenryQW/Awesome-TTRSS#425]
**Bug 描述**
无法创建新的过滤器

**你谷歌/百度了吗？**
是

**部署方法**
docker-compose
 - 使用的镜像版本：latest

**部署环境**
 - 操作系统:Ubuntu 20.04.2 LTS x86_64(Py3.7.9)
 - 浏览器: Edge

**复现步骤**
复现该 bug 的详细步骤
1. 打开偏好设置
2. 打开过滤器
3. 创建新的过滤器或者点击已有的过滤器
4. 添加新的匹配条件或者更改已有的匹配条件并点击保存
5. 发现错误：没有出现新添加的匹配条件或者已有的匹配条件未发生更改变化

**预期结果**
添加新的条件或者更改已有的条件，应该出现新添加的条件或者已有的条件发生变化更改。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
间歇性发生，四天前不行，三天前可以，昨天和今天又不行了

**Comment by Joselo2022** [comment]
Hola

**Comment by Joselo2022** [comment]
Ah
