### ISSUE TITLE
[BUG]基于awesome-ttrss 的docker-compose.yml 搭建的服务，没法用feedme更新订阅

### ISSUE THREAD

**Issue by Lethe-ideal** [HenryQW/Awesome-TTRSS#428]
**Bug 描述**
基于该项目构建的tinyrss，在feedme 安卓客户端上，没法更新和同步任何订阅，不确定是不是镜像的问题，还是feedme的问题，不过在feed相关的issue里，反映疑似是镜像问题。因为用官方的客户端是可以正常的更新的，所以可能是由于镜像的版本或者上游有问题。

**你谷歌/百度了吗？**
用了。

**部署方法**
 - docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]

**部署环境**
 - 操作系统: [如 Ubuntu 18.04]
 - 浏览器: [如 chrome, safari]

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by egoistinr** [comment]
好像是新版本ttrss有改什麼
seazon/FeedMe#490
裡面有人說把ttrss降版然後關掉更新可以應急

**Comment by lychichem** [comment]
更应该还有的是feedme三个月没更新跟不上ttrss代码了

**Comment by aFlyBird0** [comment]
@Lethe-ideal 我也出现了这样的问题，猜测和 @lychichem 一致。

目前的解决方案（已证明可行）：

在ttrss里开一下fever插件，然后用feedme的fever功能来订阅。

**Comment by AuntYang** [comment]
同样使用awesome-ttrss，我也出现了feedme不可用，只能同步加星内容，其他内容同步不到，有没有使用上游ttrss镜像的，能正常使用吗？

**Comment by Lethe-ideal** [comment]
> @Lethe-ideal 我也出现了这样的问题，猜测和 @lychichem 一致。
> 
> 目前的解决方案（已证明可行）：
> 
> 在ttrss里开一下fever插件，然后用feedme的fever功能来订阅。

感谢

**Comment by Lethe-ideal** [comment]
> 同样使用awesome-ttrss，我也出现了feedme不可用，只能同步加星内容，其他内容同步不到，有没有使用上游ttrss镜像的，能正常使用吗？

去看它们在feedme里下面的那个回复；就是改成fever登陆

**Comment by Lethe-ideal** [comment]
> @Lethe-ideal 我也出现了这样的问题，猜测和 @lychichem 一致。
> 
> 目前的解决方案（已证明可行）：
> 
> 在ttrss里开一下fever插件，然后用feedme的fever功能来订阅。

十分多谢您
