### ISSUE TITLE
同一局域网内网页端正常，但客户端无法访问ttrss

### ISSUE THREAD

**Issue by lylunula** [HenryQW/Awesome-TTRSS#433]
- ## _What_ is the issue?

背景：Nas安装了TTRSS，并跑了DNS来进行内外网转发。

不符合预期的现状是：外网web/客户端Reeder（使用fever API）都可以正常访问，但是局域网内就只能web访问，但是客户端reeder就无法拉取。

猜测原因：个人猜测是由于在内网DNS转成了IP地址，Reeder客户端就无法使用，我也试了win上面的客户端/iOS的Reeder，也是一样的结果。
想请教各位有其他可能吗，以及有什么解决方案吗？

- ## _What_ is your OS and its version?

群晖最新版

- ## _What_ is your installation method?

Docker

- ### Docker

**Comment by HenryQW** [comment]
不是网络专家，我是在群晖上跑的adguard home，用dns rewrite转发外网域名到内网容器。reeder直接用域名，内网网都可以访问。

**Comment by lylunula** [comment]
好的 感谢回答～
