### ISSUE TITLE
[BUG]feed-icons文件夹权限问题？

### ISSUE THREAD

**Issue by ylgod** [HenryQW/Awesome-TTRSS#437]
**Bug 描述**
E_WARNING (2) | classes/rssutils.php:1730 | chmod(): Operation not permitted 1. classes/rssutils.php(1730): chmod(feed-icons/14.ico) 2. classes/rssutils.php(578): update_favicon(https://www.ithome.com/) 3. update.php(232): update_rss_feed()

**你谷歌/百度了吗？**
找了，没有任何相关问题及答案

**部署方法**
 - 在黑群晖DSM7.1里的Docker
 - 使用的镜像版本 latest

**部署环境**
 - 操作系统: 黑群晖DSM7.1
 - 浏览器: 火狐，chrome都一样

**复现步骤**
复现该 bug 的详细步骤
打开TTRSS网页就显示感叹号的标志，http://X/prefs.php?tab=system转至事件日志里就有这样的问题。

**预期结果**
不该有这样的问题啊

**截屏**
上传不了图片，但上述描述已经很清楚了

这应该就是feed-icons文件夹的权限问题，我在docker容器里已经添加/var/www/feed-icons/映射到黑群晖里的文件夹为读写权限，并且给予该文件夹everyone和http的用户读写权限，都不行。

麻烦看看是什么原因造成的？谢谢

**Comment by mapleshadow** [comment]
本身这个容器没有设定PGUID PUID参数，也就是说，无法将容器的ROOT权限通过PGID PUID传递给群晖，导致权限不一致，无权限创建目录和文件。目前我解决的办法就是直接把目录映射给取消了。。。。。。。。。。。
我也不知道为何官方始终不增加这两个参数，来修复这个问题。

**Comment by mapleshadow** [comment]
找到解决方案了：https://tt-rss.org/wiki/InstallationNotes
这是官方的容器配置，里面有UID GID参数等，而且还有PHP的性能配置，配置到容器内就搞定了！！！
