### ISSUE TITLE
tiny rss无法一个订阅同时存放在多个文件夹

### ISSUE THREAD

**Issue by SuperNG6** [HenryQW/Awesome-TTRSS#44]
这个应该是tiny rss本身的问题？或者是我哪里设置的不对？
我无法把一个订阅同时设置在多个文件夹，比如 【掘金-后端】这个订阅，我想同时存在于【资讯】和【掘金】这两个文件夹中，但是并不可以，其他的比如feedly，reeder，Inoreader都可以， tiny rss是否支持此功能？

**Comment by HenryQW** [comment]
据我所知不支持这个功能。
