### ISSUE TITLE
[BUG]Reeder 5使用Fever API无法登录

### ISSUE THREAD

**Issue by xxllllll** [HenryQW/Awesome-TTRSS#442]
**Bug 描述**
Reeder 5使用Fever API无法登录，通过账号密码登录无法登录，显示Login Failde。
使用安卓应用 Meltdown 测试此 API 可以正常获取到内容。

**你谷歌/百度了吗？**
已使用搜索引擎进行搜索，发现一个类似 Issues，但其中问题并未得到解答。
https://github.com/DigitalDJ/tinytinyrss-fever-plugin/issues/30#issue-1323446521

**部署方法**
 - Docker-compose
 - 使用的镜像版本 [latest]

**部署环境**
 Ubuntu 22.04

**复现步骤**
已开启偏好设置中的启用API，并设置密码。
使用IOS Reeder 5 通过Fever进行登录。

**预期结果**
使用Reeder 5 正常获取内容。

**截屏**
![image](https://user-images.githubusercontent.com/44605747/219567581-918a9aba-6ac0-4687-86c7-4b08ef89219c.png)
![image](https://user-images.githubusercontent.com/44605747/219568406-900fca31-5ec8-4e4d-9099-c62ce45bd834.png)

**错误日志**

> Undefined array key "uid"
> 1. plugins/fever/fever_api.php(137): ttrss_error_handler(Undefined array key "uid", plugins/fever/fever_api.php)
> 2. plugins/fever/index.php(68): before()
> 
> Remote IP: 
> Request URI: /plugins/fever/
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.46

**Comment by xxllllll** [comment]
IOS Reeder 5 版本号5.4 不能使用。
Mac Reeder 5 可以使用，见了鬼了。

**Comment by willsuatsz** [comment]
刚花费$4.99在ios上下载了reeder 5,但也遇到了无法登陆的问题，还请大佬们给予帮助，谢谢！
