### ISSUE TITLE
Move to/Support another Docker registry other than Docker Hub

### ISSUE THREAD

**Issue by jacroe** [HenryQW/Awesome-TTRSS#449]
**Is your feature request related to a problem? Please describe.**
Based on the issues described in [this blog post](https://blog.alexellis.io/docker-is-deleting-open-source-images/), Docker Hub is, perhaps, no longer a safe provider of Docker images. Unless the project is willing to pay.

**Describe the solution you'd like**
Support a different Docker registry, in combination or not, with [GHCR.io](https://ghcr.io/) or [Quay](https://quay.io/).

**Additional context**
Quite a bit of additional context can be seen in [Hacker News](https://news.ycombinator.com/item?id=35166317) and this [/r/selfhosted post](https://www.reddit.com/r/selfhosted/comments/11ryub1/fyi_docker_is_deleting_open_source_organisations/).

**Comment by TonyRL** [comment]
This only affects Open Source "organisations". Meanwhile, Awesome-TTRSS is hosted under https://hub.docker.com/r/wangqiru/ttrss which I believe `wangqiru` is a personal account as you can use from https://hub.docker.com/u/wangqiru.

The blog post also explicitly mentioned:
>As far as we know, this only affects organisation accounts that are often used by open source communities. There was **no change to personal accounts**. Free personal accounts have a [a 6 month retention period](https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage).

**Comment by jacroe** [comment]
While I certainly can't argue against that, I do feel like Docker has shown their hand, and, IMO,  it's only a matter of time before they (attempt to) restrict personal accounts as well.
