### ISSUE TITLE
请教Docker更新问题

### ISSUE THREAD

**Issue by hackenfu** [HenryQW/Awesome-TTRSS#45]
HenryQW，您的作品非常好用，教程也很详细，感谢。
我发现您经常在https://hub.docker.com/r/wangqiru/ttrss更新，我有最新版洁癖，想问下Docker会在后台自动更新到您的最新版本吗？还是每次看到您的更新就要执行一遍docker-compose up -d？
谢谢

**Comment by HenryQW** [comment]
https://docs.docker.com/compose/reference/pull/

**Comment by SuperNG6** [comment]
参考这个
https://sleele.com/2019/06/16/docker更新容器镜像神器-watchtower/
