### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ahaghgoo** [HenryQW/Awesome-TTRSS#452]
**Describe the bug**
I enabled 2FA and the OTP doesn't allow me to login; it doesn't say that I inputted a wrong code or send me to the page that says I inputted the wrong username or password.  I only get an OTP blank field. 

**Have you googled?**
Yes.

**Deployment method**
 - docker-compose
 - latest

**Deployment environment**
 - OS: [Docker Compose on QNAP NAS
 - Browser: [safari]

**To Reproduce**
1. Enable OTP
2. Logout
3. Input username and password
4. Input verification code on the authentication page

**Expected behavior**
To be able to successfully logging in with 2FA enabled.  If issue persists, please provide a way to either disable 2FA through docker-compose CLI or to identify a way to fix why 2FA isn't working. 

**Error logs**

docker logs ttrss --tail 100
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(78): checkConnection()
#3 {main}<pre>Exception while creating PDO object:SQLSTATE[08006] [7] connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?</pre>PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (172.29.48.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()

## Additional Info ##
I have checked my ports on my router and I have ensured that port 5432 has been made open.  Here is the docker-compose file that I have ran.  It's a carbon-copy of what was provided here: 

``
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=http://localhost:181/ # please change to your own domain
      - DB_PASS=ttrss # use the same password defined in `database.postgres`
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=ttrss # feel free to change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true

``

**Comment by TonyRL** [comment]
The log said you entered a wrong password for PostgreSQL.

**Comment by ahaghgoo** [comment]
How do I fix that?

**Comment by ahaghgoo** [comment]
I was able to figure out how to restart from scratch by running the following command: 

``docker system prune

**Comment by ahaghgoo** [comment]
``
