### ISSUE TITLE
[BUG] Not able to update Fever plugin

### ISSUE THREAD

**Issue by ahaghgoo** [HenryQW/Awesome-TTRSS#453]
Hi, the current Fever Emulator plugin is at version 3 that was updated on 2021/11/18.  

Currently the version that is included when building with docker-compose is at version 2.3 which was released on 2020/01/27.  

I cannot currently use the Fever emulator plugin as when I attempt to use it with Reeder or any other app that supports Fever api I get the following errors: 
![Screenshot 2023-04-06 at 00 07 36](https://user-images.githubusercontent.com/1308002/230299624-c63e8186-84c3-48b0-bb28-cfa9269b43ea.png)

![IMG_0017](https://user-images.githubusercontent.com/1308002/230302083-b39daa32-3894-46b7-a621-bd70c5629fa6.PNG)

I believe if I can update the plugin, the emulation will be functional.

**Comment by HenryQW** [comment]
read: https://ttrss.henry.wang/#fever-api
