### ISSUE TITLE
[BUG] mercury插件在twitter和知乎上无法使用

### ISSUE THREAD

**Issue by KwToPA** [HenryQW/Awesome-TTRSS#455]
**Bug 描述**
简洁明了地描述这个 bug。

mercury插件在twitter和知乎上无法使用

twitter

We’ve detected that JavaScript is disabled in this browser. Please enable JavaScript or switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.

知乎

系统监测到您的网络环境存在异常风险，为保证您的正常访问，请输入验证码进行验证。

**你谷歌/百度了吗？**
请善用搜索引擎。

没有结果

**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]

Docker 

latest

**部署环境**
 - 操作系统: [如 Ubuntu 18.04]
 - 浏览器: [如 chrome, safari]

Windows 10  

chrome Version 112.0.5615.138 (Official Build) (64-bit)

**复现步骤**
复现该 bug 的详细步骤
1. 通过订阅 rsshub的路由  [https://rsshub.app/twitter/user/Blankwonder](https://rsshub.app/twitter/user/Blankwonder)
2. 测试mercury插件
3. 报错  We’ve detected that JavaScript is disabled in this browser. Please enable JavaScript or switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.

4. 知乎也一样

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

返回全文内容

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

没有相关的内容  都是其他路由的信息

**其他**
任何有助于 bug 修复的信息。

这个是不是被抓取网站方的原因？   不能修复

**Comment by HenryQW** [comment]
这些反爬虫的网站，几乎都用不了
