### ISSUE TITLE
Postgres 13 is too old, time to upgrade

### ISSUE THREAD

**Issue by dimon222** [HenryQW/Awesome-TTRSS#456]
**Is your feature request related to a problem? Please describe.**
Postgres 13 is way too old. Time to upgrade.

**Describe the solution you'd like**
Latest is 15, and should be used instead.
I've been able to confirm working "from-scratch" setup of repository's compose script with Postgres 15.
Its also possible to switch to 15-bullseye after upgrade via something like https://hub.docker.com/r/tianon/postgres-upgrade

**Additional context**
Don't know about how upgrade path have to look like for this kind of project, but perhaps worth to think about.

**Comment by TonyRL** [comment]
The database upgrade procedure is clearly listed in the [docs](https://ttrss.henry.wang/#database-upgrade-or-migration).

**Comment by dimon222** [comment]
> The database upgrade procedure is clearly listed in the [docs](https://ttrss.henry.wang/#database-upgrade-or-migration).

That's good. Then documentation part is covered. I was mainly speaking about update to compose files that still point to version 13.

**Comment by dimon222** [comment]
Fixed in #510
