### ISSUE TITLE
[BUG]最新的版本有 SELF_URL_PATH 问题

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#459]
用nginx 反代的https 不行了
之前 compose 设置 https://ssss
nginx 代理 可以正常使用 

最新版本不行了， 恢复2.15 的版本可以用

**Comment by marklu1989** [comment]
是的，我也遇到同样问题。数次重建，不能解决。define('_SKIP_SELF_URL_PATH_CHECKS', true);这个也无法解决。

**Comment by ptsa** [comment]
没有办法解决么？
