### ISSUE TITLE
[BUG] mercury parser broken: property_exists()

### ISSUE THREAD

**Issue by delightfuldude** [HenryQW/Awesome-TTRSS#460]
I'm on a fresh install of awesome-ttrss (docker). 
Mercury parser doesn't work, this is in the logs:

```
Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /var/www/plugins.local/mercury_fulltext/init.php:279
Stack trace:
#0 /var/www/plugins.local/mercury_fulltext/init.php(279): property_exists()
#1 /var/www/classes/pluginhandler.php(15): mercury_fulltext->extract()
#2 /var/www/backend.php(169): PluginHandler->catchall()
#3 {main}
  thrown
```

**Comment by lmmsoft** [comment]
same here, use 2023-06 latest version docker-compose version:

Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /var/www/plugins.local/mercury_fulltext/init.php:279
Stack trace:
#0 /var/www/plugins.local/mercury_fulltext/init.php(279): property_exists()
#1 /var/www/classes/pluginhandler.php(15): mercury_fulltext->extract()
#2 /var/www/backend.php(169): PluginHandler->catchall()
#3 {main}
  thrown

Remote IP: x
Request URI: /backend.php
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by Yong011021** [comment]
Have you configured the Mercury Parser API address?

**Comment by lmmsoft** [comment]
通过降级ttrss解决了
参考解决方案：https://lmmsoft.github.io/downgrade_ttrss/
