### ISSUE TITLE
系统-事件日志-Attempt to read property

### ISSUE THREAD

**Issue by Aurora-Dylan** [HenryQW/Awesome-TTRSS#464]
下面的这个是什么原因导致的呢?

E_WARNING (2) | classes/opml.php:334 | Attempt to read property "nodeValue" on null 1. classes/opml.php(334): ttrss_error_handler(Attempt to read property "nodeValue" on null, classes/opml.php) 2. classes/opml.php(601): opml_import_feed({DOMElement}) 3. classes/opml.php(668): opml_import_category({DOMDocument}) 4. classes/pref/feeds.php(894): opml_import() 5. backend.php(159): importOpml()  Real IP: 171.12.4.8 Forwarded For: 171.12.4.8 Forwarded Protocol: https Remote IP: 172.20.0.1 Request URI: /backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
-- | -- | --

**Comment by Aurora-Dylan** [comment]
咨询一下，虽然有这个警告，但是使用是正常的

**Comment by mqq982068** [comment]
解决了吗， 我也报这个错
