### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gop167** [HenryQW/Awesome-TTRSS#467]
[**Describe the bug**

**Have you googled?**
Please google it now.

**Deployment method**
 - Docker or docker-compose
 - Version of the image used [e.g. latest, nightly, 19.8]

**Deployment environment**
 - OS: [e.g. Ubuntu 18.04]
 - Browser: [e.g. chrome, safari]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error logs**
When the error occurs, execute `docker logs ttrss --tail 100` to obtain the error logs and paste **the relevant logs** here.

**Additional context**
](https://github.com/HenryQW/Awesome-TTRSS/issues/135#issuecomment-1650996382)

**Comment by vhladiienko** [comment]
@gop167 You have filed a template bug report without any actual bug details. Please either update the details in your original message or close it.
