### ISSUE TITLE
SELF_URL_PATH位置

### ISSUE THREAD

**Issue by destincc** [HenryQW/Awesome-TTRSS#47]
安装之后我想修改SELF_URL_PATH，那么config.php文件在哪里可以找到？谢谢！

**Comment by destincc** [comment]
upstream ttrssdev {
    server 127.0.0.1:181;
}
还有这个问题这个server后面我是不是也可以写我在yml里面配置的地址，http://域名：181

**Comment by HenryQW** [comment]
麻烦看文档，按照文档提供的步骤部署。
