### ISSUE TITLE
[BUG] can't install with docker compose - failed to register layer: failed to Lchown

### ISSUE THREAD

**Issue by maxwood** [HenryQW/Awesome-TTRSS#475]
**Describe the bug**
Can't install TT-RSS getting the following error -

"failed to register layer: failed to Lchown "/app/node_modules/content-type/HISTORY.md" for UID 1516583083, GID 0 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/node_modules/content-type/HISTORY.md: invalid argument"

**Have you googled?**
Yes

**Deployment method**
 - Docker-compose latest

**Deployment environment**
 - OS: debian 12
 - Browser: -

**To Reproduce**
I followed the section "Deployment via docker-compose" here https://ttrss.henry.wang/#deployment-via-docker

I installed LXC + Docker using a Tteck script on Proxmox

I changed the docker compose file to the ip address of the lxc, ran the docker compose, it downloads a bunch of stuff but then it fails with the following error

"failed to register layer: failed to Lchown "/app/node_modules/content-type/HISTORY.md" for UID 1516583083, GID 0 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/node_modules/content-type/HISTORY.md: invalid argument"

**Expected behavior**
To install

Quite new to this so any advice would be appreciated

**Comment by lusanagi** [comment]
This seems to be an issue with the docker image `wangqiru/mercury-parser-api:latest`; even running `docker pull wangqiru/mercury-parser-api:latest` in console  yields the same error
Either way: help would be appreciated

**Comment by HenryQW** [comment]
no idea what mean by 
> I installed LXC + Docker using a Tteck script on Proxmox

try: https://stackoverflow.com/questions/41928729/docker-failed-to-register-layer
