### ISSUE TITLE
How to Save self-hosted Mercury Parser API Endpoint in the Mercury_fulltext settings under Feeds tab

### ISSUE THREAD

**Issue by pipisauto** [HenryQW/Awesome-TTRSS#49]
* ## _What_ is the issue?

* ## _What_ is your setup? (PHP version, database used, etc.)

    I hosted TT-RSS in website interserver, (php).

* ## _Are_ there any error logs?

No

* ## _How_ can the issue be replicated?

I added your mercuty full text to the plugin of TT-RSS but the point 2 I dont know how to implement:
"Save yourself-hosted Mercury Parser API Endpoint in the Mercury_fulltext settings under Feeds tab."
I need to enter to the site https://github.com/postlight/mercury-parser-api and download the clone? but after download I need to download in my windows computer, the program YARN? I dont know what to do, thanks
-->

**Comment by HenryQW** [comment]
Unfortunately, this falls outside of the scope of my repository. You need to run your own Mercury Parser API instance to support this feature.

You are welcome to use this to host your TTRSS instance, which comes with a mercury instance automatically. For more please refer to the [doc](https://ttrss.henry.wang/).

**Comment by pipisauto** [comment]
thanks

**Comment by pipisauto** [comment]
Hello,

 

I read your doc but I am newbie in this topics.

I hosted my tiny tiny rss in a web hosted site “interserver”

I use windows 10.

I don’t understand the concept described in the link below:

https://henry.wang/2018/04/25/ttrss-docker-plugins-guide.html#deployment-and-configuration

 

How can I make docker compose in windows, I need to enter to cmd?

Can you explain in more detail how can I obtain the mercury api to add to the tt-rss preferences?, I am not a programmer, due this reason there are new concepts for me.

 

Thanks for your help.

**Comment by HenryQW** [comment]
Hi @pipisauto , it sounds like you need someone with a computer background to assist you on site or given access to your Interserver (I assume it's a VPS). I'm happy to assist you if you become a sponsor on [open collective](https://opencollective.com/awesome-ttrss).
