### ISSUE TITLE
[BUG]一直用了好久，今天突然无法访问了

### ISSUE THREAD

**Issue by zhl111** [HenryQW/Awesome-TTRSS#493]
**Bug 描述**
“Exception while creating PDO object:SQLSTATE[08006] [7] could not translate host name "database.postgres" to address: Name does not resolve”

vps的硬盘是11G，现在占用了9.95G，有没有可能是磁盘空间不够？但查了下dock就有7G，也不知能不能缩减

**你谷歌/百度了吗？**
用了

**部署方法**
 - Docker  docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]

**部署环境**
 - 操作系统: debian
 - 浏览器: chrome

**Comment by frontsmith** [comment]
我最近也有同样的问题， 楼主 找到解决方法了吗？

**Comment by HenryQW** [comment]
`docker system prune`
