### ISSUE TITLE
[BUG] Accessible git directory

### ISSUE THREAD

**Issue by Stopka** [HenryQW/Awesome-TTRSS#495]
**Bug**
The docker image contains and exposes the `.git` directory. It's generally considered a **security flaw** to expose it or even have it in the container image.
There is also accessible a `.editorconfig`

**How to replicate**

1. Run the image using the official manual https://ttrss.henry.wang/#deployment-via-docker
2. Try to request any file from git folder like http://localhost:80/.git/config

**Expected behavior**
Response with 404 http status

**Actual  behavior**
Browser downloads file from `.git` directory.

**Proposed fix**
Add `.git` direcotry and `.editorconfig` file to `.dockerignore` file to be omitted from the container image build.

**Affected version**
Tested on current `wangqiru/ttrss:latest` (containing Tiny Tiny RSS v23.12-d4ae6c6)

**Comment by Stopka** [comment]
Thank you 🙏

**Comment by Joselo2022** [comment]
Kk
