### ISSUE TITLE
[BUG] After my blog website use CDN, can't subscribe the rss, get error：60 ssl certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by cczywyc** [HenryQW/Awesome-TTRSS#497]
**Describe the bug**
My [blog website](https://cczywyc.com) is built using hexo and deployed with nginx. At first, my blog website's RSS could be subscribed to in tt-rss, but after I applied a CDN to the website, it stopped working, my [RSS link](https://cczywyc.com/atom.xml) remains accessible.
It should be noted that when configuring the CDN, the HTTPS certificate I used was the original certificate of the website that I uploaded from my local machine.
I'm not sure why this error occurred.

**Have you googled?**
I hava googled some results, but not work

**Deployment method**
 - Docker or docker-compose: docker-compose
 - Version of the image used: latest

**Deployment environment**
 - OS: Ubuntu 22.04
 - Browser: Chrome V120

**Comment by HenryQW** [comment]
I recommended https://freshrss.org/index.html
