### ISSUE TITLE
希望支持arm架构处理器的设备，比如斐讯N1小钢炮,树莓派

### ISSUE THREAD

**Issue by ZhuningS** [HenryQW/Awesome-TTRSS#50]
- ## _What_ is the issue?
希望支持arm架构处理器的设备，比如斐讯N1小钢炮,树莓派

armhf | arm32v7-latest
arm64 | arm64v8-latest
x86-64 | amd64-latest

Raspberry Pi / arm7 / arm8.

- ## _What_ is your OS and its version?
N1小钢炮系统NDM

- ## _What_ is your installation method?
compose与直接安装都试过。参考https://ttrss.henry.wang/zh/

- ### Docker

  - Did you build your own dockerfile (paste it here if possible)?

- ### Old-fashion way

  - _What_ is your setup? (PHP version, database used, etc.)
    

- ### Others

- ## _Are_ there any error logs?
页面打不开，查看日志一直报错：standard_init_linux.go：207：exec用户进程导致“exec格式错误” 
网上的方法（修改格式等）并不管用

- ## _How_ can the issue be replicated?

- ## Other Comments

**Comment by HenryQW** [comment]
两个子镜像 mercury 和 opencc 目前不兼容 arm 架构，这是没有办法支持 arm 的直接原因。
