### ISSUE TITLE
Is it possible to use multiple domains and if yes then how ?

### ISSUE THREAD

**Issue by buzhangjiuzhou** [HenryQW/Awesome-TTRSS#500]
**Is your feature request related to a problem? Please describe.**

Hi, I just have two domains and I want both of them to  get to the same service. But I found that I cannot make the second domain the same as that in `SELF_URL_PATH`.

**Describe the solution you'd like**
I wonder whether multi-domain is possible and if yes, then how to config to enable my second domain.

**Additional context**
No other useful message found.

**Comment by HenryQW** [comment]
no, that's just how ttrss is coded.
