### ISSUE TITLE
使用docker-compose搭建，ttrss容器不断重启，查看日志一直报错sh: can't open '/wait-for.sh': No such file or directory

### ISSUE THREAD

**Issue by ZhuningS** [HenryQW/Awesome-TTRSS#52]
- ## _What_ is the issue?
使用docker-compose搭建，ttrss容器不断重启（其他容器正常）

- ## _What_ is your OS and its version?
群晖DSM6.1.4  最新Docker

- ## _What_ is your installation method?
docker-compose

- ### Docker

  - Did you build your own dockerfile (paste it here if possible)?

- ### Old-fashion way

  - _What_ is your setup? (PHP version, database used, etc.)
    

- ### Others

- ## _Are_ there any error logs?
查看日志一直报错sh: can't open '/wait-for.sh': No such file or directory

- ## _How_ can the issue be replicated?

- ## Other Comments

**Comment by HenryQW** [comment]
初步估计你的操作有问题，如果是拉取最新版的镜像不可能出现该问题，建议重试。

**Comment by famiuer** [comment]
You may check the docker-compose.yml file. I happened to have this issue and I found out there was an error in line 29
` command: sh -c 'sh /wait-for.sh database.postgres:5432 -- php /configure-db.php && exec s6-svscan /etc/s6/'`
