### ISSUE TITLE
[Feature] postgresql数据库指定schema部署

### ISSUE THREAD

**Issue by transparent1998** [HenryQW/Awesome-TTRSS#522]
希望可以指定pg数据库中的某个schema进行部署，或者使用类似postgres://${PG_USER}:${PG_PWD}@postgres:5432/${PG_DB}?currentSchema=${PG_SCHEMA}格式的URL

**Comment by TonyRL** [comment]
Not possible.
TTRSS handles [it internally](https://gitlab.tt-rss.org/tt-rss/tt-rss/-/blob/master/sql/pgsql/schema.sql).
