### ISSUE TITLE
Combined RSSHub and Awesome-TTRSS in Docker Compose?

### ISSUE THREAD

**Issue by b9AcE** [HenryQW/Awesome-TTRSS#525]
I am trying to combine Awesome-TTRSS with RSSHub using Dcoker Compose on an Orange Pi 5+ running up to date DietPi.
I have it working if the traffic goes out to the Internet and then back in to my LAN again, but I would prefer to minimize the services published by me the the Internet to those that by their desired function must be so, so I would prefer to have all RSSHub→ATTRSS traffic stay on the device, but I have not gotten it to work, instead just getting `unable to fetch: Requested URL failed extended validation. [-1]` from ATTRSS when trying to get it from one Docker Compose project to another (both essentially just the compose YAML template files provided by each project),
sooo I was wondering, maybe you could also have a compose YAML template on the project's main webpage (https://ttrss.henry.wang) where RSSHub and its Redis are properly integrated into the same compose YAML as ATTRSS, for convenience?

Thank you!

**Comment by CXwudi** [comment]
You need to create an external bridge network in docker and assign both TTRSS and RSSHub container to use that external bridge network, see https://docs.docker.com/engine/network/tutorials/standalone/

**Comment by b9AcE** [comment]
Thank you for the additional information @CXwudi.
I was already aware of the information you provided.
That was not the question asked in this issue, but I am still thankful.

**Comment by CXwudi** [comment]
Okay, then assuming you can ping the RSSHub docker container from the TTRSS container, you might need the [`ALLOW_PORTS`](https://ttrss.henry.wang/#supported-environment-variables) to set to RSSHub port as it is the workaround in ATTRSS to bypass TTRSS's limitation of blocking non-standard port (80,443)

**Comment by b9AcE** [comment]
I'm sorry, I should have been more clear in my previous message.
The question is the last part of the initial post 
> sooo I was wondering, maybe you could also have a compose YAML template on the project's main webpage (https://ttrss.henry.wang/) where RSSHub and its Redis are properly integrated into the same compose YAML as ATTRSS, for convenience?

I am still thankful for the attempt at assisting in troubleshooting, @CXwudi, but that is not what was requested and is not needed at this time. I am only seeking an answer to the asked question and implicitly making a project suggestion which would enable an affirmative response.
Thank you!

**Comment by CXwudi** [comment]
Ohh, my bad. Maybe you could found online about template for integrating both TTRSS and RSSHub. I personally just leave the compose file separate for each service and use a dedicated docker bridge network to achieve communication
