### ISSUE TITLE
[BUG]yaml: line 216: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Habermann76** [HenryQW/Awesome-TTRSS#534]
**Describe the bug**
when running docker compose up -d i get an error
**Have you googled?**
Please google it now.

**Deployment method**
 - Docker or Docker Compose
 - Version of the image used [e.g. latest, nightly, 19.8]

**Deployment environment**
 - OS: [e.g. Ubuntu 24.04]
 - Browser: [e.g. chrome, safari]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error logs**
When the error occurs, execute `docker logs ttrss --tail 100` to obtain the error logs and paste **the relevant logs** here.

**Additional context**

**Comment by TonyRL** [comment]
Closing this issue since the issue form is completely empty which provides 0 help of your issue and I'm not going to play Mastermind. 

Fun facts: the docker compose file only contains [69 lines](https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml).
