### ISSUE TITLE
[BUG] Instructions on how to update Database

### ISSUE THREAD

**Issue by mariomaz87** [HenryQW/Awesome-TTRSS#538]
**Describe the bug**
I'm trying to upgrade my docker compose from using postgres 13 to postgres 16. I'm doing it step-by-step and I want to update to postgres 14 first. In the instructions on the webpage I have:

```
Use the following command to dump all your data:

docker exec postgres pg_dumpall -c -U YourUsername > export.sql
```
I don't understand which Username should I insert. I tried with my TTRSS user but it's not working. In my postgres DB the only user is "postgres", if I insert this the dump is ok, but then I have issues logging back into TTRSS after the upgrade.

**Have you googled?**
Yes, I have

**Deployment method**
 - Docker or Docker Compose: docker compose
 - Version of the image used [e.g. latest, nightly, 19.8]: latest

**Deployment environment**
 - OS: RaspOS
 - Browser: Firefox

**Comment by osnsyc** [comment]
The password needs to be reset because version 13 used md5 algorithm and version 14 uses SCRAM-SHA-256 algorithm.
```bash
docker exec -i postgres psql -U postgres
\password
# Enter the postgres password set in docker-compose.yml 
# ctrl+D to exit
```

**Comment by mariomaz87** [comment]
> The password needs to be reset because version 13 used md5 algorithm and version 14 uses SCRAM-SHA-256 algorithm.
> 
> ```shell
> docker exec -i postgres psql -U postgres
> \password
> # Enter the postgres password set in docker-compose.yml 
> # ctrl+D to exit
> ```

Thanks! I got it working with a slightly different command:
docker exec -it postgres psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'newpassword';"
