### ISSUE TITLE
docker-compose创建成功，但是ttrss无法访问，日志中一直报Operation timed out

### ISSUE THREAD

**Issue by xeqtr1982** [HenryQW/Awesome-TTRSS#55]
- ## _What_ is the issue?

docker-compose创建成功，但是ttrss无法访问，日志中一直报Operation timed out

- ## _What_ is your OS and its version?

DSM 6.2.2-24922 Update 2，Docker是最新版

- ## _What_ is your installation method?

docker-compose

- ### Docker

  - Did you build your own dockerfile (paste it here if possible)?

- ### Old-fashion way

  - _What_ is your setup? (PHP version, database used, etc.)
    

- ### Others

- ## _Are_ there any error logs?

日志中一直报Operation timed out

- ## _How_ can the issue be replicated?

- ## Other Comments

**Comment by Boycottangent** [comment]
你好，我也遇到这个问题了，请问你最终是怎么解决的？
