### ISSUE TITLE
添加代理支持

### ISSUE THREAD

**Issue by Felix2yu** [HenryQW/Awesome-TTRSS#57]
由于VPS资源吃紧，把ttrss放到了本地。在config.php中添加
```
define ('_HTTP_PROXY', 'IP:port');
```
可以解决被墙地址订阅问题，见 https://git.tt-rss.org/fox/tt-rss/pulls/36
希望加入相关环境变量支持，谢谢。

**Comment by HenryQW** [comment]
在度假，回去加！

**Comment by RookieZoe** [comment]
@HenryQW 同样有这个需求，搜到个这个：[options_per_feed](https://github.com/sergey-dryabzhinsky/options_per_feed) 不会PHP，不知道能不能用。。。

**Comment by HenryQW** [comment]
>@HenryQW 同样有这个需求，搜到个这个：[options_per_feed](https://github.com/sergey-dryabzhinsky/options_per_feed) 不会PHP，不知道能不能用。。。

@RookieZoe 这个看着不错，我回去了试一下

**Comment by HenryQW** [comment]
@RookieZoe 插件已经添加了，我没有测试功能性，麻烦尝试一下。
@Felix2yu 已经加入了对应变量，麻烦测试一下 `wangqiru/ttrss:dev` 镜像，如果没有问题的话我就并入 master 了。

**Comment by Felix2yu** [comment]
`wangqiru/ttrss:dev`docker-compose加入`- HTTP_PROXY=192.168.0.1:7890`变量，进入容器中`config.php`中并没有相关配置，无法访问被墙地址。
也测试了`options_per_feed`，配置HTTP代理后也无法访问被墙地址。

**Comment by RookieZoe** [comment]
周末试一下

**Comment by HenryQW** [comment]
>`wangqiru/ttrss:dev`docker-compose加入`- HTTP_PROXY=192.168.0.1:7890`变量，进入容器中`config.php`中并没有相关配置，无法访问被墙地址。 ...

@Felix2yu 容器是无法解析到容器外的 192.168.0.1 地址的。必须公网地址或用docker network discovery。

**Comment by Felix2yu** [comment]
@HenryQW 这边是方便表述这么写的，实际用的是NAS的内网地址，手动写到配置中是生效的。我想表达的是在docker-compose中加入`HTTP_PROXY`变量并未在配置文件中体现，也不实现目的。

**Comment by HenryQW** [comment]
>@HenryQW 这边是方便表述这么写的，实际用的是NAS的内网地址，手动写到配置中是生效的。我想表达的是在docker-compose中加入`HTTP_PROXY`变量并未在配置文件中体现，也不实现目的。

@Felix2yu 我可能漏看了`_HTTP_PROXY`的用法，回头看一看。但是 options_per_feed 不应该不能用才对

**Comment by RookieZoe** [comment]
> > @HenryQW 这边是方便表述这么写的，实际用的是NAS的内网地址，手动写到配置中是生效的。我想表达的是在docker-compose中加入`HTTP_PROXY`变量并未在配置文件中体现，也不实现目的。
> 
> @Felix2yu 我可能漏看了`_HTTP_PROXY`的用法，回头看一看。但是 options_per_feed 不应该不能用才对

在群晖上试了一下，options_per_feed 貌似没起作用。。。要么是我使用方式不对。。。流量压根没走到代理的服务上。。。

**Comment by RookieZoe** [comment]
源配置如图
![option_per_feed](https://user-images.githubusercontent.com/11600873/62819587-d0d45200-bb89-11e9-8240-10913c974eb9.png)

PS：我已经把服务迁移到梯子所在的vps上了。。。所以这个代理需求对我来说已经不是那么重要了。。。

**Comment by HenryQW** [comment]
哪有可能是这个插件本身有问题，建议去该 repo 下开一个 issue。

**Comment by hackenfu** [comment]
怎么看得出走没走代理啊？我试着把全部feed都设置成代理，目前为止没出现过error了，以前时不时会出现获取error，因为是台湾的feed

**Comment by HenryQW** [comment]
@hackenfu 看流量记录吧，我也不清楚也没有日志。
@Felix2yu `HTTP_PROXY` 的用法没错才对，是用的 dev 镜像吗？

**Comment by Felix2yu** [comment]
最新dev好了，感谢！

**Comment by hackenfu** [comment]
> 最新dev好了，感谢！

请问你怎么看得出走没走代理的？

**Comment by Felix2yu** [comment]
@hackenfu 找一个明确知道是被墙的订阅源，比如”端传媒“，右击调试，代理有相应的记录。我用的是clash，日志里就会有
`time="xxx" level=info msg="xxx --> theinitium.com match MATCH using Proxy[xx]`

看你描述时好时断，应该是网络抖动丢包了吧。真要是被墙了肯定全程红。

**Comment by hackenfu** [comment]
> @hackenfu 找一个明确知道是被墙的订阅源，比如”端传媒“，右击调试，代理有相应的记录。我用的是clash，日志里就会有
> `time="xxx" level=info msg="xxx --> theinitium.com match MATCH using Proxy[xx]`
> 
> 看你描述时好时断，应该是网络抖动丢包了吧。真要是被墙了肯定全程红。

原来还有这个办法，我回去试试，多谢！有可能像你所说丢包了，这个台湾网站确实访问比较慢的，有可能加载不过来就error了，换了代理加载快了就成功了

**Comment by HenryQW** [comment]
#61 merged.
