### ISSUE TITLE
无法启动ttrss

### ISSUE THREAD

**Issue by willie91** [HenryQW/Awesome-TTRSS#62]
- ## _What_ is the issue?

无法启动ttrss

- ## _What_ is your OS and its version?

- ## _What_ is your installation method?

- ### Docker

- ### Old-fashion way

- ### Others

- ## _Are_ there any error logs?

- ## _How_ can the issue be replicated?

- ## Other Comments

![_20190814043028](https://user-images.githubusercontent.com/32695308/63006984-6174a000-beb2-11e9-9e19-ce40155b3498.png)
![_20190814043049](https://user-images.githubusercontent.com/32695308/63007011-6f2a2580-beb2-11e9-8067-7506de16b840.png)
![_20190814043607](https://user-images.githubusercontent.com/32695308/63007021-75200680-beb2-11e9-8589-aeabbbbfcb21.png)
你好，请问一下，我docker安装的ttrss已经启动成功了，但是页面一直提示配置错误，我贴上了我的配置，跟提示的地址是一样，但是一直都访问不了，不知道是怎么回事。

希望能帮忙看一下，谢谢

**Comment by HenryQW** [comment]
你好，这是一个我死活都无法复现的问题，参见 #7 #19 #20 #33 。

我唯一可以复现该问题的办法，就是故意填错 `SELF_URL_PATH`。

请再三确认所以配置与部署都按照文档。

**除非能够发现导致该问题的根本原因（我无法定位任何原因），此后该问题的 issue 直接关闭，不再回复。**

**Comment by SuperNG6** [comment]
这个问题我又遇到过，问题在在于你的填写的内容本身就是错的
比如，我我的ttrss是开启https的，但是compose文件里不能直接写https://ttrss.com，而且应该填写http://ttrss.com
你遇到这个问题说明你填写的ip是错误的，不能填写这个ip，时间太久了，你可以试试填写127.0.0.1试试，或者容器ip

**Comment by jostyee** [comment]
@SuperNG6 得看具体怎么配置吧，我是用Nginx反代proxy_pass过来，就得填https:// foo .com/ 才行

**Comment by SuperNG6** [comment]
> @SuperNG6 得看具体怎么配置吧，我是用Nginx反代proxy_pass过来，就得填https:// foo .com/ 才行

我也是nginx反代，具体的我也记不清了，太久了
当时还写了一篇博客
https://sleele.com/2019/06/16/tiny-tiny-rss-%E9%83%A8%E7%BD%B2%E6%B5%81%E7%A8%8B/

**Comment by jostyee** [comment]
@SuperNG6 你这文章里面有些地方不太合理吧，比如：

> 地址填写成http://Mercury容器的IP:3000，不要按照图上填写

这里其实该用docker-compose里指定的container name

**Comment by SuperNG6** [comment]
> @SuperNG6 你这文章里面有些地方不太合理吧，比如：
> 
> > 地址填写成[http://Mercury容器的IP:3000，不要按照图上填写](http://Mercury%E5%AE%B9%E5%99%A8%E7%9A%84IP:3000%EF%BC%8C%E4%B8%8D%E8%A6%81%E6%8C%89%E7%85%A7%E5%9B%BE%E4%B8%8A%E5%A1%AB%E5%86%99)
> 
> 这里其实该用docker-compose里指定的container name

确实是，看了一下yml，里面指定名字了，那就可以直接http://name:3000了，习惯使然了

**Comment by HenryQW** [comment]
这里应该填写你访问 ttrss 的最终地址，也就是你浏览器地址栏里看见的地址，无论是直接 IP 还是通过反代。我服务器上跑了4年了也没遇到过问题，倒是 dev 的时候填错会遇到。

**Comment by 1192704994** [comment]
可能是系统原先用docker装过ttrss，或者是数字的全角半角？
我重装系统并且用手打的ip就可以进去。

**Comment by fengzilong** [comment]
还有一种情况，database.postgres 中的 POSTGRES_PASSWORD 和 service.rss 中的 DB_PASS 不一致也会引起这个问题（虽然概率很低，也在这里提下）

**Comment by Johnnyww** [comment]
想问一下是不是不能写成https://domain.com/ttrss/这样的形式么？然后再用nginx反向代理拦截/ttrss/路径，感觉这样挺方便的，毕竟多个项目放在一起，不太想对外开放端口的话。

**Comment by HenryQW** [comment]
@Johnnyww 搜一下啊 issue 你就会发现 #135。

**Comment by sharefantasy** [comment]
请问这个部分可以自行去掉吗？是什么原因导致？因为本来就不打算买域名或部署dns。

**Comment by sdttttt** [comment]
我今天碰上了一种非常奇怪的错误, 配置是正确的, 但是TTRSS始终提示`SELF_URL_PATH`不正确. 
我重新删除, 再拉取了TTRSS的镜像, 再次运行`docker-compose`就解决了这个问题...

**Comment by lcycug** [comment]
Thank @[famiuer](https://github.com/famiuer) for a provisional solution resolving the startup failure regarding "SELF_URL_PATH" which confuses me for days. After a switch from wangqiru/ttrss:latest to wangqiru/ttrss:nightly-2020-12-26 in the docker-compose.yml, my server comes back.

Hope this could help someone faced with the same issue in the community.

**Comment by HenryQW** [comment]
Recently builds are not stable. See https://github.com/HenryQW/Awesome-TTRSS/issues/267#issuecomment-784246758

**Comment by zhupai** [comment]
Thank @lcycug  for the advice. I've solved this problem"SELF_URL_PATH".

**Comment by kaaass** [comment]
提供一个 Apache 可用的反代配置：

```httpd.conf
<IfModule mod_proxy.c>
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPass / http://127.0.0.1:port/
    ProxyPassReverse / http://127.0.0.1:port/
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto https
</IfModule>
```

**Comment by markwhitey** [comment]
![image](https://user-images.githubusercontent.com/25740693/124586351-eabb6400-de88-11eb-82e1-58122e6d6e31.png)
我人傻了，我访问的地址是和我填的是一样的，但是提示我要填不一样的

**Comment by hmy1210** [comment]
> 这个问题我又遇到过，问题在在于你的填写的内容本身就是错的 比如，我的ttrss是开启https的，但是compose文件里不能直接写[https://ttrss.com，而且应该填写http://ttrss.com，否则就会出现你图上的这个错误页面](https://ttrss.com%EF%BC%8C%E8%80%8C%E4%B8%94%E5%BA%94%E8%AF%A5%E5%A1%AB%E5%86%99http://ttrss.com%EF%BC%8C%E5%90%A6%E5%88%99%E5%B0%B1%E4%BC%9A%E5%87%BA%E7%8E%B0%E4%BD%A0%E5%9B%BE%E4%B8%8A%E7%9A%84%E8%BF%99%E4%B8%AA%E9%94%99%E8%AF%AF%E9%A1%B5%E9%9D%A2) 你遇到这个问题说明你填写的ip是错误的，不能填写这个ip，时间太久了，我也记不清我当时尝试解决的各种方法了，你可以试试填写127.0.0.1（或者0.0.0.0)试试，或者容器ip

感谢提醒，在命令里改成了http，反代成功了~谢谢

**Comment by online-web2025** [comment]
> ![image](https://user-images.githubusercontent.com/25740693/124586351-eabb6400-de88-11eb-82e1-58122e6d6e31.png) 我人傻了，我访问的地址是和我填的是一样的，但是提示我要填不一样的

你这个问题是ttrss不让你用https访问，你需要在宝塔里面重新设置一下反代。我折腾了一上午终于解决了。参考这个文章https://cry33.com/archives/685.html。希望对你有帮助

**Comment by gop167** [comment]
我试了怎么变成这样了nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/ttrssdev.henry.wang/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/ttrssdev.henry.wang/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /www/server/nginx/conf/nginx.conf test failed

**Comment by Dcell** [comment]
如果是通过 Docker 安装 nginx，又会出现一堆问题。人麻了

**Comment by Dcell** [comment]
我有个疑问，如果我想要 2级path，反向代理的 ttrss，应该怎么配置？
