### ISSUE TITLE
Docker tags for stable releases

### ISSUE THREAD

**Issue by szpak** [HenryQW/Awesome-TTRSS#64]
## Feature description
It would be nice to have a dedicated Docker tags for stable TTRSS releases

## Detailed information
Using `latest` as tag has its advantages. However, for better reproducibility and stability one could want to put 19.8 to stay with ttrss 19.8. Of course you may want to do some non ttrss source code related changes in the project, but then it could be `19.8-h1`, `19.8-h2` (with `19.8` - or `19.8-latest` at your preference - pointing to the latest tag with ttrss 19.8).

As a bonus, tags could be also made at the GitHub level to have access to corresponding source code - in a case of need to patch something by the user itself.

Btw, thanks for developing that container! I've found it very useful.

**Comment by HenryQW** [comment]
Hi Marcin,

Thanks for the suggestion it's done. I was planning to do so a long time ago.

**Comment by szpak** [comment]
Thanks!

Btw, https://cloud.docker.com/repository/docker/wangqiru/ttrss/tags redirects me to the main Hub page. https://hub.docker.com/r/wangqiru/ttrss/tags works better if you are an anonymous user..

**Comment by HenryQW** [comment]
Thanks for pointing that out!
