### ISSUE TITLE
求支持Single User 模式

### ISSUE THREAD

**Issue by nielinjie** [HenryQW/Awesome-TTRSS#67]
- ## _What_ is the issue?

不算是ISSUE，是个请求。

- ## _What_ is your OS and its version?

docker-desktop 自带的kubernetes。

- ## _What_ is your installation method?

- ### Docker

直接用的docker-compose.yml 文件。

- ## _Are_ there any error logs?

（无）

- ## _How_ can the issue be replicated?

（无）

- ## Other Comments

由于希望能作为个人的rss服务器，希望能剪除关于多用户和认证等多余的操作，看到ttrss本身有这个选项，但无法通过环境变量传入。希望有这个功能。

有些ttrss的docker image有这个功能，可以参考下。

https://github.com/x86dev/docker-ttrss#single-user-mode

**Comment by HenryQW** [comment]
见：https://ttrss.henry.wang/zh/#%E6%94%AF%E6%8C%81%E7%9A%84%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E5%88%97%E8%A1%A8

可以使用 `wangqiru/ttrss:nightly` 启用该功能，或者等 ttrss 下一个版本发行后使用 `wangqiru/ttrss:latest`。
