### ISSUE TITLE
[BUG] 'pg_trgm' extension not installed for 'ttrss' db, causing 'af_psql_trgm' user plugin to fail and breaking feed refresh

### ISSUE THREAD

**Issue by benfishbus** [HenryQW/Awesome-TTRSS#69]
**Describe the bug**
When I enable user plugin `af_psql_trgm`, all feeds fail to refresh due to a problem with execution of the plugin. This appears to be due to the fact that while `postgresql-contrib` is installed with `sameersbn/postgresql`, the `pg_trgm` extension is not installed for the `ttrss` db.

**Have you googled?**
Can be remedied as follows:
`sudo -u postgres psql --dbname=ttrss`
then install the extension there:
`CREATE EXTENSION pg_trgm;`
[Source Link](https://community.tt-rss.org/t/solved-function-similarity-does-not-exist/1611/5)

**Deployment method**
 - Docker-compose
 - Latest

**Deployment environment**
 - OS: unraid
 - Browser: chrome

**To Reproduce**
1. Go to Preferences, then Plugins
2. Check 'af_psql_trgm' to enable
3. Click 'Enable selected plugins'
4. See feeds no longer refresh, and errors appear in Preferences > System > Event Log

**Expected behavior**
This plugin is supposed to reduce duplicate articles by marking similar articles as read, and should not prevent feeds from refreshing.

**Error logs**

/var # cat log/nginx/error.log 
2019/08/30 03:34:58 [error] 21#21: *1617 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  function "similarity" does not exist
LINE 1: select 'similarity'::regproc
               ^ in /var/www/plugins/af_psql_trgm/init.php:267
Stack trace:
#0 /var/www/plugins/af_psql_trgm/init.php(267): PDO->query('select 'similar...')
#1 /var/www/classes/rssutils.php(693): Af_Psql_Trgm->hook_article_filter(Array)
#2 /var/www/classes/api.php(415): RSSUtils::update_rss_feed(1)
#3 /var/www/api/index.php(81): API->updateFeed()
#4 {main}
  thrown in /var/www/plugins/af_psql_trgm/init.php on line 267PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block in /var/www/include/sessions.php:120
Stack trace:
#0 /var/www/include/sessions.php(120): PDOStatement->execute(Array)
#1 [internal function]: ttrss_write('irfk949ip1o7hbv...', 'dWlkfGk6MTt2ZXJ...')
#2 [internal function]: session_write_close()
#3 {main}
  thrown in /var/www/include/sessions.php on line 120" while reading response header from upstream, client: 192.168.1.20, server: , request: "POST /api/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxxxxxxx.xxxxxxxxxx:181"

**Comment by HenryQW** [comment]
Seems TTRSS has renamed the plugins? I will have to look into this when I have time. If you have any suggestions or even better submit a PR.

**Comment by HenryQW** [comment]
Hi @benfishbus , I tried to reproduce the issue with BBC, it seems it's working fine on my side and no error logs in both TTRSS and nginx. I suspect it's because my database has pg_tram initialized a long time ago (though I definitely didn't do it manually).

Will you be able to enable to plugin, then right click the feed and select Debug Feed, make sure you check both force options.

![image](https://user-images.githubusercontent.com/5896343/64215361-3c20f380-ceac-11e9-9c8d-e9e7e4088469.png)
![image](https://user-images.githubusercontent.com/5896343/64215367-46db8880-ceac-11e9-9394-811508147f36.png)
![image](https://user-images.githubusercontent.com/5896343/64215431-a9cd1f80-ceac-11e9-8e57-13d18f44940b.png)

**Comment by HenryQW** [comment]
I just found it might also be initialized via an env "DB_NAME" in pgsql container, will you be able to test this?

https://github.com/sameersbn/docker-postgresql#enabling-extensions

**Comment by benfishbus** [comment]
Since I already installed the extension (and don't know how to uninstall
it), debug shows the plugin executing successfully on articles in one of
the feeds where it's enabled:

[02:16:41/7182] ... Af_Psql_Trgm
[02:16:41/7182] === 0.0004 (sec)

DB_NAME is set already (per the docker-compose.yml you include) as follows:

   environment:
      - DB_NAME=ttrss


-Ben
