### ISSUE TITLE
ttrss                | sh: can't open '/wait-for.sh': No such file or directory[BUG]

### ISSUE THREAD

**Issue by elmagnificogi** [HenryQW/Awesome-TTRSS#73]
**Bug 描述**
应该是找不到wait-for.sh 这个文件，然后导致后面一系列报错以后不会restart，盲猜这个wait-for.sh应该是等数据库啥的全都启动以后ttrss才启动
ttrss                | sh: can't open '/wait-for.sh': No such file or directory

**部署方法**
直接使用docker-compose部署，不下载源码
 - docker-compose
 - latest

**部署环境**
 - centos 7

**错误日志**
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
Creating network "root_default" with the default driver
Creating mercury  ... done
Creating ttrss    ... done
Creating opencc   ... done
Creating postgres ... done
Attaching to postgres, mercury, opencc, ttrss
postgres             | Initializing datadir...
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
postgres             | Initializing certdir...
postgres             | Initializing logdir...
mercury              | 
mercury              | > mercury-parser-api@1.0.0 start /app
mercury              | > node index.js
mercury              | 
postgres             | Initializing rundir...
postgres             | Setting resolv.conf ACLs...
opencc               | 
opencc               | > opencc.henry.wang@0.0.0 start /usr/src/app
opencc               | > node ./bin/www
opencc               | 
ttrss exited with code 2
postgres             | Starting PostgreSQL 10...
postgres             | 2019-09-21 09:27:22.356 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres             | 2019-09-21 09:27:22.356 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres             | 2019-09-21 09:27:22.381 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres             | 2019-09-21 09:27:22.575 UTC [1048] LOG:  database system was shut down at 2019-09-21 09:27:22 UTC
postgres             | 2019-09-21 09:27:22.590 UTC [1] LOG:  database system is ready to accept connections
ttrss exited with code 2
ttrss exited with code 2
mercury              | 🚀Mercury Parser API listens on port 3000
ttrss exited with code 2
ttrss exited with code 2
ttrss exited with code 2
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/compose/cli/log_printer.py", line 233, in watch_events
    event['container'].attach_log_stream()
  File "/usr/lib/python2.7/site-packages/compose/container.py", line 206, in attach_log_stream
    self.log_stream = self.attach(stdout=True, stderr=True, stream=True)
  File "/usr/lib/python2.7/site-packages/compose/container.py", line 298, in attach
    return self.client.attach(self.id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 57, in attach
    response, stream, self._check_is_tty(container)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 366, in _read_from_socket
    socket = self._get_raw_response_socket(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 279, in _get_raw_response_socket
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
APIError: 409 Client Error: Conflict ("container e963b7eaab64c20df5b325f8a7ae0a1df612bd5fe4305c50f558c3a08c69cffe is restarting, wait until the container is running")

**Comment by elmagnificogi** [comment]
/usr/lib/python2.7/site-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.2.1) doesn't match a supported version!
RequestsDependencyWarning) 这个错忽略，我解了这个warning 还是报下面的内容

**Comment by elmagnificogi** [comment]
前面是我docker-compose太老了，我更新了以后，报的就是找不到这个文件
```
Creating mercury ... done
Creating mercury ... 
Creating opencc ... 
Creating postgres ... 
Attaching to opencc, postgres, ttrss, mercury
postgres             | Initializing datadir...
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss exited with code 2
opencc               | 
opencc               | > opencc.henry.wang@0.0.0 start /usr/src/app
opencc               | > node ./bin/www
opencc               | 
mercury              | 
mercury              | > mercury-parser-api@1.0.0 start /app
mercury              | > node index.js
mercury              | 
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
postgres             | Initializing certdir...
postgres             | Initializing logdir...
postgres             | Initializing rundir...
postgres             | Setting resolv.conf ACLs...
ttrss exited with code 2
postgres             | Starting PostgreSQL 10...
postgres             | 2019-09-21 10:48:09.874 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres             | 2019-09-21 10:48:09.875 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres             | 2019-09-21 10:48:09.882 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres             | 2019-09-21 10:48:09.904 UTC [1048] LOG:  database system was shut down at 2019-09-21 10:48:09 UTC
postgres             | 2019-09-21 10:48:09.926 UTC [1] LOG:  database system is ready to accept connections
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
mercury              | 🚀Mercury Parser API listens on port 3000
ttrss exited with code 2
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss exited with code 2
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss exited with code 2
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss exited with code 2
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
ttrss                | sh: can't open '/wait-for.sh': No such file or directory
```

**Comment by HenryQW** [comment]
我无法还原该问题。可能是 ttrss 镜像太旧，建议更新重试。

**Comment by scoxau** [comment]
Hello, I am also getting this issue

**Comment by brilon** [comment]
@scoxau the file was missing cos you didn't pull the latest source code. wait-for.sh is located in src folder.
