### ISSUE TITLE
[Feature] How to modify PHP-FPM params?

### ISSUE THREAD

**Issue by jostyee** [HenryQW/Awesome-TTRSS#74]
**该功能能够解决的问题**
ttrss实例启动时日志出现警告：
```
[24-Sep-2019 05:57:27] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

**形容理想的解决方案**
支持通过ENV或者挂载volume设置fpm pool

**其他**
https://docs.bitnami.com/bch/apps/tiny-tiny-rss/configuration/configure-phpfpm-processes/

**Comment by HenryQW** [comment]
我不是很懂这一块，推荐自主挂载一个 conf，路径看了下应该是`/etc/php7/php-fpm.d/www.conf`。

```yml
volumes:
      - /你的conf:/etc/php7/php-fpm.d/www.conf
```

**Comment by jostyee** [comment]
我觉得可以像docker-compose引用的 https://github.com/sameersbn/docker-postgresql 这样，启动容器时通过SED把设置的env替换上去

**Comment by HenryQW** [comment]
请问这个 warning 对正常使用有何影响？

**Comment by jostyee** [comment]
线程池吃满了了吧， https://serverfault.com/a/479484/130416 ，不影响用

**Comment by HenryQW** [comment]
我没有动过默认 php 设置，系统非常稳定，所以我就不纳入修改了，照顾一下资源吃紧的 VPS。
