### ISSUE TITLE
如何安装第三方插件呢？没找到插件的文件夹

### ISSUE THREAD

**Issue by fuyun-yipian** [HenryQW/Awesome-TTRSS#83]
如题，我是通过 docker-compose 部署的，不知道插件的文件夹在哪？该如何安装其他插件呢？

**Comment by HenryQW** [comment]
映射到 `/var/www/plugins`

**Comment by fuyun-yipian** [comment]
可以给一个具体的命令吗？谢谢！

**Comment by HenryQW** [comment]
建议搜索 docker mount volume

**Comment by fuyun-yipian** [comment]
比如我在本地创建一个目录: mkdir /var/www/plugins
然后：
` docker run -d \
  -it \
  --name devtest \
  --mount type=bind,source="/var/www/plugins"/target,target=这里改怎么填呢？ \
  nginx:latest
`

**Comment by fuyun-yipian** [comment]
‘’‘
 docker run -d \
  -it \
  --name devtest \
  --mount type=bind,source="/var/www/plugins"/target,target=这里应该填什么？ \
  nginx:latest
’‘’

**Comment by fuyun-yipian** [comment]
还是说类似这种：
```
    volumes:
      - ./ssl/:/var/www/ssl/:ro
```
但是，具体参数怎么填写呢？求大佬解答

**Comment by jostyee** [comment]
```
volumes:
      - ./plugins:/var/www/plugins.local
```

**Comment by fuyun-yipian** [comment]
感谢大佬的指点，但是为什么还是不行？是我放错了位置吗？还是说需要再运行相关的命令
![image](https://user-images.githubusercontent.com/56331646/66735008-becba400-ee97-11e9-9e16-e74403cf8173.png)
![image](https://user-images.githubusercontent.com/56331646/66735028-c5f2b200-ee97-11e9-8b25-9dee8e45c508.png)

**Comment by fuyun-yipian** [comment]
懂了，原来重新运行`docker-compose up -d`命令后会自动创建一个plugins文件夹
