### ISSUE TITLE
ttrs docker under traefik reverse proxy

### ISSUE THREAD

**Issue by balajeek** [HenryQW/Awesome-TTRSS#84]
Awesome article help me setup this ttrss docker on my ubuntu.  It worked fine on my local network.  I see your sample on nginx reverse proxy, but i am using traefik reverse proxy, I tried my best to put the code in docker-compose yaml but no matter what i try i get "Operation time out" . I wonder if you can provide me a sample of how to configure for traefik reverse proxy.
I was not sure where to ask this but thought may be under Feature request, becaz this is a request.  thanks so much.

**Comment by HenryQW** [comment]
Sorry I don’t plan to support other web servers as this adds more complexities.

If all containers start up successfully, you can use `docker logs ttrss` to check the log.
