### ISSUE TITLE
关于postgresql所用镜像的疑问

### ISSUE THREAD

**Issue by ClarkeCheng** [HenryQW/Awesome-TTRSS#86]
我想问问为什么采用 [sameersbn/postgresql](https://hub.docker.com/r/sameersbn/postgresql) 这个镜像？这个镜像用的是老版本的 postgresql，而且3个月没更新了。为什么不采用 [postgres](https://hub.docker.com/_/postgres) 或 [bitnami/postgresql](https://hub.docker.com/r/bitnami/postgresql)，这两个都一直在更新。

**Comment by HenryQW** [comment]
因为需要启用 pg trgm 插件
