### ISSUE TITLE
关于 ARM 平台的支持请看这里

### ISSUE THREAD

**Issue by ztlgc** [HenryQW/Awesome-TTRSS#89]
现在的树莓派4 的运行内存已经可以达到4G了，对于2G内存的树莓派，运行TTRSS也是没问题的，因为自己还不是太会docker，希望作者可以编译一个😁😁

**Comment by HenryQW** [comment]
你好，最近专注于其他事务，没空找我的树莓派出来测试。麻烦测试以下 branch:

https://github.com/HenryQW/Awesome-TTRSS/tree/arm32v7

目前暂时无法提供 arm-based mercury 以及 opencc。

#88 @virualv #50 @ZhuningS

**Comment by ztlgc** [comment]
在运行 `docker-compose up -d` 之后结果如下
![MTABYd.png](https://s2.ax1x.com/2019/11/22/MTABYd.png)

查看TTRSS日志
![MTEEAe.png](https://s2.ax1x.com/2019/11/22/MTEEAe.png)

想不通问题出在哪里😅😅

**Comment by virualv** [comment]
抱歉由于工作原因，迟迟未测。非常感谢，今天测试使用正常，

Henry Wang <notifications@github.com> 于2019年11月22日周五 上午4:04写道：

**Comment by virualv** [comment]
> 在运行 `docker-compose up -d` 之后结果如下
> ![MTABYd.png](https://camo.githubusercontent.com/02b9fcf015f59d5b282cb9833b255827acd4b731/68747470733a2f2f73322e617831782e636f6d2f323031392f31312f32322f4d54414259642e706e67)
> 
> 查看TTRSS日志
> ![MTEEAe.png](https://camo.githubusercontent.com/d6df367dd2373d2951b1505e8fc6bb602bb653fb/68747470733a2f2f73322e617831782e636f6d2f323031392f31312f32322f4d54454541652e706e67)
> 
> 想不通问题出在哪里😅😅
> `docker-compose.yml` 文件的SELF_URL_PATH填写的树莓派在路由器下的地址

使用docker-compose.dev.yml，填写一下SELF_URL_PATH，docker-compose up -d

**Comment by ztlgc** [comment]
> > 在运行 `docker-compose up -d` 之后结果如下
> > ![MTABYd.png](https://camo.githubusercontent.com/02b9fcf015f59d5b282cb9833b255827acd4b731/68747470733a2f2f73322e617831782e636f6d2f323031392f31312f32322f4d54414259642e706e67)
> > 查看TTRSS日志
> > ![MTEEAe.png](https://camo.githubusercontent.com/d6df367dd2373d2951b1505e8fc6bb602bb653fb/68747470733a2f2f73322e617831782e636f6d2f323031392f31312f32322f4d54454541652e706e67)
> > 想不通问题出在哪里😅😅
> > `docker-compose.yml` 文件的SELF_URL_PATH填写的树莓派在路由器下的地址
> 
> 使用docker-compose.dev.yml，填写一下SELF_URL_PATH，docker-compose up -d

**Comment by ztlgc** [comment]
> > 在运行 `docker-compose up -d` 之后结果如下
> > ![MTABYd.png](https://camo.githubusercontent.com/02b9fcf015f59d5b282cb9833b255827acd4b731/68747470733a2f2f73322e617831782e636f6d2f323031392f31312f32322f4d54414259642e706e67)
> > 查看TTRSS日志
> > ![MTEEAe.png](https://camo.githubusercontent.com/d6df367dd2373d2951b1505e8fc6bb602bb653fb/68747470733a2f2f73322e617831782e636f6d2f323031392f31312f32322f4d54454541652e706e67)
> > 想不通问题出在哪里😅😅
> > `docker-compose.yml` 文件的SELF_URL_PATH填写的树莓派在路由器下的地址
> 
> 使用docker-compose.dev.yml，填写一下SELF_URL_PATH，docker-compose up -d

很不幸，`sudo docker-compose -f docker-compose.dev.yml up -d`之后：
![MO2yqK.png](https://s2.ax1x.com/2019/11/24/MO2yqK.png)

**Comment by HenryQW** [comment]
@ztlgc 从容器名字来看，用错了 compose 文件。请使用 arm32v7 branch 的 docker-compose.dev.yml。

**Comment by HenryQW** [comment]
@virualv 稳定运行三天后通知我😉

**Comment by ztlgc** [comment]
> @ztlgc 从容器名字来看，用错了 compose 文件。请使用 arm32v7 branch 的 docker-compose.dev.yml。

很抱歉，是我弄错了，git不熟悉，没有clone到arm32v7分支，现在解决了，可以正常运行
![MjuUaQ.png](https://s2.ax1x.com/2019/11/25/MjuUaQ.png)

**Comment by virualv** [comment]
好的，但是我发现，这个好像不能以多用户来运行。目前是访问直接进入管理页，即使我设置了SINGLE_USER_MODE=false,依旧是直接进入管理页

**Comment by HenryQW** [comment]
@virualv 我记得在官方论坛看见这个模式初始化的时候会对数据库进行操作，更改选项应该是需要 rebuild 甚至初始化数据库。

```docker-compose -f docker-compose.dev.yml up -d --force-recreate --build```

**Comment by virualv** [comment]
已稳定运行超过72小时

**Comment by HenryQW** [comment]
所有架构都请使用 `latest` tag.

https://github.com/HenryQW/Awesome-TTRSS/commit/bd0cac02baaa35146bcceb0e93027e6865c49c3a
