### ISSUE TITLE
[Feature] 添加 MariaDB 或 MySQL 支持

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [HenryQW/Awesome-TTRSS#91]
**Bug 描述**

```
docker run -it --name ttrss --restart=always `
-e "SELF_URL_PATH=http://localhost:9002/" `
-e "DB_HOST=host.docker.internal" `
-e "DB_PORT=3306" `
-e "DB_NAME=ttrss" `
-e "DB_USER=ttrss" `
-e "DB_PASS=[Redacted]" `
-p "9002:80" `
-d wangqiru/ttrss
```
启动 ttrss 访问后即可见

Please set SELF_URL_PATH to the correct value detected for your server: http://localhost:9002/

实际上停止容器后 python 在同一端口查看 Request Header，Host 没有配置错误：

```
python3 test-server.py
Connection: Keep-Alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Host: localhost:9002
Max-Forwards: 10
TE: trailers
User-Agent: Mozilla/5.0 (Android 10; Mobile; rv:67.0.3) Gecko/67.0.3 Firefox/67.0.3
upgrade-insecure-requests: 1
X-Original-URL: /
X-Forwarded-By: Host
X-Forwarded-For: [Redacted]
X-ARR-SSL: [Redacted]
X-ARR-LOG-ID: [Redacted]
```

**你谷歌/百度了吗？**

Yup...

**部署方法**
 - Docker，使用 latest image

**部署环境**
 - 操作系统: Windows 10 Build 18363.476
 - 反代: IIS 10.0

**错误日志**
```
❯ docker logs ttrss
[24-Nov-2019 12:47:19] NOTICE: fpm is running, pid 10
[12:47:19/11] Spawn interval: 120 sec
[24-Nov-2019 12:47:19] NOTICE: ready to handle connections
<pre>Exception while creating PDO object:SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Address not available
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?</pre>[12:47:20/17] Spawn interval: 120 sec
```

**其他**
光看 log 搞不清楚到底是数据库连接问题还是其他的什么问题……进入容器内部以后 ping Database Host（为 MariaDB）似乎没问题：
```
❯ docker exec -it ttrss /bin/sh
/var/www # ping host.docker.internal
PING host.docker.internal (192.168.65.2): 56 data bytes
64 bytes from 192.168.65.2: seq=0 ttl=37 time=1.192 ms
64 bytes from 192.168.65.2: seq=1 ttl=37 time=1.462 ms
^C
--- host.docker.internal ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 1.192/1.327/1.462 ms
```

**Comment by HenryQW** [comment]
从错误日志来看是数据库连接失败了。IIS是一个魔鬼🙂

**Comment by Aster-the-Med-Stu** [comment]
检查过以后发现是我连错数据库了…端口 3306 上跑的是 MariaDB，而 5432 上跑的才是 PostgreSQL。不过似乎 image 本身也不支持连接到 MariaDB/MySQL

**测试**

```
/var/www # cat <<EOF >> test.php
<?php
$dbname = 'ttrss';
$dbuser = 'ttrss';
$dbpass = '[redacted]';
$dbhost = 'host.docker.internal';
$connect = mysql_connect($dbhost, $dbuser, $dbpass) or die("Unable to Connect to '$dbhost'");
mysql_select_db($dbname) or die("Could not open the db '$dbname'");
$test_query = "SHOW TABLES FROM $dbname";
$result = mysql_query($test_query);
$tblCnt = 0;
while($tbl = mysql_fetch_array($result)) {
  $tblCnt++;
  #echo $tbl[0]."<br />\n";
}
if (!$tblCnt) {
  echo "There are no tables<br />\n";
} else {
  echo "There are $tblCnt tables<br />\n";
}
EOF

/var/www # php -f test.php

PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/test.php:9
```

**Comment by Aster-the-Med-Stu** [comment]
ttrss 上游是支持连接到 MariaDB/MySQL 的，所以或许只要启用 PHP 对 mysql 的支持外加提供一个环境变量选择数据库后端类型？

**Comment by HenryQW** [comment]
https://github.com/HenryQW/Awesome-TTRSS/commit/3925aeef69c482361839de8704d6d8e234d742c6#diff-04c6e90faac2675aa89e2176d2eec7d8R99

https://github.com/HenryQW/Awesome-TTRSS/commit/14f77b794b08fb294295ab55683058eb3ba6c317

As the author of ttrss mentioned:

> Only InnoDB database engine is supported on MySQL. While you technically can force tt-rss schema under MyISAM you will experience various glitches due to missing functionality (foreign keys, cascade deletes, etc.) that tt-rss actively uses. 

MySQL was once supported, I decided to drop it, it was problematic for me, the biggest one, emoji was not rendering, I'm not sure if that's still an issue with MySQL. There were other funny issues I can't recall, and I spent some good hours on fixes but to no avail.

The moment I switched to Postgres, bang, everything works perfectly. I'm not a database guy, but Postgres is IMO better than MySQL in this case. Thus I'm opinionated about supporting Postgres only.

**Comment by Aster-the-Med-Stu** [comment]
@HenryQW 拿 LinuxServer 的 Docker 试用过了，实际上 TT-RSS MariaDB/MySQL 没法显示 Emoji 主要原因是它 schema 下面初始化 MySQL 的 character set 是 UTF8 而不是 UTF8MB4。你当时部署的时候碰上什么奇怪的问题，这里可以协助测试一下。

![图片](https://user-images.githubusercontent.com/32929636/69690045-801b4180-1105-11ea-93fc-67e49102d4aa.png)

**Comment by HenryQW** [comment]
忘记了，反正从那之后 MySQL 一生黑，我所有的部署都用了 PG。
