### ISSUE TITLE
ARM64v8平台是不是不支持呢

### ISSUE THREAD

**Issue by ztlgc** [HenryQW/Awesome-TTRSS#96]
`master` 分支下的`docker-compose.yml`和`docker-compose.arm32v7.yml`的我都试过了，都是`Restarting (1)`状态

**Comment by HenryQW** [comment]
暂不支持，最近没空增加。

**Comment by ztlgc** [comment]
报错了
![UTOOLS1575172788433.png](https://i.loli.net/2019/12/01/dMNERbpP5zZaHX6.png)

**Comment by HenryQW** [comment]
你需要git checkout dev

**Comment by ztlgc** [comment]
> 你需要git checkout dev

还是不行啊，是我的机子有问题吗
![UTOOLS1575364760990.png](https://i.loli.net/2019/12/03/sxFG5HfmrPRi1E8.png)

**Comment by HenryQW** [comment]
移除了 qemu 便于本地测试，再试试。

**Comment by ztlgc** [comment]
可以启动了
![UTOOLS1575548472297.png](https://i.loli.net/2019/12/05/sKg1VrJfEbO6doc.png)

**Comment by HenryQW** [comment]
确认稳定运行三天后我开始merge👌

**Comment by ztlgc** [comment]
已稳定运行三天

**Comment by HenryQW** [comment]
arm64v8 镜像不知为何无法在 dockerhub build，我测试了本地可以 build 并且运行成功。
