### ISSUE TITLE
[BUG]php alpine libiconv 中文编码错误

### ISSUE THREAD

**Issue by HeathLee** [HenryQW/Awesome-TTRSS#98]
alipine 镜像里的 libiconv，遇到 gbk、gb2312 等编码的 rss 订阅源时会遇到如下错误
![image](https://user-images.githubusercontent.com/7382922/70242232-6df76e00-17ab-11ea-90f4-9ddf0ebee6e5.png)
换成 gnu-libiconv 可以解决
https://github.com/aliyun/aliyun-oss-php-sdk/issues/97
https://github.com/wallabag/docker/pull/158

**Comment by HeathLee** [comment]
我没环境测试 arm32 是否存在此问题和是否适用此方法，所以就不直接提 pr了

**Comment by HenryQW** [comment]
interesting finding！底层镜像都是原版 alpine，应该都会受这个影响。能否提供 rss 源地址便于测试？@ztlgc 麻烦帮忙测试 arm 环境是否有个问题？

**Comment by HeathLee** [comment]
一个可复现的例子 https://blog.codingnow.com/atom.xml

**Comment by virualv** [comment]
﻿
你好，有类似问题


Send by virualv 



Send by virualv

**Comment by ztlgc** [comment]
> interesting finding！底层镜像都是原版 alpine，应该都会受这个影响。能否提供 rss 源地址便于测试？@virualv @ztlgc 麻烦帮忙测试 arm 环境是否有这个问题？

同样的错误
![UTOOLS1575638253877.png](https://i.loli.net/2019/12/06/M8sen3EP71NcZbG.png)

![UTOOLS1575638229848.png](https://i.loli.net/2019/12/06/WxTizMlo56V8DAs.png)

**Comment by cocakuma** [comment]
我使用最新的镜像依然会碰到这个问题，还是云风的博客 https://blog.codingnow.com/atom.xml

**Comment by HenryQW** [comment]
@cocakuma 我本地修复了这个问题，gnu-libiconv 1.16就会出现这个问题，旧版本没事：

```
apk add gnu-libiconv=1.15-r3
```

![image](https://user-images.githubusercontent.com/5896343/108536422-5d5de580-72d4-11eb-9b71-ca18b71c27ae.png)



但是上游 ttrss 改动太多了，有其他的bug。半小时前https://git.tt-rss.org/fox/tt-rss/commit/cf249d7e8c55542ca6383b430ec77f07401e96ea 又把首页改跪了。

![image](https://user-images.githubusercontent.com/5896343/108536350-47e8bb80-72d4-11eb-94f2-494222cac9dd.png)

我先reopen这个，等上游稳定了再关闭。

**Comment by HenryQW** [comment]
最新镜像修复了该问题。
